### ISSUE TITLE
Not loading Google Analytics script on Safari when debug mode is disabled

### ISSUE THREAD

**Issue by meta7x** [MatteoGabriele/vue-analytics#100]
### Description

On loading the page in Safari, Vue Analytics throws the following error:
[vue-analytics] It's not possible to load Google Analytics script (vue-analytics.js:1:4643)

This occurs locally and served on a server, but only when debug mode is disabled. When debug mode is enabled, the script loads as expected.

Tested on Chrome, Firefox and Safari. The first two work as expected.

### Expected behavior

The script should load just like in debug mode.

### Actual behavior

The script doesn't load and an error is thrown.

### Environment

Version: vue-analytics@5.9.1
OS: macOS 10.12.4
Browser: Safari 10.1

### Reproducible Demo

This is my code concerning Vue Analytics:

`
import router from './router'

const isProd = process.env.NODE_ENV == 'production'

//...

import VueAnalytics from 'vue-analytics'
Vue.use(VueAnalytics, {
  router,
  id: 'UA-115865971-1',
  debug: {
    enabled: !isProd,
    sendHitTask: isProd,
  }
})`

**Comment by MatteoGabriele** [comment]
hi @meta7x 
I'm sorry but I can't reproduce this error, would you mind providing a public repository with a simple vue-cli application that reproduces this behavior?

thanks for your time

**Comment by meta7x** [comment]
https://github.com/meta7x/vue-analytics-bug

Here I used the Vue webpack template, as I did with my project and the issue persists.
I highlighted line 13 in /src/main.js, because changing that from true to false breaks Vue Analytics on my Safari. I've tried closing and reopening Safari and emptying the cache, but so far nothing has worked...

**Comment by meta7x** [comment]
I've just realized that my Adblock seems to be the problem. Turning it off gets rid of the error.
Is that intended behaviour?

**Comment by MatteoGabriele** [comment]
I was exactly thinking about browser extensions. It is an intended behavior to have unintended behaviors when u install AdBlock :)
It probably blocks the script from been loaded and so the promise is rejected.
The debug enabled loads a different script called analytics_debug.js and probably AdBlock doesn't care about it.
