### ISSUE TITLE
[Ask] Is Plugin support for send Screen Tracking?

### ISSUE THREAD

**Issue by moogreentea** [MatteoGabriele/vue-analytics#102]
Hi,

i need to send screen views for tracking behevior but not found events for do it.

Is it possible to send Screen Tracking pass by plugin?

Info for App / Screen Tracking https://developers.google.com/analytics/devguides/collection/analyticsjs/screens

Thanks,
Chan

**Comment by MatteoGabriele** [comment]
Unfortunately not, I actually wanted to add that possibility.
For now you could go with $ga.query() which is like using window.ga and u have access to everything, but the auotracking works only with pageview.

Probably this weekend I'll add it

**Comment by moogreentea** [comment]
Hi,

Just try to send this.$ga.query('send', 'screenview', { screenName: 'Top 5 News' });
and already set appName 

but not found screen tracking data on Google Analytics

Could please any suggest ?

**Comment by MatteoGabriele** [comment]
Can I see your plug-in installation? Other then that I can only suggest to wait a bit and maybe they will start registering them. Sometimes analytics takes time, sometimes is immediate.

**Comment by moogreentea** [comment]
Oh, Thanks you for your fast reply :)

i think i will wait more about screen tracking data.

Thanks,
Chan

**Comment by MatteoGabriele** [comment]
been implemented in v5.10
