### ISSUE TITLE
GDPR and the ability to turn off GA programmatically 

### ISSUE THREAD

**Issue by harryhazza77** [MatteoGabriele/vue-analytics#103]
Hi, thank you for your plugin. I'm UK based and this issue effects any page being browsed from the EU or Switzerland. We now have to give users a choice to opt out of google analytics tracking i.e. programmatically. Is this currently supported?

**Comment by MatteoGabriele** [comment]
Ah good one! I actually need to be GDPR friendly as well so I will definitely take care of this feature asap.

Right now is not really possible to disable it once is installed, the only workaround would be to pass 'false' to debug.sendHitTasks but it's a sync operation

**Comment by harryhazza77** [comment]
I've found this https://developers.google.com/analytics/devguides/collection/analyticsjs/user-opt-out which contains `window['ga-disable-UA-XXXXX-Y'] = true;` so this might be a workaround for now

**Comment by MatteoGabriele** [comment]
Ah nice! Will keep that in mind. Thanks for the suggestion

**Comment by harryhazza77** [comment]
👍
