### ISSUE TITLE
No results in GA using vue-analytics and AWS

### ISSUE THREAD

**Issue by farbodg** [MatteoGabriele/vue-analytics#104]
Hi,

I've followed the documentation, and added vue-analytics to my vue application by adding the following to my **src/main.js** file (with the appropriate tracking ID):

```
import Vue from 'vue'
import VueAnalytics from 'vue-analytics'

Vue.use(VueAnalytics, {
  id: 'UA-XXX-X'
})
```

I built my application using **npm run build** and uploaded it to my AWS S3 instance. I hopped onto my website and checked my Google Analytics console and I do not see any active users on it. I thought it may take a while before my website registered with GA and so I came back to it the next day and it still does not show anything.

I turned on debugging, and the [logs show everything is working as expected](https://imgur.com/a/5ayij), with my appropriate tracking ID. 

I tried removing vue-analytics, and going down the usual route, which is pasting the javascript code GA gave me into my index.html file. After doing that, GA is showing active users and all relevant information.

**Comment by MatteoGabriele** [comment]
close it for inactivity. feel free to open it again when you have a riproduction

**Comment by QuantumInformation** [comment]
I used the router and have the same issue on google cloud

https://github.com/MatteoGabriele/vue-analytics/issues/190
