### ISSUE TITLE
ignoreRoutes does not seem to work

### ISSUE THREAD

**Issue by ligne13** [MatteoGabriele/vue-analytics#105]
### Description

ignoreRoutes does not seem to work.
AutoTracking is enabled. I've added a route name to the ignoreRoutes array but the pageview is still called automatically.

### Expected behavior

The pageview should not be triggered when going to the route matching the route name inserted in the ignoredRoutes array.

### Actual behavior

The pageview is called.

### Environment

Run this command in the project folder and fill in their results:

`npm ls vue-analytics`: vue-analytics@5.10.0 

Then, specify:

1. Operating system: MacOS 10.12.6
2. Browser and version: Chrome 65

### My Code

```
// Routes
const routes = [
    {
        name: "home",
        path: "/",
        component: Feed,
    },
    {
        name: "page",
        path: "/page/:pageId",
        component: Page,
        props: true,
    },
];
// Analytics
Vue.use(VueAnalytics, {
    id: 'UA-XXXXXX-X',
    router,
    autoTracking: {
        page: true,
        pageviewOnLoad: false,
    },
    ignoreRoutes: ['page'],
});
```

**Comment by MatteoGabriele** [comment]
hi @ligne13 
thanks for your feedback, I will have a look and see if I can replicate the error
