### ISSUE TITLE
TypeError inside hook (works in v5.9.1)

### ISSUE THREAD

**Issue by hopscotcher** [MatteoGabriele/vue-analytics#106]
### Description

TypeError

### Expected behavior

Executing Google Analytics commands.
Running command: ga("send", "event", "category", "action", "label", 123)

### Actual behavior

[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'apply' of undefined"

### Environment

`npm ls vue-analytics`: vue-analytics@5.10.0  

1. Operating system: Ubuntu 16.04.3 LTS
2. Browser and version: Google Chrome 65.0.3325.181

### Reproducible Demo

  mounted () {
    this.$ga.event('category', 'action', 'label', 123)
  }

**Comment by MatteoGabriele** [comment]
@hopscotcher thanks for your feedback!
fixed with 5.10.1
