### ISSUE TITLE
Best way to call opt-out function in a component

### ISSUE THREAD

**Issue by markusdanek** [MatteoGabriele/vue-analytics#109]
Hi,

I have a own component for a cookie message warning (regarding GDPR).

In this [component](https://github.com/markusdanek/vuejs-meetup-talk-gdpr/blob/master/vue-app/src/components/CookieMessage.vue) I have a method "accept()" which sets a localStorage item and should also set the opt-out function from your plugin.

Would be this the correct way to do it?

```
accept() {
    this.setGDPR();
    this.isOpen = false;
    this.$emit('accept');
    Vue.use(VueAnalytics, {
        id: 'UA-XXX-X',
        disabled: false
    })
}
```

In my main.js file I initialize your plugin like it is described in the README.

Thank you!

**Comment by MatteoGabriele** [comment]
hi @markusdanek 
I don't think this is the best way to do it.

What I would suggest is to have an end-point to call and let its response disable/enable the opt-in.

The `disabled` prop accepts plain booleans, promises, functions, and functions that return promises so you could, for example, opt for something like this

```js]
import Vue from 'vue'
import VueAnalaytics from 'vue-analytics'
import axios from 'axios'

Vue.use(VueAnalytics, {
  id: 'aaaaaa',
  disabled: () => {
    return axios.get('/api/user/123/analytics-opt-in').then(response => {
      return response.data
    })
  }
})
```

Of course this one only works if your user has already choosen which option, otherwise it's quite difficult. 
Could also be that you can drop a message that analytics will start working on the next refresh or something. 
Not quite sure about that. Let me know if works otherwise I could look if it's possible to have that property reactive.

**Comment by markusdanek** [comment]
Hi @MatteoGabriele 
thank you for your quick reply! ☺️

I totally understand your suggestion with the end-point but I think it's a litte over-engineering for my use case.

What I want to achieve is a little demonstration how to add a cookie message component to a Vue.js project and when clicking on the "Accept" or "Deny" buttons it should set the disabled boolean to "true"/"false". 

So in my case I do not have any end-points to call but just want to check with the debug mode if the tracking is activated or deactivated.

Does it make sense what I want to do? 😅

**Comment by MatteoGabriele** [comment]
I totally understand your use case, but Google Analytics can't opt-in/opt-out in runtime: it needs to be done **before** you create the trackers.

You only have two options: 
- you already know the user choice and use the `disabled` prop to apply the value of your cookie.
- you need to install it after a click event which I really don't like but I guess it's possible.

**Comment by markusdanek** [comment]
Ah okay, did not know that with the runtime!

> You need to install it after a click event which I really don't like but I guess it's possible.

So that would result to the following methods, right?
```
accept() {
    this.isOpen = false;
    Vue.use(VueAnalytics, {
        id: 'UA-XXXXXXXX-X',
        disabled: false,
        debug: {
            enabled: true,
            trace: true,
            sendHitTask: true
        },
        fields: {
            cookieDomain: 'none'
        }
   })
},
deny() {
    this.isOpen = false;
    Vue.use(VueAnalytics, {
        id: 'UA-54514383-9',
        disabled: true,
        debug: {
            enabled: true,
            trace: true,
            sendHitTask: true
        },
        fields: {
            cookieDomain: 'none'
        }
    })
}
```

In this case it sets the **_ga** cookies but after I reload I do not get any debugs anymore.

> You already know the user choice and use the disabled prop to apply the value of your cookie.

I can't understand what you are meaning with that 🙈
Where would I set the prop?

Btw: Is there a way to buy you a beer/coffee? ☺️

**Comment by MatteoGabriele** [comment]
I am saying that if the cookie/localStorage exists it means that the user already came once and he decided to opt-in or opt-out.
In this case, you could do something like this:

```js
import Vue from 'vue'
import VueAnalaytics from 'vue-analytics'
import axios from 'axios'

const optIn = localStorage.getItem('opt-in')

if (typeof optIn !== 'undefined') {
  Vue.use(VueAnalytics, {
    id: 'aaaaaa',
    disabled: optIn 
  })
}
```

In case the user just came in your website, you might use that click handler to run analytics, but you don't need to install the plugin if it denies it: will be pointless.

```js
export default {
  name: 'MyComponent', 

  methods: {
    accepts () {
      Vue.use(VueAnalytics, {
        id: 'aaaaaa'
        // no needs to specify `disabled`
      })
    }
  }
}
```

**Comment by MatteoGabriele** [comment]
ps: I don't know how you could buy me a coffee, unless you live in Amsterdam :D, but thanks for the gesture :)

**Comment by harryhazza77** [comment]
Hi @markusdanek. 

> but it does not work.

I'm not sure why it didn't work for you. I am trying to achieve the same thing regarding GDPR in which, IMHO, this brilliant module must be disabled at the beginning and enabled after asking permission to track the users activity. For me, I was able to toggle `window["ga-disable-UA-XXX"]` at runtime and see tracking events being sent (if allowed) and no longer being sent (if denied).

**Comment by MatteoGabriele** [comment]
Yeah, I misread the API specification. 
It is not before trackers but before you do a call to the `ga` object.
I will try to see if there's a way to make property observable without making the application heavier with some strange libraries: I can probably just use a Vue instance.

**Comment by harryhazza77** [comment]
Anything to get that ugly window global out of my Vuex Mutation would be great!

**Comment by leo-coco** [comment]
@MatteoGabriele Do you have anyway to check wether the tracking is actually disable or enable ? 

I trigger this function 

>  enableTracking () {
>       this.$ga.enable()
>       // from now on analytics is enabled
>     }

or even tried to write 

> $vm0.$ga.disable

 in the console but it seems to me that nothing happened. When I check on the real time traffic on Analytics, it is still active.

**Comment by MatteoGabriele** [comment]
Not really, sorry. Could you try it locally enabling the debug mode? You can have a better insight of what's happening in your application

**Comment by leo-coco** [comment]
I installed Google Analytics Debug extension to check what is going on -> apparently nothing. Triggering the function `$ga.enable or $ga.disable;`do not affect the state of analytic in the debugger but it does change `window['ga-disable-UA-myID']`

**Comment by MatteoGabriele** [comment]
Analytics debug is already built-in in the plug-in, but yeah is the same thing.
I can just suggest u to create a repository with this issue so I can have a look. Use vue CLI and add the minimum necessary to show me the problem

Thanks

**Comment by mystrdat** [comment]
Same issue here, but I don't see the module switching `window['ga-disable-UA-myID']` correctly.

**Comment by pandalion** [comment]
Hi @MatteoGabriele does your vue-gtag library have a similar enableTracking and disableTracking? I am trying to replace `vue-analytics` with this one. thank you :)
