### ISSUE TITLE
checkDuplicatedScript option no longer working

### ISSUE THREAD

**Issue by tdolsen** [MatteoGabriele/vue-analytics#110]
### Description

The `checkDuplicatedScript` option is no longer working. It was removed in commit 0357b615f4f5c576dd754fb3bc2d0cc04effac73. This results in the script being loaded twice using [PrerenderSPAPlugin](https://github.com/chrisvfritz/prerender-spa-plugin) as described in issue #60.

It's not clear to me whether this was intentionally done, enabling some other way to solve this. If that's the case would I expect this to be reflected in the [script-loader.md](https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/script-loader.md) docs.

If this change was unintended can I offer to re-enable the expected behavior. Seems simple enough, given `hasGoogleScript` still does what it implies.

### Expected behavior

For bootstrapping to identify whether script tag has been injected, and only inject if missing.

### Actual behavior

Injects script tag regardless.

### Environment

1. `vue-analytics@5.10.2`
1. Operating system: Any
2. Browser and version: Any

### Reproducible Demo

Shouldn't be needed, the function calls are removed from the source.

**Comment by MatteoGabriele** [comment]
Hi @tdolsen, thanks for your feedback.
This feature should still be available, I'm going to check whether or not is still working: otherwise, it's a bug that I will fix :)
