### ISSUE TITLE
Dynamic id

### ISSUE THREAD

**Issue by ggirodda** [MatteoGabriele/vue-analytics#111]
Hello,
I already post this question in nuxtjs google analytics module
https://nuxtjs.cmty.io/nuxt-community/analytics-module/issues/c12
but I think it's more inherent to put it here.
How can I put id dynamically ? I use a custom api module wich retrive some information such as the google analytics id, but it is called in a middleware.
I see that in vue-analytics I can put a Promise instead of the id, but I just want to take the id in my store, I don't want to perform another request, because requests have to be done through the plugin I created, and because I already do that for verification pourpose in the middleware
I try to do that, but google tag assistant doesn't see th UA code:
nuxt.config.js

`{src: '~/plugins/vue-analytics.js', ssr: false},`

/plugins/vue-analytics.js

```
import Vue from 'vue'
import VueAnalytics from 'vue-analytics'

export default ({ store }) => {
  Vue.use(VueAnalytics, {
    id: store.state.descs.google_analytics,
    ecommerce: {
      enabled: true
    }
  })
}

```

**Comment by MatteoGabriele** [comment]
Hi @ggirodda, I'm also in the other repository so no problem with that, but be sure to close that ticket or we'll have duplicates.

About your issue, I'm sorry but the ID field already has plenty of options: strings, arrays, functions, functions that return promises and plain promises.
There's even an integration with Vuex, but the initialization needs to be done as explained in the documentation: everyone has so many ways to achieve the same purpose that it's impossible to satisfy every one of them.
I would suggest to just add manually the id or retrieve it from an API end-point.

**Comment by ggirodda** [comment]
Ok, thank you for your reply and for your work

**Comment by MatteoGabriele** [comment]
@ggirodda my pleasure :)
