### ISSUE TITLE
Avoid using lodash.merge, possible?

### ISSUE THREAD

**Issue by shershen08** [MatteoGabriele/vue-analytics#12]
Is that possible to replace lodash.merge with some simpler function,
the [package is 2.2KLOC](https://github.com/lodash/lodash/blob/4.6.0-npm-packages/lodash.merge/index.js) itself which is 10x more that the vue-analytics.js file

**Comment by MatteoGabriele** [comment]
@shershen08 yes i was thinking to make something custom to shrink the size.

thanks to remind me this actually :)

**Comment by shershen08** [comment]
That'd be great!
Since it's used in only one place - merging the options defaults with the actual called options afaik.

**Comment by MatteoGabriele** [comment]
yeah I think something like an `Object.assign` will do the trick

**Comment by shershen08** [comment]
Since Object.assign is ES6, and that's not same browser support as the [original framework, vue.js does](https://github.com/vuejs/vue), so maybe [go for a polyfilled version](https://github.com/sindresorhus/object-assign) - 
or e.g. I just did it like [this in vue-masonry plugin](https://github.com/shershen08/vue-masonry/blob/master/src/masonry.plugin.js#L19)

**Comment by MatteoGabriele** [comment]
@shershen08 just published v2.3.1
