### ISSUE TITLE
Question about page tracking

### ISSUE THREAD

**Issue by Jarzka** [MatteoGabriele/vue-analytics#123]
Relating to:

https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/page-tracking.md
`this.$ga.page('/')`

What is `this` in this example? Can't I just call Google analytics directly to track a page load, for example inside `router.beforeEach` function.

EDIT: In this tutorial, they are using `ga` directly:
https://serversideup.net/google-analytics-vue-router-single-page-application/

**Comment by MatteoGabriele** [comment]
hi @Jarzka 
`this` is the scope of your component.
to track pages just use the instance of your router like described here https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/page-tracking.md#enable-page-auto-tracking

**Comment by Jarzka** [comment]
Oh, sorry, I did not notice there was that automatic page tracking section.

Thanks for help!

**Comment by MatteoGabriele** [comment]
@Jarzka no problem :)
btw the example you've posted is just a simple implementation of google analytics inside a vue application, this plugin provides an actual wrapper of that library for Vue and implements more useful utilities like the automatic route tracking and more
