### ISSUE TITLE
Using pageViewTemplate in router prevents page from being set

### ISSUE THREAD

**Issue by mwaldstein** [MatteoGabriele/vue-analytics#124]
### Description

Using pageViewTemplate only causes pageview's to be sent, without any 'set' command, causing events to be mis-assigned to the wrong page.

### Expected behavior

a page 'set' command should still be set

### Problem Exploration

 * In `trackRoute`, if there is a pageviewTemplate, it is used to create the parameter sent to `page` rather than the route - https://github.com/MatteoGabriele/vue-analytics/blob/master/src/lib/page.js#L70
 * If `page` isn't provided with a route or router, it only sends a pageview with the parameters passed - https://github.com/MatteoGabriele/vue-analytics/blob/master/src/lib/page.js#L46 - A 'set' is only called if there is a route (or router passed).

### Possible solutions 

 * Set the page in trackRoute if 'proxy' is defined, using 'page' from the proxy return.
 * Move the logic for handling routes and pageviewTemplates into the 'page' function - this would also address the issue that if you manually call `this.$ga.page(this.$router)` it doesn't use any defined pageviewTemplate

**Comment by MatteoGabriele** [comment]
hi @mwaldstein 
I've actually seen this bug couple of days ago and I forgot to add an issue for it.

thanks a lot for your feedback, I will fix it asap :)
