### ISSUE TITLE
Confliction between page tracking and screen tracking?

### ISSUE THREAD

**Issue by L-Jovi** [MatteoGabriele/vue-analytics#126]
Hi, it's not a bug, just question as title said.

Is it no possible to enable both page tracking and screen tracking?

I follow the [document - page-tracking](https://matteogabriele.gitbooks.io/vue-analytics/content/docs/page-tracking.html) and successfully record page info, I can see chrome console output when I switch page.

But then I add screenview `track` under `methods` of module, I notice that's no output like `ga("send", "screenview" ...)`

My code config like below.

__Init ga__

![image](https://user-images.githubusercontent.com/7262199/40277952-b1e06a1c-5c5a-11e8-99e6-af8b7afedce4.png)

__pageview tracking__

Just one child config of routers.

![image](https://user-images.githubusercontent.com/7262199/40277966-e192cfe8-5c5a-11e8-8437-f93e99ed9f88.png)

__screenview tracking__

Below method `track` not fire.

![image](https://user-images.githubusercontent.com/7262199/40277945-a04ec0fa-5c5a-11e8-8c8c-b16f5fb65d2a.png)

How should I tracking both pageview and screenview ?

Thanks for your time :)

regards.

**Comment by MatteoGabriele** [comment]
hi @L-Jovi not really sure about your setup, could you please create a small app with vue-cli and do the same thing so I can have a look.

is not possible to have autotracking with both methods: or you track pageviews or you track screenview, but the screenview method available in the $ga api is available anytime and should work.

**Comment by L-Jovi** [comment]
Thanks for your reply :)

Maybe I could extract key code to setup new demo by vue-cli later, if I cause any trouble, feel free to close the issue.

regards.

**Comment by MatteoGabriele** [comment]
no man, no problems. 
I tagged it as a question but if you don't reply within a couple of weeks I'll close it: my policy :D
