### ISSUE TITLE
Home page not registered

### ISSUE THREAD

**Issue by Sephen** [MatteoGabriele/vue-analytics#129]
In my Vue App I've got two routes home and page. 
Page is being registered in Google Analytics but the homepage is being ignored

```
import Vue from 'vue'
import Router from 'vue-router'
import VueAnalytics from 'vue-analytics'

import Home from '@/components/Home'
import Page from '@/components/Page'

Vue.use(Router)

export default new Router({
  mode: 'history',
  routes: [
    {
      path: '/',
      name: 'Home',
      component: Home
    }, {
      path: '/page/:slug',
      name: 'page',
      component: page
    }
  ]
})

// Google Analytics
Vue.use(VueAnalytics, {
  id: process.env.GA_CODE,
  Router
})
```

I've tried the following: 
`this.$ga.page(this.$router)`

`this.$ga.page('/')`
    
```
this.$ga.page({
  page: '/',
  title: 'Home page',
  location: window.location.href
})
```
But none of the above sends the data to Google Analytics. The other page uses: `this.$ga.page(this.$router)` which just works.

In both routes the Analytics is called in the created method like:

```
...
created () {
  this.$ga.page(this.$router)
}
...
```
Does anybody know what i'm doing wrong?

**Comment by MatteoGabriele** [comment]
hi @Sephen the autotracking works with your instance of vue-router, not with vue-router itself.

you need to pass what you are currently exporting as default in that first snippet

```js
import Vue from 'vue'
import Router from 'vue-router'
import VueAnalytics from 'vue-analytics'

import Home from '@/components/Home'
import Page from '@/components/Page'

Vue.use(Router)

const router = new Router({
  mode: 'history',
  routes: [
    {
      path: '/',
      name: 'Home',
      component: Home
    }, {
      path: '/page/:slug',
      name: 'page',
      component: page
    }
  ]
})

// Google Analytics
Vue.use(VueAnalytics, {
  id: process.env.GA_CODE,
  router
})

export default router
```

**Comment by vesper8** [comment]
this could use way better documentation... I shouldn't be finding out how to use this with a router by perusing dozens of issues

**Comment by MatteoGabriele** [comment]
@vesper8 I'm sorry man but there's plenty of documentation, examples, articles on Medium about this plugin and how to use it. 
If you guys just install plugins and pretend to make it work without not event read 2 lines about it and without understanding the tools you use: it's on you.

And the most important thing of all: always remember to be polite with open source developers. We're not paid by anyone and we make the best we can because we like it, but we're not here to do your job, but just to make it easier.

cheers
