### ISSUE TITLE
Perf issues on v-ga

### ISSUE THREAD

**Issue by darkylmnx** [MatteoGabriele/vue-analytics#130]
This is more of a suggestion than a "bug" but there are issues performances and memory leak on v-ga because you add events but never remove them, so if for example I switch a component 10 times, the events are still somewhere in memory but not used.

**Comment by MatteoGabriele** [comment]
thanks @darkylmnx 
I will look into that :)

**Comment by basvangeffen** [comment]
Maybe I misunderstood the issue @darkylmnx addresses, but it sounds like its about (not) removing the event handler on unbind. I was worried about that specific issue, but after looking into this, it seems like Vue takes care of this. See [this discussion and issue](https://github.com/vuejs/vue/issues/314) for an elaborate explanation -- in particular the last few comments.

**Comment by darkylmnx** [comment]
@basvangeffen well it seems that there's no final answer on this as on the Vue forum, Linus was sayinf it's better to remove events, but I guess it's more about non DOM-reated events, things like events on window or on the document, events not on the directive root node or it's children so yeah, for this issue it's no more accurate.
