### ISSUE TITLE
support for quasar framework?

### ISSUE THREAD

**Issue by haimsitt** [MatteoGabriele/vue-analytics#131]
Hi!
I tried to run this code, but I couldn't see my page views in google analytics (not locally as well).

![image](https://user-images.githubusercontent.com/39988091/41029568-a3972fea-6984-11e8-8bb3-5b263aa52913.png)

I am using quasar framework and build with:  quasar build -m pwa
I am stuck on this one could you please help me out?

**Comment by MatteoGabriele** [comment]
I think is because you are passing a `Router` property, but the plugin is looking for a `router` property.
