### ISSUE TITLE
Plugin doesn't seem to boot.

### ISSUE THREAD

**Issue by websanova** [MatteoGabriele/vue-analytics#133]
### Description

Just doesn't seem to be working at all, no idea.

```
"vue": "2.5.14",
"vue-analytics": "5.12.2",
```

```
Vue.use(require('vue-analytics'), {
        id: 'UA-12345678-99',
        router: Vue.router,
        debug: {
            enabled: true,
            trace: true,
            sendHitTask: true
        }
    });
```

* No console / debug output
* No ga scripts loading.
* No other requests for page, etc being made.
* Shows `undefined` when doing  `console.log(this.$ga)` or `console.log(this.ga)`
* No errors

I'm stumped, I thought at least some error, or output, but the plugin seems to be loading...(maybe)

I also tried adding the ga include code on my own, which then loads the script fine but still nothing working, still `undefined`, etc.

It's like it just doesn't boot or init, maybe I'm missing something simple...

**Comment by MatteoGabriele** [comment]
Hi @websanova 
I should probably make this more clear somewhere because you're like the third person that asks me that :)

The plugin has only one build and it has a **default export**.
This means that you can import it with es6 syntax `import VueAnalytics from 'vue-analytics'` or with es5 syntax `const VueAnalytics = require('vue-analytics).default`

I will update documentation to make this clear

**Comment by websanova** [comment]
Yes,

I just painfully figured this out.

```
Vue.use(require('vue-analytics').default, {
        id: 'UA-12380236-25',
        router: Vue.router,
});
```

Thx for the reply :-)

**Comment by MatteoGabriele** [comment]
you're welcome. I'm actually working on version 6, with some other features, webpack 4 build, also the possibility to load the plugin via script tag and so on.

**Comment by DevinWatson** [comment]
Just spent a day fighting the same issue. Analytics.js was loading just not doing a GET on the collect endpoint. Maybe update the documentation to be a bit more clear.

**Comment by MatteoGabriele** [comment]
I've already updated the documentation days ago
