### ISSUE TITLE
Campaign

### ISSUE THREAD

**Issue by ben182** [MatteoGabriele/vue-analytics#136]
Hi,

how can I track campaigns with utm get params?

**Comment by MatteoGabriele** [comment]
I don't really used it for campaigns to be honest. Could you let me know how do you usually do it.

thanks :)

**Comment by ben182** [comment]
Hi. Look at this: https://support.google.com/analytics/answer/1033863?hl=en
How can I use it with the API?

**Comment by MatteoGabriele** [comment]
Well, to me they just look like parameters to add to a specific URL, so just append it to a link like you would do normally. This example doesn't use any of the google analytics API

**Comment by ben182** [comment]
The problem is that I does not work with vue router. For example#: http://example.com/#/?utm_source=exampleblog&utm_medium=referral&utm_campaign=summer-sale. It does not send the request to google

**Comment by ben182** [comment]
This does not work neither: http://example.com/?utm_source=exampleblog&utm_medium=referral&utm_campaign=summer-sale

**Comment by MatteoGabriele** [comment]
@ben182 could you please create a small repository with vue-cli and recreate this issue on that. Would be really helpful 

thanks for your time

cheers

**Comment by MatteoGabriele** [comment]
closed due to inactivity
