### ISSUE TITLE
Mandatory analytics property when using meta for another plugin

### ISSUE THREAD

**Issue by Bob-Thomas** [MatteoGabriele/vue-analytics#138]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description

I have my own vuex plugin running for local storage caching that also uses the meta object.
```
{ meta: {cache:bool}}
```
and sometimes I want to cache a mutation but not use analytics.
### Expected behavior

Using a `{meta:{cache:true}}` shouldn't trigger the `throw new Error('The "analytics" property needs to be an array')` error and just let me use cache keyword with needing a analytics property as well.

### Actual behavior

It sends out the `throw new Error('The "analytics" property needs to be an array')` and doesn't propagate my request further.

### Proposal

Do an extra check if the object contains the analytics property and if not `return` else `continue`

**Comment by Bob-Thomas** [comment]
@MatteoGabriele did everything go okay?

Can I close the issue now ?

**Comment by Bob-Thomas** [comment]
@MatteoGabriele no worries, for now I just use my own fork.
Thank you for delivering this awesome tool take your time

**Comment by MatteoGabriele** [comment]
I think I get it, probably is due to the recent eslint package hack. NPM had to revoke all tokens. 
I think that Travis is not allowed anymore to publish in my account because the token expired.

**Comment by MatteoGabriele** [comment]
yes! I had to remove the old token and add a new one!
that was a pain in the ass to find out!

thanks again for your contribution!

The package is deployed v5.12.3

cheers!
