### ISSUE TITLE
An event triggered before the GA library is loaded is ignored

### ISSUE THREAD

**Issue by i4ntch1k** [MatteoGabriele/vue-analytics#142]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description

An event triggered by a "mounted" hook in a component is ignored since GA is not fully loaded yet.

### Expected behavior

The event should be delayed until the library is fully loaded and then triggered.

### Actual behavior

The event is triggered and fails since no tracker has been created yet.
Here is what displays Google Analytics Debugger addon on Chrome: 
Initializing Google Analytics.
analytics_debug.js:10 Running command: ga("send", "event", {eventCategory: "myCategory", eventAction: "myAction", eventLabel: "myLabel"})
analytics_debug.js:10 Command ignored. Unknown target: undefined
analytics_debug.js:10 Running command: ga("create", "UA-…", "auto", {})
analytics_debug.js:10 Creating new tracker: t0
analytics_debug.js:10 Auto cookieDomain found: "none"
analytics_debug.js:10 Registered new plugin: ga(provide, "render", Function)
(the "pageview" command successfully appears in GA dashboard, but not the "event")

Subsequent events are well triggered and appear in GA dashboard.

### Environment

vue-analytics@5.12.2

Then, specify:

1. Operating system: MacOS 10.13.6
2. Browser and version: Chrome, Version 67.0.3396.99 (Official Build) (64-bit)

### Reproducible Demo

In main.js:
```
import Vue from 'vue'
import VueAnalytics from 'vue-analytics'
import App from '@/App.vue'

Vue.use(VueAnalytics, {
  id: process.env.GOOGLE_ANALYTICS_KEY
})

new Vue({
  render: h => h(App)
}).$mount('#app')
```

In App.vue:

```
<template>
  <span>test</span>
</template>

<script>
export default {
  mounted () {
    this.$ga.event({
      eventCategory: 'myCategory',
      eventAction: 'myAction',
      eventLabel: 'myLabel'
    })
  }
}
</script>
```

**Comment by MatteoGabriele** [comment]
Hi @i4ntch1k 
I've tested it and looks like you're right, event tho I already thought about it when I deployed a fix for that long time ago.
I will have a look again and let you know

Thanks for your feedback

**Comment by ajshortt** [comment]
Any movement on this? Having the same issue. If there was a method for checking that GA was mounted then you use that check before firing your event

**Comment by MatteoGabriele** [comment]
The fix has been published.
check vue-analytics@5.15.0
