### ISSUE TITLE
Different configs per id

### ISSUE THREAD

**Issue by phouri** [MatteoGabriele/vue-analytics#143]
I got into a situation where I have 2 google analytics ID, one is ours, and other is the client's that wants to run with his ClientID (not the Googla Analytics Id, but the client ID), I don't want to override ours, but change his config to be something else.

So far I see that it's only one config for all, is it possible to split configs per ID?

**Comment by MatteoGabriele** [comment]
Hi @phouri 
let me see if I understand: you want the same domain id to start tracking twice the same event but based on two different client id?

Something like this but automatically done by the plugin on every event?

```js
this.$ga.set('clientID', 'foo')
this.$ga.page('/home')
this.$ga.set('clientID', 'bar')
this.$ga.page('/home')
```

**Comment by phouri** [comment]
Nope, something a lot simpler, I have 2 domain ids (one reports to my GA, other to a client using my services GA). 

However, the configurations are a bit different (specifically in my case, the config.fields) I'd have gotten around most configurations by getting the correct tracker and setting the configuration but clientId is read only and can only be setup in creation time.

So an example configuration for me would be:
```js
Vue.use(VueAnalytics, {
  id: ['id1', 'id2'],
  fieldsPerId: {
    id1: {},
    id2: {clientId: 'foo'},
  }
}
```

**Comment by MatteoGabriele** [comment]
Ah ok, I see what you mean.

thanks for your feedback

**Comment by MatteoGabriele** [comment]
@phouri I actually still didn't think about how to handle this, but if you have already an idea I can have a look at you PR :)

thanks a lot for your time

**Comment by phouri** [comment]
Added the PR :) lmk if it's ok

**Comment by MatteoGabriele** [comment]
Thanks a lot for your time, I'll have a look next week when I'm back.

Cheers
