### ISSUE TITLE
dynamicly add extra ID

### ISSUE THREAD

**Issue by sweebee** [MatteoGabriele/vue-analytics#147]
I'm doing an API call and i get an analytics ID, how do I add it to the current ID? So it should add it besides the default one that is set in Vue.use().

**Comment by MatteoGabriele** [comment]
Could you a snippet of your current installation and how are u handling the call?
The `id` property can also be a promise that returns an array, so you could retrieve that second id from API and add it to an array with the first one.

**Comment by sweebee** [comment]
in my main.js i have

```
Vue.use(VueAnalytics, {
  id: 'UA-102xxxxxxx,
  router
});
```

this is the call:

```
this.axios.post('url', data).then((res) => {
         let id = res.data.analytics_id;
         // add it it to analytics script
       });
```

**Comment by MatteoGabriele** [comment]
You cannot add a new domain ID on the fly, needs to be done before everything starts so this is your only option:

```js
const ids = ['UA-102xxxxxxx']

Vue.use(VueAnalytics, {
  id: axios.post('url', data).then(response => {
    const id = response.data.analytics_id
    return ids.concat(id)
  })
})
```

**Comment by sweebee** [comment]
i get the following error:

```
Uncaught (in promise) TypeError: e.replace is not a function
    at s (vue-analytics.js:1)
    at vue-analytics.js:1
    at Array.forEach (<anonymous>)
    at k (vue-analytics.js:1)
    at vue-analytics.js:1
```

**Comment by MatteoGabriele** [comment]
Uh! I might have spotted a small bug then :) 
For make it work for now, you can just wrap it in a function

```js
const ids = ['UA-102xxxxxxx']

Vue.use(VueAnalytics, {
  id: () => {
    return axios.post('url', data).then(response => {
      const id = response.data.analytics_id
      return ids.concat(id)
    })
  }
})
```

**Comment by MatteoGabriele** [comment]
@sweebee if it's working I'll close this ticket, I've already opened another one for the little bug I saw

**Comment by sweebee** [comment]
Yes thanks.
