### ISSUE TITLE
Analytics only tracked when in debug mode

### ISSUE THREAD

**Issue by daniel-keller** [MatteoGabriele/vue-analytics#15]
I'm sure this is an issue with my implementation as I'm new to Analytics. 
I see the session in real time when I initialize vue-analytics in debug mode but without debug mode on I see nothing. At first I thought this was b/c I was on my local environment; however, running the code on my dev server produced the same results. I'm using Vue 2 and Vue Router 2

```
import Vue from 'vue'
import VueRouter from 'vue-router'
import VueAnalytics from 'vue-analytics'

// Initialize Vue Components here
...

// Initiailze router
Vue.use(VueRouter)

var router = new VueRouter({
  linkActiveClass: 'active',
  routes: [
    {path: '/', redirect: {name: 'search'}},
    {path: '/admin', component: AdminVue, name: 'admin'},
    {path: '/advancedsearch', component: AdvancedSearchVue, name: 'advanced'},
    {path: '/search', component: SearchVue, name: 'search',
        children: [{
            path: '/object/:perm_id',
            name: 'object',
            component: DetailOverlayVue
        }]
    }
  ]
})

// initialize analytics
Vue.use(VueAnalytics, {
  id: 'UA-XXXX-X',
  router: router,
  debug: {
    enabled: true,
    trace: false,
    sendHitTask: true
  }
})

// start application
var app = new Vue({
  el: '#app',
  router: router
})
```

**Comment by MatteoGabriele** [comment]
hi @daniel-keller the purpose of the debug it's actually to show to you what you're tracking: if you are not in debug mode, then the app is still tracking but it is not logging to your console.

when you put `debug.enabled` to `true` I am actually loading a specific library from Google Analytics which is slightly bigger in size, and allows you to see everything is going on.

Never use debug mode in production.

**Comment by MatteoGabriele** [comment]
If you want to read more you can click [here](https://developers.google.com/analytics/devguides/collection/analyticsjs/debugging) to the actual documentation of `analytics_debug.js`, but can also skip it!

Basically what you need to know is that

- you are always tracking by default
- if you enable debug you are actually seeing what you are tracking
- you can also see what you are tracking enabling debug, but you can also don't send anything to your domain if you are still developing in your machine: just set `sendHitTask` to `false`
- you can also choose if you want a more verbose output by enabling `trace` to `true`

**Comment by daniel-keller** [comment]
Thank you for quick response. I understand that debug mode will log in the console and I certainly don't want to us it in production. What I mean is if I turn debug mode on I can login to my google analytics account and see the active user in real time. However if I turn debug mode off I no longer see any real-time activity on the site.

**Comment by daniel-keller** [comment]
Hmm, well now its started working and I can't reproduce the error. Thank you again for your response.

**Comment by MatteoGabriele** [comment]
@daniel-keller No idea about the realtime data disappearing on debug false, to be honest: there's no API involved for realtime data on GA.

Let me know if you find any other issue.

thanks

**Comment by leighwilliams** [comment]
I think I've come across the original issue described here.

```
debug: {
  enabled: false,
  trace: false,
  sendHitTask: false,
},
```

Above is disabling `sendHitTask` even though `enabled` is set to false.

```
debug: {
  enabled: false,
  trace: false,
  sendHitTask: true,
},
```

This is required to make it work while keeping `debug` key present.

**Comment by MatteoGabriele** [comment]
This is the exact value of the default state of the debug object https://github.com/MatteoGabriele/vue-analytics/blob/master/src/config.js#L7-L11

`debug.enabled` is not referring to `sendHitTask` property or `trace`, but is referring to the actual debug mode.

so if you don't want to sendHitTask to your Analytics account during development, simply write

```js
Vue.use(VueAnalytics, {
  id: 'xxxxxxxxx',
  debug: {
    sendHitTask: false
  }
})
```
as described here in the source code, when that property is false, the value of sendHitTask is set to `null`
https://github.com/MatteoGabriele/vue-analytics/blob/master/src/init.js#L58-L60
