### ISSUE TITLE
Requires router to work properly

### ISSUE THREAD

**Issue by janswist** [MatteoGabriele/vue-analytics#150]
Issue is with readme file. I must have read an article that showed me that I have to use 'router' within VueAnalytics object to start tracking. Without it it's not working.

**Comment by MatteoGabriele** [comment]
You need to pass the instance of your routing ( vue-router ) only if you want to use the auto-tracking feature of the package, otherwise you can do it manually.

**Comment by janswist** [comment]
Yes, but it's not obvious. I thought it was running and 2 weeks went by and 0 hits on Google Analytics. That's why I created issue because it should work as stated in readme file.

**Comment by MatteoGabriele** [comment]
That's a list of features. If you go to the chapter dedicated to tracking it will be obvious that you need to pass the router.
If you stay only at that list that you are automatically opt-out from Google analytics service then.

Always read the guide before using a library and test before pushing in production.

**Comment by MatteoGabriele** [comment]
But thanks anyway for the feedback, I will make it more explicit
