### ISSUE TITLE
Can I replace the 'https://www.google-analytics.com/analytics.js' to custom url

### ISSUE THREAD

**Issue by xmsz** [MatteoGabriele/vue-analytics#153]
I can't load 'https://www.google-analytics.com/analytics.js' some times. Due to my country often block the Google Website.

So, Can I custom the google analytics load url.

**Comment by MatteoGabriele** [comment]
You can't do this right now, but it's an easy feature to add :)

**Comment by xmsz** [comment]
Tanks
