### ISSUE TITLE
v-ga on UI-Framework (etc. element-ui) not work

### ISSUE THREAD

**Issue by my9074** [MatteoGabriele/vue-analytics#154]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description

What are you reporting?

I use UI famework (etc. [element-ui](http://element-cn.eleme.io/1.4/#/zh-CN/component/button)).
and follow the steps of the document. but ```v-ga``` not work on like *el-button*、*el-input* component.

### Expected behavior

Tell us what you think should happen.

### Actual behavior

Google analytics can not collected Events

### Environment

Run this command in the project folder and fill in their results:

`npm ls vue-analytics`: 

Then, specify:

1. Operating system: mac os 
2. Browser and version: chrome 65+

### Reproducible Demo

Please take the time to create a new app that reproduces the issue or at least some code example

Demonstrable issues gets fixed faster.

xxx.vue
![image](https://user-images.githubusercontent.com/4555635/44387099-236ec580-a557-11e8-95dc-99ba1da3c6be.png)

main.js
![image](https://user-images.githubusercontent.com/4555635/44386892-7136fe00-a556-11e8-9d98-9ff51c5cce4b.png)

**Comment by MatteoGabriele** [comment]
Please, because it's an issue with a framework involved, take time to create the application on a repository and link it here.

Create a small app with vue-cli, add framework and plugin and re-create the issue

thanks for your time

**Comment by my9074** [comment]
@MatteoGabriele Can this DEMO reproduce the question？

**Comment by MatteoGabriele** [comment]
Sorry but I didn't have time yet. I'll ket you know asap

**Comment by MatteoGabriele** [comment]
I had a look and yeah it doesn't work with this `el-button` component.
I've also tried with a custom button component that I made on the fly and it worked.

I guess that it's more a ticket for the UI framework you're using, that for me: the binding doesn't work passing via their component.

**Comment by MatteoGabriele** [comment]
I'm sorry @my9074, but I don't understand.
