### ISSUE TITLE
Extracting clientId

### ISSUE THREAD

**Issue by avrelaun** [MatteoGabriele/vue-analytics#156]
I used the analytics.js library previously, and would like to replace it with vue-analytics to ship it directly with the vendors.

The only thing that is missing for completing the transition is being able to extract the clientId (cid) generated from the ga instance. Since parsing the cookies is considered a bad practice I used to access via the tracker like this:

```
	window.ga((tracker) => {
		cid = tracker.get('clientId');
	});
```

Is there a way to achieve this with Vue-analytics ?

**Comment by MatteoGabriele** [comment]
Hi @avrelaun 
is currently not possible but I could add this feature.
The only thing is that in this plugin is possible to manage more than one domain, so or it will return probably an object map or something like that

**Comment by avrelaun** [comment]
It would be great !
For now I guess I'll extract the value from the cookie...

**Comment by alangrainger** [comment]
Here's a couple of ways I'm currently doing this, until the package supports it:

`ga.getAll()[0].get('clientId');`

And if you have more than one property:

`function() {
  try {
    var trackers = ga.getAll();
    var i, len;
    for (i = 0, len = trackers.length; i < len; i += 1) {
      if (trackers[i].get('trackingId') === "ID-PROPERTY") {
        return trackers[i].get('clientId');
      }
    }
  } catch(e) {}  
  return 'false';
}`

**Comment by wdwatkins** [comment]
I'd just like to make another vote for this feature
