### ISSUE TITLE
Incomplete doc at Vuex part

### ISSUE THREAD

**Issue by Calvin-Huang** [MatteoGabriele/vue-analytics#158]
The README about Vuex part said there is an `event` function can be used to send the ga event.

```
// store.js
import Vue from 'vue'
import Vuex from 'vuex'
import { page } from 'vue-analytics'

Vue.use(Vuex)

export default new Vuex.Store({
  state: {
    counter: 0
  },
  actions: {
    increase ({ commit, state }) {
      commit('increase', state.counter + 1)
    }
  },
  mutations: {
    increase (state, payload) {
      state.counter = payload
      event('user-click', 'increase', 'counter', state.counter)
    }
  }
})
```

However, it will throw an undefined error at runtime since the `event` not exists. I inspected the current `vuex-middleware.js`, there is no implementation for `event` function. Is there any way to make the `event` works fine? Or we need to follow the old `meta` style to send the event via Vuex.

**Comment by MatteoGabriele** [comment]
hi @Calvin-Huang 
you probably need update your vue-analytics package.

After I'll release version 6, the vuex middleware will be removed, because now you can simply use the package API also importing its methods separately.

you can check the release here https://github.com/MatteoGabriele/vue-analytics/compare/v5.15.1...v5.16.0

**Comment by Calvin-Huang** [comment]
Thanks for the explanation.

I noticed the doc was updated, and it works fine now. Thanks again!
```
- import { page } from 'vue-analytics'
+ import { event } from 'vue-analytics'
```

**Comment by MatteoGabriele** [comment]
Yeah, it was a PR from a contributor that I thought was in master already, instead was in the develop branch :)
