### ISSUE TITLE
pageViewTemplate not getting called

### ISSUE THREAD

**Issue by devinrhode2** [MatteoGabriele/vue-analytics#160]
### Description

My app reloads, there's only one page, and the autoTracking.pageViewTemplate/pageviewTemplate hook is not getting called. 

### Expected behavior

I have a console.error statement inside this hook, and it should be getting logged to the console, but is not.

Here's my main.js with the code:
```js
import Vue from "vue";

import App from "./App";
import router from "./router";
import VModal from "vue-js-modal";
import VueAnalytics from "vue-analytics";

// Tried true and false for this:
const isProd = true;//process.env.NODE_ENV === "production";

Vue.config.productionTip = isProd;

// This works, nothing insane going on here:
console.error('test');

Vue.use(VueAnalytics, {
  id: "UA-31828297-1",
  router,
  autoTracking: {
    exception: true,
    screenview: true,
    // prependBase: false, // commented out just for testing
    pageViewTemplate (route) {
      console.error('pageViewTemplate route', route);
    },
    pageviewTemplate (route) {
      console.error('pageviewTemplate route', route);
    }
  },
  debug: {
    enabled: !isProd,
    sendHitTask: isProd
  }
});

Vue.use(VModal);

require("es6-object-assign/auto"); // for IE11 when use vue-js-modal

new Vue({
  el: "#app",
  data: {
    config: Vue.config
  },
  router,
  render: h => h(App)
});
```

### Actual behavior

I do see that some events get sent. Mostly everything else seems to be working just fine.

### Environment

```
➤ npm ls vue-analytics
my-app@1.0.0 /my/app/path
└── vue-analytics@5.16.0 
```

1. Operating system: macOS Sierra 10.12.6
2. Browser and version: Firefox 61.0.2 (also tested Chrome 68.0.3440.106 (Official Build) (64-bit))

### Screenshots
Chrome isProd = true:
![screen shot 2018-09-07 at 6 49 24 pm](https://user-images.githubusercontent.com/539816/45247696-2693e080-b2cf-11e8-9e04-72c6de492d25.png)

Firefox isProd = true:
![screen shot 2018-09-07 at 5 52 17 pm](https://user-images.githubusercontent.com/539816/45247712-488d6300-b2cf-11e8-900d-065dea0fa084.png)

Chrome isProd = false:
![screen shot 2018-09-07 at 7 11 48 pm](https://user-images.githubusercontent.com/539816/45248023-eeda6800-b2d1-11e8-8e8d-0d12812cdf6a.png)

Firefox isProd = false:
![screen shot 2018-09-07 at 7 11 40 pm](https://user-images.githubusercontent.com/539816/45248056-52fd2c00-b2d2-11e8-9f75-3fe4b0cf88bd.png)

### Reproducible Demo
Here's a .zip of an app that reproduces the issue... I just deleted a ton of code from our app and stubbed the Home and App components, which are used in the router/index.js file.
[broken-pageview-hook-demo.zip](https://github.com/MatteoGabriele/vue-analytics/files/2362932/broken-pageview-hook-demo.zip)

**Comment by devinrhode2** [comment]
edit: added .zip file of demo

**Comment by devinrhode2** [comment]
I tried using the router meta.analytics option and that didn't seem to work in FF:
```
export default new Router({
  routes: [
    {
      path: "/",
      name: "Home",
      component: Home,
      meta: {
        analytics: {
          pageviewTemplate (route) {
            console.error('hey');
            return {
              title: 'This is my custom title',
              page: route.path,
              location: 'www.mydomain.com'
            }
          }
        }
      }
    },
    {
      path: "/:orgId",
      name: "Room",
      component: Home,
      meta: {
        analytics: {
          pageviewTemplate (route) {
            console.error('hey');
            return {
              title: 'This is my custom title',
              page: route.path,
              location: 'www.mydomain.com'
            }
          }
        }
      }
    }
  ],
  mode: "history"
});
```

**Comment by MatteoGabriele** [comment]
it's `pageviewTemplate` not `pageViewTemplate` and also you have the `screenview` option turned on. The `pageviewTemplate` only works when using page tracking as the name suggests :)

**Comment by devinrhode2** [comment]
Ok cool. Thank you.

There is a reference to pageViewTemplate in the docs, which is why I tried
both pageviewTemplate and pageViewTemplate

**Comment by MatteoGabriele** [comment]
Could be a typo, can you link the lines here? Thanks a lot

**Comment by devinrhode2** [comment]
Best off searching the docs for case-sensitive "pageViewTemplate", maybe there's more than one?

Looks like removing screenview: true made the hooks in router/index.js fire, but not the ones in main.js.
