### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by stmegabit** [MatteoGabriele/vue-analytics#161]
Hello, thanks for your work. Could you add TypeScript support by adding [declaration file](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html)?

**Comment by MatteoGabriele** [comment]
Yeah definitely. I like it! 
I'll try this link you sent. Feel free to open a PR if you're more familiar with that

**Comment by jamiecarter7** [comment]
I used the code from this tutorial and it seems to work well, I did add 2 extra lines for the new disable and enable functions 

```typescript
import _Vue, { PluginFunction } from "vue";

declare class VueAnalytics {
  static install(Vue: typeof _Vue, options: any): void;
  analyticsMiddleware: any;
  onAnalyticsReady: any;
  event: any;
  ecommerce: any;
  set: any;
  page: any;
  query: any;
  screenview: any;
  time: any;
  require: any;
  exception: any;
  social: any;
  disable: any;
  enable: any;
}
export default VueAnalytics;

declare module "vue-analytics" {

}

declare module "vue/types/options" {
  interface ComponentOptions<V extends _Vue> {
    ga?: VueAnalytics;
  }
}

declare module "vue/types/vue" {
  interface Vue {
    $ga: VueAnalytics;
  }
}
```

**Comment by MatteoGabriele** [comment]
I was actually just now looking at it but I was wondering if it's enough to create a folder types and throwing this file in or I have to do something else

**Comment by bluelovers** [comment]
a lazy way is try rename all { .js => .ts }
and add this into `tsconfig.json`

```json
{
  "compilerOptions": {
    ...
    "declaration": true,
    ...
  }
```

then typescript will auto create `.d.ts` from your `.ts` file

---

and remember add follow code into `.npmignore`

```glob
*.ts
!*.d.ts
```

**Comment by nztomas** [comment]
@jamiecarter7 I followed your steps (and also steps from that Japanese page) but still can't access this.$ga in my components - any idea why?

**Comment by nztomas** [comment]
Okay found it - stupid vscode was complaining but the app was actually working fine. I just had to restart VSCode to reload *.d.ts

Thanks

**Comment by kukoo1** [comment]
any update on this ?

@MatteoGabriele Just create new file named index.d.ts in types/ directory. That's all.
User's typescript compiler will automatically detect *.d.ts in node_modules/${packgage} by default.

**Comment by johnjcamilleri** [comment]
Using the code above I was getting this error:

```
Invalid module name in augmentation. Module 'vue-analytics' resolves to an untyped module at '<PATH>/node_modules/vue-analytics/dist/vue-analytics.js', which cannot be augmented.
```

This version works for me (I don't really understand the details of why):

```ts
declare module 'vue-analytics' {
  import _Vue, { PluginFunction } from "vue";

  export default class VueAnalytics {
    static install(Vue: typeof _Vue, options: any): void;
    analyticsMiddleware: any;
    onAnalyticsReady: any;
    event: any;
    ecommerce: any;
    set: any;
    page: any;
    query: any;
    screenview: any;
    time: any;
    require: any;
    exception: any;
    social: any;
    disable: any;
    enable: any;
  }

  module "vue/types/options" {
    interface ComponentOptions<V extends _Vue> {
      ga?: VueAnalytics;
    }
  }

  module "vue/types/vue" {
    interface Vue {
      $ga: VueAnalytics;
    }
  }

}
```

Versions:
- typescript 3.4.5 
- vue 2.6.10
- vue-analytics 5.17.0

**Comment by edarioq** [comment]
If anyone needs it, with the recent update you can:

```
import VueAnalytics from 'vue-analytics';
```

Declare the variable:
```
ga = new VueAnalytics();
```

Then you can use it in your code:
```
this.ga.event(etc...);
```
