### ISSUE TITLE
window.ga is not a function

### ISSUE THREAD

**Issue by sebastian-raubach** [MatteoGabriele/vue-analytics#163]
### Description

vue-analytics causes a `window.ga is not a function` error. No tracking is taking place.

### Expected behavior

No error

### Actual behavior

Error

### Environment

Run this command in the project folder and fill in their results:

`-- vue-analytics@5.16.0`

Then, specify:

1. Operating system:
Windows 10
2. Browser and version:
Chrome 68.0.3440.106

### Reproducible Demo
```
import Vue from 'vue'
import Router from 'vue-router'

import HelloWorld from '@/components/HelloWorld'

import VueAnalytics from 'vue-analytics'

Vue.use(Router)

var router = new Router({
  routes: [
    {
      path: '/',
      name: 'home',
      component: HelloWorld
    }
  ]
})

Vue.use(VueAnalytics, {
  id: 'UA-XXXXXXX-X',
  router: router
})

export default router
```

**Comment by paolodina** [comment]
same here with ubuntu/chrome 69.0.3497.81 (Official Build) (64-bit)

**Comment by MatteoGabriele** [comment]
I'm sorry but I can't reproduce it. Please create a small app with essential settings and all the steps to reproduce the error described.

thanks for the feedback :)

**Comment by sebastian-raubach** [comment]
This repository should show the error:
https://github.com/sebastian-raubach/vue-ga-test

**Comment by MatteoGabriele** [comment]
@sebastian-raubach the project fails to build because of a missing static folder, but other than that, when I fix that issue, doesn't prompt me any errors about window.ga not defined.
Please double check this reproduction before sending it.

**Comment by sebastian-raubach** [comment]
@MatteoGabriele  I added the static folder. The I checked it out, ran `npm install`, then `npm run dev`, then checked the browser's web console (Chrome) and there is a `window.ga is not a function` error.

**Comment by MatteoGabriele** [comment]
I'm sorry but an error in the build is the only thing I see in my console.
I was wondering if you all have some analytics blocker or stuff like this, because I cannot reproduce this error.

<img width="1384" alt="screen shot 2018-09-18 at 8 55 51 am" src="https://user-images.githubusercontent.com/5337152/45669584-cac42580-bb20-11e8-881c-5507c6c45ad0.png">

**Comment by sebastian-raubach** [comment]
Yes, that was indeed the case. Sorry to bother you with this!

**Comment by MatteoGabriele** [comment]
No worries :)

**Comment by adrienbecker** [comment]
Hi guys,

I have same problem in dev and prod environment on Chrome 69 and Safari 12 but not on Firefox 61 and Safari 12 sometime.

You can check the test here http://vueanalytics.bkr.io

Test create with vuejs webpack template

```js
// The Vue build version to load with the `import` command
// (runtime-only or standalone) has been set in webpack.base.conf with an alias.
import Vue from 'vue'
import VueAnalytics from 'vue-analytics'
import App from './App'
import router from './router'

Vue.config.productionTip = false

Vue.use(VueAnalytics, {
  id: 'UA-126199024-2',
  router,
  debug: {
    enable: true,
    sendHitTask: true
  }
})

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  components: { App },
  template: '<App/>'
})
```

It's a real issue or just a crazy random f**k bug !!!

Thanks all :)

**Comment by adrienbecker** [comment]
Great ! 
The default value of `disable` option is `false`, so any script is loaded…

**Comment by MatteoGabriele** [comment]
Hi @adrienbecker 
I'm not really following :)
Do you still have a problem and btw yes the default value is false because by default I want the plug-in to work

**Comment by adrienbecker** [comment]
Hi @MatteoGabriele,
Yes I search anywhere since yesterday but it's good ! 
Thanks your plugins is very pratique 👍 :) 
Best,

**Comment by MatteoGabriele** [comment]
@adrienbecker thanks a lot :)
cheers

**Comment by Eduruiz** [comment]
[http://vueanalytics.bkr.io](http://vueanalytics.bkr.io) gives me the same error I'm having in my project, when using disconnect. `window.ga is not a function`.

**Comment by adrienbecker** [comment]
@Eduruiz Do you use Chrome ?

**Comment by MatteoGabriele** [comment]
@Eduruiz I'm 99% sure you have an ADs or Analytics blocker.
Please check first on a private browser :)

thanks

**Comment by adrienbecker** [comment]
Right ! Ghostery extension for me, ADs don't disrupt ga script

**Comment by Eduruiz** [comment]
@MatteoGabriele it is, disconnect or ghostery block google analytics scripts, but I think we should test if window.ga exists before calling it to avoid trowing errors when users have this kind of blocking scripts. Google Analytics "per se" does it.

**Comment by MatteoGabriele** [comment]
@Eduruiz Google as way more control on his product, I cannot throw an error if `window.ga` is undefined because it will be so a lot of time, especially in SSR applications and during the script loading state.

I'll see what I can find, but probably this is just the way it is.

Hopefully this ticket will provide enough information to the developer to not freak out if it doesn't work.

**Comment by nikugogoi** [comment]
hi @MatteoGabriele , thanks for the really cool plugin.... 
So here is a case when google-analytics script doesnt load

**main.js**
```
...
Vue.use(VueAnalytics, {
  id: 'UA-XXX-X',
  checkDuplicatedScript: true,
})
...
```

**index.html**
```
...
<div id="app"></div>
<script src="//someother.analytics.com/analytics" async defer></script>
...
```
In such a scenario the google analytics script doesnt load due to `checkDuplicatedScript` flag
it can be observed in slow network... so turn down the network speed if working in local

**Comment by MatteoGabriele** [comment]
Thanks man! :)
Can u be more specific, I don't think I understand the problem
