### ISSUE TITLE
Use google ads AW-XXXXXXXXX

### ISSUE THREAD

**Issue by Neptius** [MatteoGabriele/vue-analytics#165]
Hi, I want to integrate the id ads of google (AW-XXXXXXXXX) on my client web site, here is the code put at my disposal.
```
<!-- Global site tag (gtag.js) - AdWords: XXXXXXXXX -->
<script async src="https://www.googletagmanager.com/gtag/js?id=AW-XXXXXXXXX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'AW-XXXXXXXXX');
</script>
```
It looks like the default code of UA but he doesn't work. Can I use it with vue-analytics? Is there an alternative?

Sorry for my bad english.

**Comment by MatteoGabriele** [comment]
I'm not sure about Google integrations betweens Analytics and Tag Manager, I'm sorry, but just looking at this code, this just looks like the new version of Google gtags, so if you need gtags support this plugin doesn't have it yet.

If you need to track your pages, event and so on with google analytics or gtags, then you can just use this plugin with no addition to your HTML and pass your domain ID as the plugin parameter.

let me know if does make sense to you

thanks

**Comment by Neptius** [comment]
Thank you for your reply.
If I understood correctly, I just have to integrate the code, which I posted above, on my website with the ID (AW -...) and everything will work?

**Comment by MatteoGabriele** [comment]
if you have to track your website with analytics, you don't have to add all that code, but just add the ID in the plugin options following the instructions in the readme.
the plugin doesn't support the gtag script, so depends what you have to do :)

**Comment by Neptius** [comment]
I don't know if I can trust this chrome extension because I have no way to see if everything goes well

**Comment by MatteoGabriele** [comment]
No, like this is wrong: you are already tracking with Analytics using the UA-xxxx-x code so that's fine, don't need to add another ID there.

For what concerns google tag manager I have no clue cause I actually never worked with it.

Sorry man!
