### ISSUE TITLE
Full url question

### ISSUE THREAD

**Issue by tstrumfels** [MatteoGabriele/vue-analytics#168]
Not a bug - essentially using this library to replicate google tag manager functionality - purpose is to capture the page being accessed by each logged in user, where my google id and userId values are captured in the global scope (window.ga and window.userId), and setting my custom user_id field.

Vue.use(VueAnalytics, {
    id: window.ga,
    fields: {
        userId: window.userId,
    },
    set: [
        { field: 'user_id', value: window.userId }
    ],
    router,
    autoTracking: {
        pageviewOnLoad: false
    }
});

then in the component, capturing the event

       this.$ga.event('userId.dimension', {
            'userId': window.userId
        });

While this does in fact work, I am able to capture the route path, however when i pull the data down it doesnt account for the full url from IIS (in the case of a virtual directory).  So if my route is component1, the data pulled down is mydomain.com/component1 (instead of mydomain.com/appname/component1).

Environment: VS 2017, vue spa with webpack and typescript.

Any pointers are much appreciated.

**Comment by MatteoGabriele** [comment]
hi @tstrumfels 
thanks for your feedback. Unfortunately I don't know what could cause this.
Did u check the data sent locally? enable the debug option and check what it is sending to have a better insight.

**Comment by tstrumfels** [comment]
enabled debug - from what I can tell, in an MVC5 multi-page app, the dimensions of interest that I capture are hostname and pagePath - in the multipage app (not using your library), it includes the appname in the pagePath dimension, so /appname/page1.  However, from your lib, it only grabs /page1.

So then, in the console, behind the scenes it shows: Running command: ga("set", "page", "/page1") and ga("send", "pageview", "/page1").

**Comment by tstrumfels** [comment]
Digging around (excellent work, btw!), wondering if there's additional config to pass in, maybe pageViewTemplate?

**Comment by MatteoGabriele** [comment]
Yes probably because I use the route path. You could use the pageviewTemplate and create your own object. Let me know if works for you.

Thanks :)

**Comment by tstrumfels** [comment]
Matteo,
pageviewTemplate worked like a charm.  Was able to extract applicationName from window.location.pathname, then return as such:

            return {
                page: applicationName + route.path,
                title: document.title,
                location: window.location.href
            }

Thanks for pointing me to the debug api, that was very helpful.  Thanks again for your work

**Comment by MatteoGabriele** [comment]
Nice to hear that! :)
Cheers
