### ISSUE TITLE
Does not apply in chrome-extension

### ISSUE THREAD

**Issue by gksmf5310** [MatteoGabriele/vue-analytics#177]
Hello, I want use to analytics.js to my chrome-extension.
But it seems that it is not applied better than I thought.

The following is part of the file that initializes vue.
```
import Vue from 'vue'
import VueRouter from 'vue-router'
import VueAnalytics from 'vue-analytics'

...

Vue.use(VueRouter);

...

const router = new VueRouter({routes});

Vue.use(VueAnalytics, {
	id: 'UA-XXXXX-X',
	router
})

```

And in the vue script we entered the event as below.

`this.$ga.event('category', 'action', 'label', 123)`

There was no compile error. However, on Google Analytics pages, data is not being played.

Although guide seem to be on the Web, plugin chrome worries whether you need an option separately.
And github is the first question I ask, but if you have any inaccuracies, I ask for your understanding.

**Comment by MatteoGabriele** [comment]
Turn on the debug mode in the plugin, which uses analytics-debug.jsand if your data is displayed there, then it's correct on my side and I have no control over it

Thanks for your feedback tho :)

**Comment by gksmf5310** [comment]
@MatteoGabriele There was the same issue before. https://github.com/MatteoGabriele/vue-analytics/issues/50

`this. $ ga.set ('checkProtocolTask', null);`
I put the code above and solved the problem.

So, is there an option to put that code in the process of initializing VueAnalytics?

```
Vue.use(VueAnalytics, {
	id: 'UA-000000-0',
	checkProtocolTask : null // Can I put it like this?
})
```

**Comment by MatteoGabriele** [comment]
Yes, u can use this option here https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/set.md#set-multiple-fields-before-first-hit

**Comment by gksmf5310** [comment]
Thanks to you, the problem has been solved. Thank you very much :)

**Comment by MatteoGabriele** [comment]
It's a pleasure :)

**Comment by axe-me** [comment]
for 5.x
```js
  Vue.use(VueAnalytics, {
    id: '',
    fields: {
      cookieDomain: "none"
    },
    set: [{ field: "checkProtocolTask", value: null }]
  });
```
