### ISSUE TITLE
How to set userId?

### ISSUE THREAD

**Issue by codeofsumit** [MatteoGabriele/vue-analytics#178]
I'm having trouble setting the userId.

In my `main.js` I have this:

```js
Vue.use(VueAnalytics, {
  id: `${process.env.VUE_APP_GA}`,
  router,
});

firebase.auth().onAuthStateChanged(user => {
  if (user) {
    // TODO: set userId in Google Analytics

    store.dispatch('user/LOGIN', user);
  }
});
```

I tried setting the userId from the `LOGIN` action in vuex but I'm getting an error after using the imported `set` function from `vue-analytics`. But I still don't know how to do it from `main.js`.

I considered "installing" VueAnalytics *after* I have the userId but that would mean the plugin is installed multiple times if a user logs in and out so I'm just trying to set the Id. But how can I do it?

**Comment by codeofsumit** [comment]
Ok I found this: `Vue.$ga.set('userId', user.uid);` - is that the preferably way of using it in Javascript files like `main.js`?

**Comment by MatteoGabriele** [comment]
Yes. You can also use the set array in the plugin setup, it u prefer, but is not possible to add a promise so it needs to be synchronous.

User id can be set at any time

Always look at the documentation first :)

**Comment by codeofsumit** [comment]
@MatteoGabriele Of course! I couldn't find it in the docs - I searched the issues for `userId`, that's when I found this. On which page is this documented? I looked at

* Get Started
* How to load
* v-ga
* Set
* vuex

**Comment by MatteoGabriele** [comment]
The set one was probably the right one for you
