### ISSUE TITLE
ready () not firing

### ISSUE THREAD

**Issue by ThomasKientz** [MatteoGabriele/vue-analytics#179]
The ready hook is never fired :

```
Vue.use(VueAnalytics, {
  id: "UA-XXX",
  ready() {
    return console.log("READY"); // never printed
  }
});
```

Analytics are working fine (receiving hits, and logs with debug mode).

Any ideas ?

**Comment by MatteoGabriele** [comment]
yep, you are right!
In a refactor I did I apparently forgot to add it back and i wasn't tested.

sorry for that

I'll add it back asap

cheers!

**Comment by ThomasKientz** [comment]
@MatteoGabriele Hi mate, just to let u know that I am waiting for this one ;)

**Comment by MatteoGabriele** [comment]
I'll do it right away. Didn't have time these days, sorry

**Comment by MatteoGabriele** [comment]
never mind! I have some weird issues in my machine and node is not working... very nice when you want to do a quick fix ahahahhaha

i'll check tomorrow hopefully
