### ISSUE TITLE
Auto tracking not working correctly

### ISSUE THREAD

**Issue by sachaw** [MatteoGabriele/vue-analytics#180]
After injecting directly into my router for auto tracking, google analytics reports all page hits as whatever the app was loaded on, independent of whatever route the user moves to. i.e:
user loads app at `/`
user navigates to `/about`
google analytics gets 2 hits for `/`
the same behavior can be observed for any route.

here is a sample of code that replicates the aforementioned issue:
https://pastebin.com/9RceTENL

**Comment by MatteoGabriele** [comment]
Hi @sachaw I'll try to replicate this asap.
Possible issue could be the fact that you're loading components asynchronously, but it shouldn't be the case.

thanks for the feedback

**Comment by MatteoGabriele** [comment]
I'll close this one for inactivity, but please open it again when you have a repository with a  reproduction ready

**Comment by rajeshwarpatlolla** [comment]
I am also facing the same issue. Auto tracking is not working. But if i add `this.$ga.page('/login');` manually, then it is working.

**Comment by rajeshwarpatlolla** [comment]
I too had the same issue. The solution is we need to pass the router instance to vue analytics to work with automatic page tracking.

<img width="1060" alt="Screenshot 2020-07-26 at 1 21 26 AM" src="https://user-images.githubusercontent.com/9896335/88465165-64f41200-cede-11ea-824a-7f8080630501.png">
