### ISSUE TITLE
How to find the field `exception` and `field` in the analytics ?

### ISSUE THREAD

**Issue by zhougonglai** [MatteoGabriele/vue-analytics#182]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description

I have 2 fields although records but have been unable to find ! `exception` and `field`

### Expected behavior

Should find the corresponding record in analytics!

### Actual behavior

Can find only ` time ` and `event`

### Environment

Run this command in the project folder and fill in their results:

`npm ls vue-analytics`: "vue-analytics": "^5.16.0"

Then, specify:

1. Operating system:  Mac OS 10.14.1
2. Browser and version: Chrome. 62

### Reproducible Demo

Please take the time to create a new app that reproduces the issue or at least some code example

Demonstrable issues gets fixed faster.
`fields`:
```javascript
Vue.use(VueAnalytics, {
  id: 'UA-XXX',
  checkDuplicatedScript: true,
  router,
  autoTracking: {
    exception: true
  },
  // 字段跟踪
  fields: {
    version: 'v1.2.4'
  },
```
`exception`:
```javascript
}).catch(err => {
    this.$ga.exception(err.message || err)
})
```

**Comment by MatteoGabriele** [comment]
hi @zhougonglai 
I'm sorry but I don't understand what's the problem

**Comment by zhougonglai** [comment]
> hi @zhougonglai
> I'm sorry but I don't understand what's the problem

I realized that some of the API does not seem to have any practical effect. like `field` and `exception`

**Comment by MatteoGabriele** [comment]
This is the link to the available fields you can use: you cannot create your own

https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference
