### ISSUE TITLE
Ecommerce gives error says Plugin "ec" does not have method "addItem".

### ISSUE THREAD

**Issue by shawhu** [MatteoGabriele/vue-analytics#184]
### Description
"ec" does not have method "addItem".

### Expected behavior
not giving error
and the ecommerce message sent

### Actual behavior

Tell us what actually happens.

### Environment

Run this command in the project folder and fill in their results:

`npm ls vue-analytics`: 
npm ls vue-analytics
gatest@1.0.0 /Users/shawhu/Projects/elephant/gatest
└── vue-analytics@5.16.1
Then, specify:

1. Operating system:
macos 10.13.6
2. Browser and version:
google chrome 70.0.3538xxx

### Reproducible Demo

    vue init webpack gatest

in main.js we have this

    Vue.use(VueAnalytics, {
        id: 'UA-xxxx-1',
        disableScriptLoader: true, 
        router, 
        autoTracking: {
        pageviewOnLoad: false
    },
     debug: {
     enabled: true
    },
    ecommerce: {
    enabled: true,
    enhanced: true
     }
     })

in one of the component page we have

      this.$ga.set("userId", "_iWydJAZTVEdF3Dys");   // <-this line works fine!
      //this doesn't
      this.$ga.ecommerce.addItem({
          id: '1234',                     // Transaction ID. Required.
          name: 'Fluffy Pink Bunnies',    // Product name. Required.
          sku: 'DD23444',                 // SKU/code.
          category: 'Party Toys',         // Category or variation.
          price: '11.99',                 // Unit price.
          quantity: '1'                   // Quantity.
        })

the error is like this

![screen shot 2018-12-12 at 3 37 48 pm](https://user-images.githubusercontent.com/1240808/49854028-ef7c2080-fe23-11e8-8efe-3902bb9523c0.jpg)

**Comment by MatteoGabriele** [comment]
That's strange, didn't touch that feature for a while. Thanks for the feedback, I'll have a look asap

Cheers

**Comment by shawhu** [comment]
trying to upload a zipped proj for testing
[gatest.zip](https://github.com/MatteoGabriele/vue-analytics/files/2670890/gatest.zip)

**Comment by shawhu** [comment]
> That's strange, didn't touch that feature for a while. Thanks for the feedback, I'll have a look asap
> 
> Cheers

Many thanks!

**Comment by jakubjanuzik** [comment]
Hey, I do have the same issue in a project I participate with

apparently this line is not called:
`ga('require', 'ecommerce')`

After I've done such a thing in a debugger, it works just fine.

More info https://developers.google.com/analytics/devguides/collection/analyticsjs/ecommerce#loadit

**Comment by jakubjanuzik** [comment]
@MatteoGabriele 
Removing `enhanced: true` helps, but then you probably won't have access to the enhanced API.

**Comment by shawhu** [comment]
better than nothing, thanks @jakubjanuzik

**Comment by MatteoGabriele** [comment]
Thanks for the workaround! Unfortunately I'm out of town and without laptop so you have to hold you breath for a couple more weeks.

Cheers!

**Comment by mnording** [comment]
@MatteoGabriele  have you had any time to investigate this?
