### ISSUE TITLE
GA Lite

### ISSUE THREAD

**Issue by derevandal** [MatteoGabriele/vue-analytics#185]
Hi, is there a way to use [ga-lite](https://github.com/jehna/ga-lite) instead of official?
Even changing `customResourceURL` to my local `ga-lite`'s script, doesn't work because `ga-lite` uses `galite()` function instead of `ga()` function.

**Comment by MatteoGabriele** [comment]
No, I'm sorry but this is not possible. I'm always using ga library and also would an update that at this point I'm not going to do because I'm working on moving the project from the analytics.js library to gtag.js

thanks
