### ISSUE TITLE
Does this.$ga.enable() fire a pageview?

### ISSUE THREAD

**Issue by jamiecarter7** [MatteoGabriele/vue-analytics#187]
So this is a question, not a bug report.

I've been playing with the new GDPR settings on my website, and I just want to confirm, that up until the accept button is pressed on my GDPR notice, and `this.$ga.enable()` is run. The app does not collect any data?

```javascript
Vue.use(VueAnalytics, {
  id: 'UA-XXX-X',
  router,
  checkDuplicatedScript: true,
  debug: {
     sendHitTask: process.env.NODE_ENV === 'production'
  },
  disabled: true
})
```

Also can I confirm that on `this.$ga.enable()` being run the plugin does not send a pageview for the page currently being browsed? 

If not, then I will add a custom pageview event on the user accepting the GDPR and just after running the enable() function.

Thanks!

**Comment by MatteoGabriele** [comment]
Confirmed. When `disabled` is true by default, nothing is collected.
When you re-enable it, nothing happens until the next action. 
If you would like to trigger the current page the user is in when he accepts the privacy policy, then you need to trigger that yourself.

hope it's all clear

Cheers :)
