### ISSUE TITLE
2 ids in same page

### ISSUE THREAD

**Issue by emersoncoder** [MatteoGabriele/vue-analytics#19]
How I do 2 google analytics in same page ?

Thanks in advanced

**Comment by MatteoGabriele** [comment]
You can't! Usually an ID is per domain, so I didn't find that necessary to implement.

What's the use case? Tracking the same events and pages but for 2 different domains?

**Comment by emersoncoder** [comment]
I have an e-commerce that creates e-commerce pages, and on the pages that customers use, they put their ID, and I put mine too, so it gets 2 ID tracking the page.

**Comment by emersoncoder** [comment]
I use u code in this way 

const ecommerce1 = require('vue-analytics');
const ecommerce2 = require('vue-analytics');

then I do 2 calls with diferent analytics IDS

**Comment by MatteoGabriele** [comment]
If you need to track the same events with multiple domain IDs I need to make a change in my code, but it's possible

**Comment by MatteoGabriele** [comment]
feature added in v3.0.0

**Comment by MatteoGabriele** [comment]
@emersoncoder just pass an array of strings instead of one string and you're good to go.

```js
Vue.use(VueAnalytics, {
  id: ['UA-XXX-X', 'UA-ZZZ-Z']
})
```
