### ISSUE TITLE
vue-analytics always reports no page hits on google analytics

### ISSUE THREAD

**Issue by QuantumInformation** [MatteoGabriele/vue-analytics#190]
I have issue with vue-analytics

### Description

I have this site in GA 

![image](https://user-images.githubusercontent.com/216566/51323313-18698400-1a68-11e9-9a27-c086996a1778.png)

and use it like this

```Vue.use(VueAnalytics, {
  id: [ 'UA-3001283-11' ], router,
  debug: {
    sendHitTask: false
  }
})
```
But I never see any hits, the live deployment is here:

http://quantumjs.com

### Expected behavior

page tracking

### Actual behavior

I expect to see page views, not nothing like this:

![image](https://user-images.githubusercontent.com/216566/51323335-2d461780-1a68-11e9-9772-09cb3d386a53.png)

### Environment

Run this command in the project folder and fill in their results:

`npm ls vue-analytics`: 

➜  quantumvue git:(master) ✗ npm ls vue-analytics
quantumjs2@0.1.0 /Users/nikos/WebstormProjects/quantumvue
└── vue-analytics@5.16.1 

Then, specify:

1. Operating system: Mac os High seirra

### Reproducible Demo

Please take the time to create a new app that reproduces the issue or at least some code example

Demonstrable issues gets fixed faster.

**Comment by Dadibom** [comment]
You told it to not send the hit
`sendHitTask: false`
Remove the line or set it to true to send the event

**Comment by QuantumInformation** [comment]
I thought that was just to disable local hosting hits?

**Comment by Dadibom** [comment]
That's what it was implemented for. Set `sendHitTask: false` *in development* to avoid sending hits.

**Comment by Dadibom** [comment]
It won't check your `window.location.host` for you

**Comment by QuantumInformation** [comment]
That would be a nice feature
-- 

Kind regards

Nikos Katsikanis

**Comment by QuantumInformation** [comment]
I done this thx!

    sendHitTask: window.location.hostname === "localhost" ? false : true
