### ISSUE TITLE
Enhanced analytics not being tracked when using vue-router

### ISSUE THREAD

**Issue by jahvi** [MatteoGabriele/vue-analytics#192]
### Description

Enhanced Ecommerce events are not being reported to GA when using vue-router, looks like the problem is the order in which events are being ran.

Right now using vue-router and vue-analytics on their own works fine, it will automatically trigger the `pageview` event when router change, however for enhanced ecommerce GA expects the `pageview` event to run **last**, after the ecommerce functions like `addProduct`, `setAction`, etc are called.

This might not be a problem when using vue-analytics manually without the router as you have more control over when to call each function.

I can call `this.$ga.page()` manually after placing the transaction but that will track the pageviews twice, is there a way around this?

### Expected behavior

Enhanced Ecommerce data should be passed to GA.

### Actual behavior

Enhanced Ecommerce data is not being passed to GA.

### Environment

1. Operating system:
All OSs.

2. Browser and version:
All browsers.

### Reproducible Demo

https://codesandbox.io/s/n51jyxyr2j

Check the console when clicking the links, pageviews are tracked correctly.

Check the console when clicking "Add item", it triggers the right events but because `pageview` has already ran then it doesn't get reported.

**Comment by MatteoGabriele** [comment]
Sorry! I didn't see this ticket before.

I will have a look asap. Let me know if you still have this problem @jahvi 
Sorry again for the long wait

**Comment by leolux** [comment]
Manual tracking with `this.$ga.page()` leads to the following message in Google Tag Assistant:
`Same web property ID is tracked twice.`

What `page` value should one pass for SPA applications? If the real URL is like `https://mysite.com/#/about` should the manual tracking work with this code?
```
 this.$ga.page({  
  page: '/#/about',
  title: 'About',
  location: window.location.href
})
```

**Comment by MatteoGabriele** [comment]
I'm afraid you need to skip adding router as an option and go full manual when tracking your page views. There's no way I can detect when you finish firing a specific type of event: it is something you need to do yourself because you have control on it

**Comment by leolux** [comment]
Alright, thanks!
Manual tracking works well.
