### ISSUE TITLE
Handle outbound links in <router-link>

### ISSUE THREAD

**Issue by rominf** [MatteoGabriele/vue-analytics#193]
I propose to make it possible to send outbound links to Google Analytics. For example, I put:
```html
<router-link to="https://google.com/"/>
```
When the user clicks to this link, the browser opens http://localhost:8081/#/https://google.com/, router understands that this is the external link, sends an event to Google Analytics and redirects to the https://google.com/.

I really need this feature and I don't know how to implement correct outbound links opening events sending another way so that it worked even if the user opens links in a new tab via a context menu.

**Comment by rominf** [comment]
Related: https://github.com/vuejs/vue/issues/9378, https://github.com/vuejs/vue-router/issues/1280

**Comment by rominf** [comment]
I implemented what I wanted. If someone is interested, I can extract the code. But anyway, it's better to implement this in the plugin.

**Comment by MatteoGabriele** [comment]
can't you just make a component out of it just for you outbound clicks and that one automatically checks fires the google event and redirect to the link?

**Comment by frankoostrum** [comment]
@rominf I'm running into the same issue. Care to share your solution?

**Comment by rominf** [comment]
@frankoostrum, I can share the solution at weekend.

**Comment by rominf** [comment]
@frankoostrum here is the solution I use right now:

1. Initialize VueAnalytics as described in the documentation.
2. Extend `Vue.prototype`:
```javascript
  Vue.prototype.trackOutbound = function(this: Vue, url: string) {
    if (this.$ga.q) {
      // Google Analytics is blocked
      window.location.replace(url);
    } else {
      this.$ga.query('send', 'event', 'outbound', 'click', url, {
        transport: 'beacon',
        hitCallback() {
          window.location.replace(url);
        },
      });
    }
  };
```
3. Add `Redirect.vue` page template. Put anything you want inside, but probably you want just add this function:
```javascript
beforeRouteEnter(to, from, next) {
    const url = to.path.slice(1);
    next(vm => vm.trackOutbound(url));
}
```
4. Adjust `routes.js`:
```javascript
const routes = [
...
  {
    path: '/(.*)\://*',
    component: () => import('pages/Redirect.vue')
  }
];
```
5. Use `<router-link>` like this:
```html
<router-link to="https://google.com/"/>
```

That's it. @frankoostrum, looking for your feedback.

**Comment by frankoostrum** [comment]
@rominf Thank you for this. Works like a charm. 

As for the feedback, maybe you can change the `Vue.prototype` extension to regular JS to make it useful for more people. Also the `router-link` example should have some innerHtml.

**Comment by rominf** [comment]
@frankoostrum, thank you for feedback. I made a fix.

**Comment by frankoostrum** [comment]
@rominf One downside though is that now outbound links show up as both events and pages (since you direct to http://www.example.com/#/https://www.google.com which ga registers as page.

**Comment by rominf** [comment]
Thank you for noticing. Do you have a workaround?
