### ISSUE TITLE
Less sessions than new users

### ISSUE THREAD

**Issue by himberjack** [MatteoGabriele/vue-analytics#194]
### Description

In GA, we see sessions/users ~0.5 but we barely have returning users.
Seems like something is wrong as only 1 sessions per 2 users is being counted.
We ran the debug tool of GA and it looks fine: ga('set', xxxx) and then ga('pageview', xxxx).
We are not sure why this happens,

### Expected behavior

We expect to be around 1 sessions per user ratio

### Actual behavior

We have significantly less sessions than new users.

### Environment
vue-analytics@^5.16.0

**Comment by MatteoGabriele** [comment]
I am sorry but if events are fired and in the correct order then the plug-in is working. Everything else is not in my control and I don't know how to help you, tbh.

This is just a wrapper for Google analytics, not the actually Google analytics library :)

**Comment by himberjack** [comment]
Thanks @MatteoGabriele however this is not quite true. The GA plugin fires ga.create on every page load on a non-SPA, this is probably creates the session start event. Here, when we move around routes, we only have set(page) and send(pageview) but no create event

**Comment by MatteoGabriele** [comment]
I'm doing what's written in the guide
https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications

If you find some mistakes, you're more than welcome to let me know :)

Thanks
