### ISSUE TITLE
GA ecommerce command firing order of ecommerce:addTranscation and ecommerce:send

### ISSUE THREAD

**Issue by zisuzon** [MatteoGabriele/vue-analytics#198]
### Description

I've placed ecommerce vue-analytics code on mounted hook with some business logic so that whenever the thank you page load, it will send report to GA. But the *ecommerce:addTranscation* command is firing after the *ecommerce:send* command on page reload (The thank you page after the payment done). As a result, it's not submitting any report to GA. (I found the command firing order enabling the debug mode)

### Expected behavior

*ecommerce:send* should fire after *ecommerce:addTranscation* on page reload.

### Actual behavior

*ecommerce:send* fires before *ecommerce:addTranscation* on page reload.

### Environment

1. Operating system: Ubuntu 18.04 (64 bit)
2. Browser and version: Chromium 71.0.3578.98 

### Reproducible Demo
```
mounted () {
      if (
        BUSINESS_LOGICS
        ) {
        this.$ga.ecommerce.addTransaction({
          id: XXX,
          affiliation: XXX
          revenue: XXX
          shipping: XXX
        })
        
        // this one is firing before this.$ga.ecommerce.addTransaction
        this.this.$ga.ecommerce.send()
      }
    },
```

**Comment by MatteoGabriele** [comment]
there's a typo in your script `this.this.$ga.ecommerce.send()` with a double this
also it's not really possible that the plugin decides which one to fire, if you fire one first and the other one second, that will be the flow.

provide an easy reproduction if you really are experiencing this

**Comment by MatteoGabriele** [comment]
closed due to inactivity, please open it again in case of a reproduction
