### ISSUE TITLE
Displaying google analytics in component

### ISSUE THREAD

**Issue by IniZio** [MatteoGabriele/vue-analytics#2]
Is it possible to retrieve the google analyticis like page viewcount from the components?Also awesome to see this plugin as I have been searching for similar function for Vue :+1:

**Comment by MatteoGabriele** [comment]
can you be more specific,  I don't think I understand what you mean.  you would like to know how many pages a specific component has tracked? or it's a Google analytics api feature?

**Comment by MatteoGabriele** [comment]
closed due to inactivity

**Comment by Yusadolat** [comment]
Hi @MatteoGabriele I think the point he's trying to make is to have the Analytics report display on a component. Getting the report from google analytics and display it on a vue component.

**Comment by Yusadolat** [comment]
Is there a way to g around that @MatteoGabriele

**Comment by MatteoGabriele** [comment]
The main purpose of this component is to send data, not displaying it.
It would be out of its scope

Thanks for the suggestion tho

**Comment by Yusadolat** [comment]
Thanks for the reply @MatteoGabriele. Is there a way to go about this?
