### ISSUE TITLE
Don't send data on development environment

### ISSUE THREAD

**Issue by jonorozcoc** [MatteoGabriele/vue-analytics#202]
In order to keep Google Analytics production data as clean as posible the library has to detect the environment where is running. There are many ways to do that.

The most accurate way is using hot-reload window variable that is not present in production build.

If you want to test library usage, it could be added an option called "test" (Boolean) if true it bypass environment detection.

I can send a PR if needed

**Comment by shanestillwell** [comment]
@jonorozcoc why not just remove the Google Analytics tracking id in development? It should be an environment variable anyway.

```
// GA
if (process.env.GA_TRACKING_ID) {
  Vue.use(VueAnalytics, {
    id: process.env.GA_TRACKING_ID,
    router,
  })
}
```

**Comment by MatteoGabriele** [comment]
There's already a way of turning on and off data sending: just using the debug property `sendHitTask`

There is literally a link in the Readme called "Turn off during development"

https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/turn-off-development.md
