### ISSUE TITLE
beforeRouteEnter with delay causes duplicate page views

### ISSUE THREAD

**Issue by Dadibom** [MatteoGabriele/vue-analytics#204]
### Description

When using routes with beforeRouteEnter and a delay before next is called (for example the api call necessary to populate the page), there will be an initial page view tracked as the url `/`

This only happens on the initial load of the page

### Expected behavior

Only the second (correct) page event should be sent

### Actual behavior

two events are sent, and the first has the wrong url

### Reproducible Demo

https://codesandbox.io/s/r0ynjkm7pn

Go to /foo and reload the page. two events are tracked. this does not happen on /bar which does not have the beforeRouteEnter hook

**Comment by lluisltk** [comment]
We run into the same problem where we were randomly seeing initial `/` events for users landing on non-home pages.

It seems like at bootstrap time for _pageviewOnLoad_ , the code is often obtaining the `router.currentRoute` set to `/` on a race condition before the Vue Router it is _ready_.

We are evaluating the following fix in the `src/lib/page.js:83` file where we added `&& router.history.ready`:
```javascript
if (autoTracking.pageviewOnLoad && router.history.ready) {
    trackRoute(router.currentRoute)
  }
```

**Comment by lluisltk** [comment]
@MatteoGabriele , @Dadibom , we have opened a pull request with the above fix that solved this issue for us. Let us know what you think. Thanks!

**Comment by MatteoGabriele** [comment]
this has been merged
