### ISSUE TITLE
Make the documentation clear that page views with router object won't work for paths in ignoreRoutes 

### ISSUE THREAD

**Issue by mrwwalmsley** [MatteoGabriele/vue-analytics#206]
I added several of my pages to ignoreRoutes so that I could manually trigger page views for those pages.

Then I used `this.$ga.page(this.$router)` to trigger page views for those pages. This didn't work, since they were in `ignoreRoutes`.

Perhaps the documentation should make this clear?

**Comment by MatteoGabriele** [comment]
I might need to ignore routes only when used by my internal router change so that manually will still be possible to achieve

thanks for the feedback
