### ISSUE TITLE
Lighthouse performance

### ISSUE THREAD

**Issue by lludol** [MatteoGabriele/vue-analytics#208]
### Description

Lighthouse told me that Google analytics is not well loaded when I use your plugin.

### Actual behavior

Here is the Lighthouse "error":
````
Preconnect to required origins
Consider adding preconnect or dns-prefetch resource hints to establish early connections to important third-party origins. 
````

Here is the Google documentation: https://developers.google.com/web/fundamentals/performance/resource-prioritization#preconnect

They told us to "just" add ```preconnect``` attribute like this:
```
<link rel="preconnect" href="https://example.com">
```

Thank you if someone can fix it. If I have the time I will try to make a PR.

**Comment by MatteoGabriele** [comment]
Thanks! A PR would be nice, I'm currently out of town :)

**Comment by MatteoGabriele** [comment]
@lludol I was having a look at this but link is not for js files so it is kinda weird that lighthouse was suggesting you this

**Comment by MatteoGabriele** [comment]
please re-open this when you have some more details

thanks

**Comment by kevinmarrec** [comment]
@lludol Any news about fixing this ?

I got a screenshot here 

![image](https://user-images.githubusercontent.com/25272043/64592182-bb7e5d80-d3ab-11e9-88e5-2bc5ed17c4f1.png)

It's from Lighthouse results run on https://marrec.io (Mobile 4G)

**Comment by emerg** [comment]
@MatteoGabriele I just sent you an email about this a little bit ago before I came across this thread. I thought it was interesting that the lighthouse report comes back with this as well, because I was a little confused by the
```
<link rel="preconnect" href="https://example.com"> 
```
when the resource the lighthouse report is talking about is a script tag.
Anyway, the report I'm getting back from Lighthouse is exactly the same as @kevinmarrec 's screen shot above.

**Comment by doutatsu** [comment]
I am getting the same report as @kevinmarrec. Would be great to get this sorted

**Comment by MattixNow** [comment]
Any news about this issue ?

**Comment by doutatsu** [comment]
Have you tested your fix @MatteoGabriele? I've just upgraded and tested it out, but I am still seeing the same warning in Audit.

![image](https://user-images.githubusercontent.com/4270980/68973483-4df51000-07e6-11ea-8ccf-affe84ede285.png)

**Comment by MatteoGabriele** [comment]
Yes I did. Did you update? You can check the rendered script tag in the head?

**Comment by doutatsu** [comment]
Yup, its there. Not sure why Audit is still failing. I'll keep looking if its something on my side, thanks for the fix on the pacakge side 👍 
![image](https://user-images.githubusercontent.com/4270980/68973715-dc699180-07e6-11ea-998e-6ee6a245c346.png)

**Comment by Matiyeu** [comment]
Any news? Tested @MatteoGabriele ?

**Comment by MatteoGabriele** [comment]
Well I have attached the attribute. Not sure what to do more :)

**Comment by kevinmarrec** [comment]
@MatteoGabriele `rel` isn't a valid thing for `script` : https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script, it is just ignored and does nothing.

It needs to be an additional 
```html
<link rel="preconnect" href="https://www.google-analytics.com"> 
```

`preconnect` only works with `link` tag, and there is only `link` mention in https://developers.google.com/web/fundamentals/performance/resource-prioritization?utm_source=lighthouse&utm_medium=devtools#preconnect

So `link` is required to tell the browser that your page intends to establish a connection to `https://www.google-analytics.com`. In our case, the `https://www.google-analytics.com/analytics.js` script.

So the fix would be about :
- Remove useless `rel="preconnect"` of current `script` tag.
- Add in head : 
```html
<link rel="preconnect" href="https://www.google-analytics.com"> 
```

**Comment by kevinmarrec** [comment]
Still, I don't think so it is achievable around `vue-analytics` plugin, cause the `link` needs to be present in the HTML of the first call (i.e. can be done with Vue SSR / Nuxt).

**Comment by MatteoGabriele** [comment]
Ah good to know! Didn't know that. I can still do it. Thanks

**Comment by ricardogobbosouza** [comment]
The link should be `<link rel="preconnect" href="https://www.google-analytics.com">` instead of `<link rel="preconnect" href="https://www.google-analytics.com/analytics.js">` no?

**Comment by MatteoGabriele** [comment]
ah sorry, now I actually understand what you mean! you're right!
I'll fix it right away
thanks @ricardogobbosouza

**Comment by ricardogobbosouza** [comment]
@MatteoGabriele Need to update here too https://github.com/MatteoGabriele/vue-gtag/blob/master/src/util.js#L8
