### ISSUE TITLE
Support for Google Optimize (ga require)

### ISSUE THREAD

**Issue by wopian** [MatteoGabriele/vue-analytics#21]
[Google Optimize](https://optimize.google.com) requires inserting `ga('require', 'GTM-XXXXXXX');` into Analytics to function correctly. However it's currently only possible to add `ga('set')`.

**Comment by MatteoGabriele** [comment]
@wopian I will make a `require` method and also maybe also a method that can do everything if really needed. Could maybe be handy.

thanks for the suggestion :)

**Comment by MatteoGabriele** [comment]
I've added the `require` method so now you can write `Vue.$ga.require('GTM-XXXXXXX')`
Also added the `query` method that allows you to pretty much do everything i didn't implement yet

available in the v3.2.0
