### ISSUE TITLE
How to implement google analytics on vue app on multiple domains?

### ISSUE THREAD

**Issue by japhfortin** [MatteoGabriele/vue-analytics#210]
I have multiple domains that use the same files (from git master branch). Now, I want to implement google analytics on each domain.

I've tried this vue-anlaytics package multiple domain tracking (see link - https://medium.com/dailyjs/tips-tricks-for-vue-analytics-87a9d2838915#7ead) but the problem is whenever I try to visit domain1.com. It also registers on the domain2.com google analytics dashboard.

Please help.

**Comment by MatteoGabriele** [comment]
The multiple domain tracking is exactly that: you add an array of IDs and they will all register the same things. Multiple tracking doesn't mean that it is going to detect in which domain it is and fire only one of them. 

You need to add your personal logic for that, it's a fairly easy check :)

**Comment by japhfortin** [comment]
Thanks! I've solved it by using an environment variable.

**Comment by MatteoGabriele** [comment]
Perfect solution
