### ISSUE TITLE
Change analytics ID in subdirectory [help wanted]

### ISSUE THREAD

**Issue by miskomv** [MatteoGabriele/vue-analytics#211]
Hi, i have a SPA in a url like this:
http://www.domain.com

And i have a different SPA in a subdirectory, like this:
http://www.domain.com/subdirectory

How can i change Analytics ID ( UA field ) to be different in the subdirectory ¿?

**Comment by MatteoGabriele** [comment]
If you have two different builds, I would you an environment variable and then switch ID based on that, otherwise you might need to read your URL and detect if you're under the "subdirectory" and switch from there
