### ISSUE TITLE
Displaying Analytics Report on on Component

### ISSUE THREAD

**Issue by Yusadolat** [MatteoGabriele/vue-analytics#212]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description
Displaying analytics report on Vue Component
What are you reporting?
I'm asking fo feature if it doesn't work the way asked
### Expected behavior

Tell us what you think should happen.
I will like to display some of what i see on google analytics on part of my vue components.
### Actual behavior

Tell us what actually happens.

### Environment

Run this command in the project folder and fill in their results:

`npm ls vue-analytics`: 

Then, specify:

1. Operating system:
2. Browser and version:

### Reproducible Demo

Please take the time to create a new app that reproduces the issue or at least some code example

Demonstrable issues gets fixed faster.

**Comment by MatteoGabriele** [comment]
I'm sorry but this it's a bit out of the scope of the library. I do deal with UI for this library: it's only a vuejs wrapper of Google's library + some automations.

thanks anyway
