### ISSUE TITLE
Query params with value "undefined"

### ISSUE THREAD

**Issue by Amareis** [MatteoGabriele/vue-analytics#216]
### Description

Simple showcase:
`<v-btn :to="{name: 'someRoute', query: {param: undefined}}">Button</v-btn>`
Vue router forms right query string (without `param` entirely), but in GA this page shows with `param=undefined`
![image](https://user-images.githubusercontent.com/4806617/58369088-17ad9680-7f0f-11e9-98c4-9345d510bf15.png)

### Expected behavior
Page route in GA match the vue-router one.

### Actual behavior
Query params with `undefined` value are appeared.

### Environment
vue-analytics@5.16.4
Ubuntu, Chrome 72.0.3626.121

**Comment by MatteoGabriele** [comment]
but why would you pass underfined as a querystring value?

**Comment by Amareis** [comment]
![image](https://user-images.githubusercontent.com/4806617/58686847-63da5a00-8399-11e9-885a-972eea329ea8.png)
Just for shortening

**Comment by MatteoGabriele** [comment]
I would put `null` if I was you, but I will look into it to check if the property value is undefined or null, to no add the property at all
