### ISSUE TITLE
Catching 'window.ga is not a function error'

### ISSUE THREAD

**Issue by nieroda** [MatteoGabriele/vue-analytics#217]
What are you reporting?

If the user is using an adblock / track block this error will throw.
vue-analytics.js?0183:1 window.ga is not a function

Is it possible to catch it so we know that the user is using blockers? I tried wrapping it in a try catch to no avail.

**Comment by MatteoGabriele** [comment]
I also ask myself why there's a template for issues and nobody ever uses it.
Btw tell me which version you have.
This ticket should also already be around cause I remember it

**Comment by nieroda** [comment]
Sorry - I thought of it less of an issue and more of a feature request since it all works as advertised

**Comment by f213** [comment]
@MatteoGabriele Could you please apply the patch from 8121bf7 to the master branch?

Drop me a line if you have no time for this — i will create a PR for you.
