### ISSUE TITLE
Make existing GA detection more strict

### ISSUE THREAD

**Issue by MKRazz** [MatteoGabriele/vue-analytics#218]
The check for existing Google Analytics is a bit vague and can easily cause false positives. 

https://github.com/MatteoGabriele/vue-analytics/blob/0809338d490508b5c328f7f6facd0201a1b1d5ad/src/helpers.js#L45-L54

A site I loaded this plugin on has 'analytics' in the host name and it caused GA not to load 😅.

**Comment by MatteoGabriele** [comment]
uh! will check a better one thanks
