### ISSUE TITLE
Conflict with already loaded analytics script

### ISSUE THREAD

**Issue by MrMoins** [MatteoGabriele/vue-analytics#220]
I made a embeddable widget and I want to track events in it.
When the widget is embedded on a website not using Google Analytics all is fine, tracking is done correctly.
But when the website is already using Google Analytics tracking in widget does not work anymore, events are fired on website property.
I try to instantiate with a table of IDs (but just one ID) and that doesn't solve my issue.

See logs : https://www.dropbox.com/s/z3qj8w6azqsbf2x/Capture%20d%E2%80%99%C3%A9cran%202019-06-04%20%C3%A0%2010.12.10.png?dl=0

**Comment by MatteoGabriele** [comment]
you might want to read this part of the documentation 

https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/script-loader.md

**Comment by MrMoins** [comment]
I saw well. But the problem is not there.

It would be necessary that vue-analytics allows to explicitly give a name to the tracker (or generate a random one) and then use it during tracking. 

This would not conflict with a tracker already present.
