### ISSUE TITLE
Custom fields are not being sent

### ISSUE THREAD

**Issue by mateuszs** [MatteoGabriele/vue-analytics#222]
### Description

When I set custom fields like below, no 'someMetric' query param is being sent.

```
Vue.use(VueAnalytics, {
                id: ['UA-123-3'],
                router,
                customIdFields: {
                    'UA-123-3': {
                         someMetric: 'blabla'
                    }
                },
                debug: {enabled: true}
            })
```

### Expected behavior

It should be 'someMetric' query param in analytics request.

### Actual behavior

No additional key is sent

### Environment

1. Operating system: OSX
2. Browser and version: Chrome newest

**Comment by FirefoxMetzger** [comment]
I might be wrong (quite new to GA), but are you sure it is possible to track custom fields in the cookie?

My understanding is that the field has to be one of those specified in the [Field Reference](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference)

**Comment by MatteoGabriele** [comment]
it doesn't work because it only works when you use multiple IDs. in your example you use only one ID so there's no need for targeting customIdFields
