### ISSUE TITLE
v-ga documentation parses string into event value

### ISSUE THREAD

**Issue by FirefoxMetzger** [MatteoGabriele/vue-analytics#224]
In the doc for `v-ga` ([here](https://github.com/MatteoGabriele/vue-analytics/blame/9b7125472dc1313823e6c03538434d22b4edad8a/docs/v-ga.md#L39)) the example passes the name as the value field to google analytics.

Why does this work? From what I understand you must pass positive integers in the value field and no other variable types are allowed. Am I overlooking something or is this an error in the documentation?

**Comment by bohdan-shulha** [comment]
I believe this one is just a mistake because Google Analytics documentation clearly says the value must be an integer.

https://support.google.com/analytics/answer/1033068?hl=en

**Comment by MatteoGabriele** [comment]
it was a simple example to be honest, I wasn't paying attention on what I was passing, but thanks for the feedback
