### ISSUE TITLE
[Suggestion] Installation in components

### ISSUE THREAD

**Issue by Major666RUS** [MatteoGabriele/vue-analytics#227]
Installation vue-analytics looks like that.

```
import Vue from 'vue'
import VueAnalytics from 'vue-analytics'

Vue.use(VueAnalytics, {
  id: 'UA-XXX-X'
})
```

But such way of installation requires from me to know tracker's id. In my project there are trackers's id in the database. I get it throw API in my single-file-component. So I need to install vue-analitics in the component. But I can't do it. 
Yeah, I know I can use Promise, like that:

```
// a Promise
Vue.use(VueAnalytics, {
  id: axios.get('/api/foo').then(response => {
    return response.data
  })
})
```

But I can't get access to router.params (in order to get required tracker's id from the database depending on the curent page) and have to work with window.location that it's not very nice. Maybe it is not popular case but it could help to someone (me, for example).

**Comment by MatteoGabriele** [comment]
trackers are created at the very beginning and also the fact that you need a tracker for each page is a very very specific use case so I can't really focus on this one, I'm sorry.

cheers
