### ISSUE TITLE
[Suggestion] Allow to pass array to v-ga

### ISSUE THREAD

**Issue by bohdan-shulha** [MatteoGabriele/vue-analytics#228]
### Explanation

Currently, we can use argument-less commands this way (example 1)

```javascript
<a v-ga="'trackSomething'">Link</a>
```

And command with arguments like this (example 2)

```javascript
<a v-ga="$ga.commands.trackSomething.bind(this, 'My Link')">Link</a>
```

As you may see, there is a bit of boilerplate when the command accepts arguments.

### Use Cases

I use Nuxt.js and it is not possible to use `v-ga` for cases when the command needs to receive an argument, `$ga` is simply not defined and example 2 just fails saying `undefined has no commands`. It is possible to define a method in a Vue component and simply use `@click` but it is even more boilerplate to code.

### Proposal

Make it possible to use `v-ga` like this

```javascript
<a v-ga="['trackSomething', 'My Link']">Link</a>
```

**Comment by MatteoGabriele** [comment]
I'm not sure about this idea tbh and also I just find the directive not nice to use in the first place and wonder if it actually adds value
