### ISSUE TITLE
Page error with redirect

### ISSUE THREAD

**Issue by dan2600** [MatteoGabriele/vue-analytics#229]
Hi, 

I'm using this library in part to track an event when users click an outbound link. Clicking the link fires the event, preventing the default, and then i set the window location to go to the link.

The problem is if I do the code like this:

this.$ga.event('outbound click', 'target title', 'target category')
window.location = e.target.parentNode.href

The GA event gets attached to the next page, and I get a page unset error in my GA. I was able to fix it with a short timeout.

this.$ga.event('outbound click', 'target title', 'target category')
setTimeout(()=>{window.location = e.target.parentNode.href;},150)

Ideally, the event function would have a callback or promise.  Hope this helps.

**Comment by MatteoGabriele** [comment]
try this 

https://github.com/MatteoGabriele/vue-analytics/issues/47
