### ISSUE TITLE
Add supported vue and vue-router versions to readme

### ISSUE THREAD

**Issue by thatandyrose** [MatteoGabriele/vue-analytics#23]
Hey!

Just a quick nitpick that might actually be useful to others. It would be good to add supported versions of Vue to the readme...?

thanks for this awesome library!

**Comment by MatteoGabriele** [comment]
done! :)

thanks for you suggestion!

**Comment by thatandyrose** [comment]
@MatteoGabriele wow that was quick :-) 👍
