### ISSUE TITLE
GA Site Speed with Vue-Analytics

### ISSUE THREAD

**Issue by fm-adam** [MatteoGabriele/vue-analytics#232]
Hello,

Great package and docs. Vue-Analytics was a breeze to install and to get started with. Thank you. I am now looking at enabling Site Speed (`siteSpeedSampleRate `) to get GA metrics for Avg. Page Load Time, Avg. Redirection Time, etc, but I cannot find any reference for support for this feature in your docs or issue tracker, and the data is definitely not showing up in my GA dashboard. So, is it possible to enable GA Speed Tracking using Vue-Analytics. If so, can you point me in the right direction.

Thanks

**Comment by MatteoGabriele** [comment]
Thanks for your feedback :)

I believe that siteSpeedSampleRate is a field that needs to be added on create of the tracker, so you might want to try

```js
Vue.use(VueAnalytics, {
  id: 'UA-XXX-X',
  fields: {
    siteSpeedSampleRate: 10
  }
})
```

reference link https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#siteSpeedSampleRate
