### ISSUE TITLE
Multiple trackers in ID array appear to send no data to either GA accounts

### ISSUE THREAD

**Issue by ok200paul** [MatteoGabriele/vue-analytics#233]
Quickly to begin: Thanks so much for such a useful package, I've used it for a long time! Hopefully this issue is valid, and not something I've missed. Paul

### Description

When using an array of multiple GA IDs, it looks like neither account gets data sent to them. Using a single ID within an array appears to work OK.

### Expected behavior

Placing multiple IDs into the `id` array sends data to both GA accounts.

### Actual behavior

Using a single ID (within an array) works fine. Any more than one, send no hit data to all GA accounts.

### Environment

Run this command in the project folder and fill in their results:

`npm ls vue-analytics`: vue-analytics@5.17.0 

Then, specify:

1. Operating system: Mac OS Mojave 10.14.5
2. Browser and version: Chrome Version 76.0.3809.100 (Official Build) (64-bit)

### Reproducible Demo

https://github.com/ok200paul/vue-analytics-multiple-tracker-issue

**Comment by MatteoGabriele** [comment]
hi @ok200paul thanks for your feedback
I've found your setup a bit hard to test tbh, could you please create a simple application with vue-cli? it is a standard stable setup + I'm able to run webpack without need to recompile each time I make a change

thanks a lot
