### ISSUE TITLE
Not load analytics.js when disabled and/or disableScriptLoader are being using

### ISSUE THREAD

**Issue by thebspin** [MatteoGabriele/vue-analytics#235]
### Description

I am trying to comply to the GDRP. From my understanding if  i load the analytics js i am already in violation, even if i technicly only load it and don't use it.

### Expected behavior

Using:
disableScriptLoader: true,
disabled: true

I would expect that analytics.js is not being loaded.

### Actual behavior

analytics.js is being loaded in the header.

**Comment by MatteoGabriele** [comment]
thanks for the feedback! didn't catch this one :)

**Comment by dsturm** [comment]
Hey @MatteoGabriele, is there any progress on this?
