### ISSUE TITLE
Check if tracking is disabled

### ISSUE THREAD

**Issue by leo1200** [MatteoGabriele/vue-analytics#236]
A function like this.$ga.disabled() returning a boolean would be great.

**Comment by MatteoGabriele** [comment]
Can i ask you for what purpose?

**Comment by leo1200** [comment]
Integration of a feature to stop GA for the current session - enabling the
user to check if GA is still disabled. This, however, is not necessary
anymore, as I decided on a different implementation:
https://lernzettel.org/#/funktionen/google-analytics-deaktivieren

Matteo Gabriele <notifications@github.com> schrieb am So., 18. Aug. 2019,
22:00:

**Comment by MatteoGabriele** [comment]
can't really read the content of that link but in this case I will close the ticket
thanks
