### ISSUE TITLE
Auto-Tracking does not update the tracker page reference

### ISSUE THREAD

**Issue by mikereinhold** [MatteoGabriele/vue-analytics#24]
Currently the auto tracking feature only sends the pageview hit and does not update the tracker's internal page location reference via 
```javascript
ga('set', 'page', '/new-page.html');
```
As a result, events, social interactions, user timings, etc always show the landing page as the "page" for the event in Google Analytics - reducing visibility to where the event, social interaction, or user timing actually happened.

For reference, see Google's Analytics reference for [Single Page Applications](https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications).

> While technically the send command for pageview hits accepts an optional page field as the third parameter, passing the page field that way is not recommended when tracking single page applications. This is because fields passed via the send command are not set on the tracker—they apply to the current hit only. Not updating the tracker will cause problems if your application sends any non-pageview hits (e.g. events or social interactions), as those hits will be associated with whatever page value the tracker had when it was created.

**Comment by MatteoGabriele** [comment]
issue closed
see PR #25

**Comment by MatteoGabriele** [comment]
fix available with v3.2.1

**Comment by mikereinhold** [comment]
Thanks! :)
