### ISSUE TITLE
Question: Loading script at a later time?

### ISSUE THREAD

**Issue by jrtnq514** [MatteoGabriele/vue-analytics#240]
I really want to use this plugin but have a situation (security policy) where I cannot load the script on the page until a check (ajax call) is made. Unfortunately I can't just disable the script it has to be completely off the page. I have thought of a few possible options and want to confirm if they're possible or not.

1. Set `disableScriptLoader: true` add the analytics script myself at a later time. I'm assuming the plugin would pick up the script when it does get added.
2. Make the check call and in `main.js` and conditionally use the plugin. This would mean the app won't be rendered until the call is resolved.
3. Is there anyway to use `loadScript` through the api? If not can it be exposed in a future release?

Thanks!

**Comment by MatteoGabriele** [comment]
hey @jrtnq514 
I've never checked but the first option might not work tbh, but you can try.
the second one will work for sure but I get it that it's a bit hacky and doesn't sound like a nice piece of code to write.
I can expose the helper, but I won't help with the cause.
I'm gonna need to have a look at how few things:
- how to bootstrap later
- load on demand
- share utilities

I hope I can come back to you soon, if you have any ideas, please don't hesitate to open a Pull Request

thanks

**Comment by cassioscabral** [comment]
I actually think this is quite important for EU legislation and the whole GDPR issues. The user must consent to the usage of tracking before any tracking script loading. 

I tried to set the disabled property on main.js and later do `$ga.enable()` but realized that's not actually working.

When setting disabled at first, GA will think that the user has already opt-out and I can't get to activate later. And activating at first (default disabled property set to false) will load the cookies anyway which could be a legal breach.

Here you can check what I'm referring to: https://techcrunch.com/2019/10/01/europes-top-court-says-active-consent-is-needed-for-tracking-cookies/

**Comment by MatteoGabriele** [comment]
yeah but if you set `disabled` to `true` on plugin install, you are not tracking: just loads a js file that is not actively used by the application, so as for the GDPR rules should be ok.
does this make sense?

**Comment by cassioscabral** [comment]
Setting disabled to true at installing it's fine, it safe for GDPR as far as I know (which is very little).

But enabling (with `this.$ga.enable()`) later, let's say after the user has done the consent, I don't see it the same GA cookies or the others like when I set disabled to false.

I did some local testings and if I could control the bootstrap function, exposing it, it does work, but I don't know the extent of the function and the impact of just calling that whenever I need it. For example, calling twice will generate two <script> tags, since bootstrap was supposed to be called only once.

For me, it would be nice to control when to load, so I could ask the user first for consent and have the same behavior as if you were setting disabled to false from the beginning.

**Comment by MatteoGabriele** [comment]
it makes sense indeed. I should have finally some time to work on it this week. I'll update you 
thanks a lot for your feedback

very much appreciated

**Comment by cassioscabral** [comment]
Just an FYI, I was able to overcome this a bit by using Promises with the disabled property. The only drawback is that you must create an App prop with this promise that's it's set on main.js file and provided on the Vue app instantiation phase.

Later on, you just need to execute the promise when the user has done the consent.

**Comment by xiev** [comment]
Hey @cassioscabral, could you provide a snippet how you handled this? I have the exact same problem, that `this.$ga.enable()` isn't doing what I thought it would. 

I'm fairly new to Vue.js and don't really understand what you mean by: 

>  you must create an App prop with this promise that's it's set on main.js file and provided on the Vue app instantiation phase

**Comment by cassioscabral** [comment]
Sure, no problem.


On your main.js file
```js
import Vue from 'vue';
import App from './App.vue';
import VueAnalytics from 'vue-analytics';
import router from './router';
import store from './store';

let disabledVueGA;
Vue.use(VueAnalytics, {
  id: 'myID',
  disabled: () => new Promise(r => (disabledVueGA = r))
});

new Vue({
  router,
  store,
  render: h => h(App, { props: { disabledVueGA } })
}).$mount('#app');
```

on you App.vue props definition
```js
props: {
  disabledVueGA: { type: Function, required: true }
},
```

Then, when the user accepts it just call `this.disabledVueGA(false); // or true (depends on the consent`

Remember that the disabled property set to false is equal to activating the library. So, it can be confusing.

And after adding the cookies, disabling(`this.$ga.disable()`) it will not remove the cookies, just opt-out. Which is enough to not send anything to GA anymore. But you might want to remove yourself, I'm not sure what's the best/correct way to do it here though.

**Comment by xiev** [comment]
Thank you! This looks good to me, no cookies get set until the user clicks the accept button and also the realtime view shows the correct behavior.

I really appreciate your answer and help!

**Comment by MatteoGabriele** [comment]
@jrtnq514 @cassioscabral @xiev I have implemented this feature un vue-gtag so I won't spend time here because this package will probably be deprecated soon. Google is moving its library and I am doing the same.

thanks for your feedback
