### ISSUE TITLE
After Page Reload, disabled again .

### ISSUE THREAD

**Issue by nawalnew** [MatteoGabriele/vue-analytics#244]
### Description

What are you reporting?

The function this.$ga.enable() is working as expected. But after reload the "enabled" state is gone.  I use vue-cookie-law for a cookie banner. The Cookie is set as expected.

### Expected behavior
Tracking should be saved with the cookie selection. 

### Actual behavior

After page reload the Enabled function istn working anymore and the Google Tag is not tracking anymore.

### Environment

1. Operating system:
Mac OSX
2. Browser and version:
All Browsers:
Safari, Firefox and Chrome

### Reproducible Demo

https://boxliebe.de 

Default.vue:
```
<template>
  <div>
    <slot/>
    <ClientOnly>
        <cookie-law theme="base" storageType="cookies" v-on:accept="enableTracking()">
          <div slot="message">
          Wir benutzen Cookies, um die Nutzerfreundlichkeit der Webseite zu verbessern. Durch die weitere Nutzung der Webseite stimmen Sie der Verwendung von Cookies zu. <g-link to="/datenschutz">Datenschutzerklärung</g-link>
        </div></cookie-law>
      </ClientOnly>
  </div>
</template>

<script>
import CookieLaw from 'vue-cookie-law'

export default {

  components: { CookieLaw },
  methods: {
    disableTracking () {
      this.$ga.disable()
      // from now on analytics is disabled
    },
    enableTracking () {
      this.$ga.enable()
      // from now on analytics is enabled
      console.log("enabled")
    }
  }</script>
```

**Comment by MatteoGabriele** [comment]
you can read about `disabled` option here. https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/opt-out.md

you can simply pass the value of the cookie: can be a boolean, a function returning a boolean or even a promise return a boolean, but since you have a cookie, just take the value of the cookie
