### ISSUE TITLE
Any plans to support gtag?

### ISSUE THREAD

**Issue by gecko-8** [MatteoGabriele/vue-analytics#245]
Just asking as Google seems to be pushing everyone to use gtag.js now and there aren't any good plugins for it yet. This seems to be the most polished plugin so it would be great to see it added.
Thanks,
Jason

**Comment by MatteoGabriele** [comment]
yeah I know. but unfortunately I have been having less and less time so right now I mainly try to fix bug and give some easy feature back.
I need to read the API again, last time I checked was too soon and was unclear gibberish

totally valid point tho

I hope I can schedule some time for this

**Comment by MatteoGabriele** [comment]
@gecko-8 I've release a version of [vue-gtag](https://github.com/MatteoGabriele/vue-gtag) still need to finish tests and documentation, but would be nice if you could try it and get some feedback

cheers :)

**Comment by gecko-8** [comment]
@MatteoGabriele Sorry for the slow response, I've been sick with the flu and job hunting for the past few weeks. Unfortunately I don't have any projects I can test it on but it looks really good!

**Comment by MatteoGabriele** [comment]
@gecko-8 no worries at all, get better and good luck with job hunting!
