### ISSUE TITLE
Set custom dimension when using multiple trackers

### ISSUE THREAD

**Issue by jratzenboeck** [MatteoGabriele/vue-analytics#246]
### Description

As pointed out in the documentation you can specify multiple trackers in the configuration of the plugin to send hits two multiple ga properties. This works fine. However, the plugin gives me an error if I use `this.$ga.set('dimension1', 'A')` to set a custom dimension, which from then on should be send along each pageview and tracked event. Every tracked hit lacks of the custom dimension I tried to set.

### Expected behavior

It should set the custom dimension for all following hits on the page. 

### Actual behavior

It gives me the following error in the dev console and does not set the dimension for the following hits.

![Screenshot 2019-10-09 at 17 22 32](https://user-images.githubusercontent.com/15803745/66495361-6e300180-eab9-11e9-8631-def838910096.png)

### Environment

Run this command in the project folder and fill in their results:

`npm ls vue-analytics`: vue-analytics@5.16.4 

Then, specify:

1. Operating system: MacOS Mojave 10.14.3 (18D42)
2. Browser and version: Version 77.0.3865.90 (Official Build) (64-bit)

### Reproducible Demo

I have not yet had time to create a small stand-alone app which shows the error. I hope I can add this within the next few days if it helps fixing the issue.

**Comment by MatteoGabriele** [comment]
don't really understand that error you added in the image, but would be nice to have a reproduction. if I have enough time I will try it myself.

thanks for you time

**Comment by jratzenboeck** [comment]
Thank you for taking a look on this! For your information: In the meantime I could manage to send the dimension along every event I track and with the `pageViewTemplate` function inside the `autoTracking` I can add the dimension to every pageview as well.

**Comment by Bergrebell** [comment]
@jratzenboeck - nice that you found a solution! would you mind sharing it here? I'm having the same issue.

**Comment by jratzenboeck** [comment]
first of all, sorry for the late answer. I hope you can still use my solution. It looks like this.

```
autoTracking: {
        pageviewTemplate(route) {
            const pageData = { page: route.path };
            const { dimensionName, dimensionValue } = store.state.ga;
            if (dimensionName && dimensionValue) {
                pageData[dimensionName] = dimensionValue;
            }
            return pageData;
        },
    },
```

In this project I use VueJS and have the `dimensionName` and `dimensionValue` stored in the Vuex Store as pointed out in the destructuring statement `const { dimensionName, dimensionValue } = store.state.ga;`. 
This will be set as soon as I need the dimension information to be tracked.

**Comment by MatteoGabriele** [comment]
I have to be honest, I'm lately working on the vue-gtag package which will basically replace this one soon. So I'll probably move all feature requests to the other package
