### ISSUE TITLE
lodash vulnerabilities

### ISSUE THREAD

**Issue by woodgates** [MatteoGabriele/vue-analytics#247]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description

Hi.
After installing I got this message
found 525 vulnerabilities (10 moderate, 514 high, 1 critical) in 28926 scanned packages

lodash was responsable for a the ones I could see.

### Expected behavior

Non having this message

### Recommended solution:
This is a know issue, I found information here.
https://snyk.io/blog/snyk-research-team-discovers-severe-prototype-pollution-security-vulnerabilities-affecting-all-versions-of-lodash/

**Comment by MatteoGabriele** [comment]
I am currently updating the entire compiler and also all tests too, so I guess when that will be done all vulnerabilities will go away.
the are all part of devDependencies tbh, this library has zero dependencies, but for some reasons npm keeps on alert you.

**Comment by MatteoGabriele** [comment]
duplicate of #221

**Comment by woodgates** [comment]
the problem gets solved following npm fix instructions.
