### ISSUE TITLE
Track branch information for split-testing

### ISSUE THREAD

**Issue by Bergrebell** [MatteoGabriele/vue-analytics#248]
I want to perform a split-test on one of my sites. Usually I would add a method call that sends the branch-name to analytics in a script like this:

```
<script>
  ga('send', 'pageview', {
    'Branch':  '{{ getenv "BRANCH" }}'
  });
</script>
```

how can I achieve this in vue-analytics?

**Comment by MatteoGabriele** [comment]
for a manual hit like this you can simply use the `this.$ga.query` inside your component, which is nothing more that the exposed `ga` library inside the Vue instance.

```js
this.$ga.query('send', 'pageview', {
  'Branch': '{{ getenv "BRANCH" }}'
});
```
