### ISSUE TITLE
ERR_UNSAFE_REDIRECT with https

### ISSUE THREAD

**Issue by woodgates** [MatteoGabriele/vue-analytics#249]
### Description
Hi. I'm implementing my app on production and I'm getting this error:
vue-analytics.js:1 GET https://www.google-analytics.com/analytics.js net::ERR_UNSAFE_REDIRECT

my page is https.

this is my main.js

Vue.use(VueAnalytics,{
  id:'UA-150321348-1',
  router,
  debug:{
    enabled:!isProd,
    sendHitTask:isProd
  }
})

please your help.

**Comment by MatteoGabriele** [comment]
this is almost certainly an ad block issue
