### ISSUE TITLE
SSR broken in 5.17.3

### ISSUE THREAD

**Issue by mikerogerz** [MatteoGabriele/vue-analytics#252]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description

Latest version breaks in SSR.

### Expected behavior

Work the same as 5.17.2.

### Actual behavior

`window is not defined`
`at Object../node_modules/vue-analytics/dist/vue-analytics.js`

### Environment

Run this command in the project folder and fill in their results:

`npm ls vue-analytics`: 

└── vue-analytics@5.17.3

Then, specify:

1. Operating system:
Ubuntu 19.04
2. Browser and version:
Chrome 79

**Comment by deepenpatel19** [comment]
Same issue I face on production. 
I'm not able to load even single page due to this library. 

Library:
- vue-analytics@5.17.3
- vue@2.6.10

Browser:
Chrome (77.0.3865.120).

OS:
- AMI

**Comment by MatteoGabriele** [comment]
yeah I see! somehow webpack is adding the window object in the compiled file, it's not the library itself. I'm trying to understand what am I missing but for the time being just use 5.17.2

sorry for the inconvenience

**Comment by MatteoGabriele** [comment]
@mikerogerz should be fixed, let me know and thanks a lot for the feedback

**Comment by mikerogerz** [comment]
New version works great. Thanks for the quick response.
