### ISSUE TITLE
Add demographics

### ISSUE THREAD

**Issue by FilipeamTeixeira** [MatteoGabriele/vue-analytics#254]
I'm trying to add demographics analytics to my code, but I'm not sure how to incorporate this in the vue-analytics plugin.
According to the google analytics support page (https://support.google.com/analytics/answer/2444872), it should be possible to add that information by adding `ga('require', 'displayfeatures');` between the create and send.

However, I'm not really sure how to do it here.

Thank you

**Comment by MatteoGabriele** [comment]
I'm quite sure it was in the documentation but now I'm doubting. it is possible to inject a collection of `set` or `require` in the plugin options and those will be fired after the trackers are initialised.
if you need something before, you can use the `beforeFirstHit` callback method

```js
import Vue from 'vue'
import VueAnalytics from 'vue-analytics'

Vue.use(VueAnalytics, {
  id: 'UA-XXX-X',
  beforeFirstHit () {
     Vue.$ga.require('displayfeatures')
  }
})
```

**Comment by MatteoGabriele** [comment]
Sorry, you can actually use it like this

```js
import Vue from 'vue'
import VueAnalytics from 'vue-analytics'

Vue.use(VueAnalytics, {
  id: 'UA-XXX-X',
  requires: ['displayfeatures']
})
