### ISSUE TITLE
Question: Is it possible to skip the first page openning ?

### ISSUE THREAD

**Issue by oduvan** [MatteoGabriele/vue-analytics#256]
If I have a legacy  ga layer on top of vue-js app. This layer tracks page opening when application is loading. But when it is loaded all router actions are trackable inside of the app.

So in order to avoid duplication of ga-pageview event (one from legacy and one from vue), can I ask vue do not track first openinig?

Thank you

**Comment by MatteoGabriele** [comment]
https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/page-tracking.md#disable-pageview-hit-on-page-load

**Comment by oduvan** [comment]
thank you.
