### ISSUE TITLE
Add router at a later stage

### ISSUE THREAD

**Issue by sebastian-raubach** [MatteoGabriele/vue-analytics#257]
Is there a way to add the `router` after the initialisation like through a `$ga.setRouter` method or something like that? I'm in a situation where I create vie-analytics in the `store`, but the `router` imports the `store`, hence, if I try to use `router` in `store`, I've got a circular dependency.

**Comment by sebastian-raubach** [comment]
Ended up just calling `Vue.$ga.page(router)` from the router in `beforeEach`.

**Comment by MatteoGabriele** [comment]
I'm sorry but your use case is too specific. Not sure why would you install a plug-in from Vuex. Hopefully your implementation will be enough

Cheers :)
