### ISSUE TITLE
How to wait for GA Event "Sent" in the case of Form Submission / User Redirection?

### ISSUE THREAD

**Issue by necevil** [MatteoGabriele/vue-analytics#26]
In my use case I am submitting a form and triggering an event to be sent when that form is submitted.  The trick is that I want to wait until I KNOW that GA has recorded the event before I allow the user to be redirected.

Google Analytics docs normally suggest something like this:

```
 ga('send', 'event', {
   'eventCategory': 'YOUR Category Name', //required
   'eventAction': 'YOUR Action name', //required
   'eventLabel': 'YOUR Label',
   'eventValue': 1,
   'hitCallback': function() {
       console.log('Sent!!');
      //callback function
    },
   'hitCallbackFail' : function () {
      console.log("Unable to send Google Analytics data");
      //callback function
   }
```

My question is, how can I listen for the hitCallBack with Vue-Analytics?

**Comment by MatteoGabriele** [comment]
Currently is not possible with the `trackEvent` method, I'll going to make some adjustment to support also objects, but for now you can simply use the `query` method available since v3.1.0

```js
this.$ga.query('send', 'event', {
  'eventCategory': 'YOUR Category Name',
  'eventAction': 'YOUR Action name',
  'eventLabel': 'YOUR Label',
  'eventValue': 1,
  hitCallback: function () {
    console.log('Sent!!')
  },
  hitCallbackFail: function () {
    console.log('Unable to send Google Analytics data')
  }
})
```

**Comment by MatteoGabriele** [comment]
see #28

**Comment by necevil** [comment]
Great answer @MatteoGabriele 
Worked like a charm and already into up and running!
Thanks a ton!

**Comment by MatteoGabriele** [comment]
@necevil You're welcome and thanks for your feedback!
