### ISSUE TITLE
$ga does not exist on type VueConstructor

### ISSUE THREAD

**Issue by paolog22** [MatteoGabriele/vue-analytics#269]
![image](https://user-images.githubusercontent.com/12680745/71642553-05d37380-2ce8-11ea-8814-aa5c43b9ed08.png)

> Error:(6, 17) TS2339: Property '$ga' does not exist on type 'VueConstructor<Vue>'.

What am i missing ? 
thank you

environment
"vue-analytics": "^5.20.2",
"vue": "^2.6.10",
typescript: 3.5.3

**Comment by paolog22** [comment]
help ?

**Comment by MatteoGabriele** [comment]
The type definition has been done with support of other collaborators, I honestly don't work with TS so I don't know how to fix this. 
Maybe @romansp knows it :)

**Comment by romansp** [comment]
@paolog22 `$ga` is available on Vue instance itself. Does this work for you? 

```js
import Vue from "vue";

export default class Exception {
  public static register(): void {
    Vue.config.errorHandler = (err, vm, info) => {
      vm.$ga.exception(err.toString());
    };
  }
}
```

I'm not so sure about augmenting `VueConstructor` types. Neither `vue-router` nor `vuex` do it.

**Comment by paolog22** [comment]
@MatteoGabriele @romansp thank you.. did not saw that . thank you for your time sorry for the bother :) . will now close this

**Comment by MatteoGabriele** [comment]
Thanks a lot @romansp
