### ISSUE TITLE
Return Client ID

### ISSUE THREAD

**Issue by OlegShchurin** [MatteoGabriele/vue-analytics#279]
### Description

Hello, could you please add a feature that will return GA Client ID or how to do it using Vue-analytics?

[In Google Analytics its something like this:](https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id#getting_the_client_id_from_the_cookie): 

```
ga(function(tracker) {
  var clientId = tracker.get('clientId');
});
```

**Comment by MatteoGabriele** [comment]
try
```js
$ga.query(function(tracker) {
  var clientId = tracker.get('clientId');
});
```
