### ISSUE TITLE
Doesn't work in Chrome Extension

### ISSUE THREAD

**Issue by artrayd** [MatteoGabriele/vue-analytics#280]
I'm building chrome extensions for Chrome using "kocal/vue-web-extension".

### Description

 After installing vue-analytics I am getting this error:
vue-analytics.js:1 Refused to load the script 'https://www.google-analytics.com/analytics.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

 I added in extension manifest.json this line, but it doesn't help
"content_security_policy": "script-src 'self' https://ssl.google-analytics.com; object-src 'self'",

### Expected behavior

Google analytics should work

### Actual behavior

I am getting this error.

### Environment

Chrome extension

`npm ls vue-analytics`: 

Then, specify:

1. Operating system : MacOS
2. Browser and version: Chrome 83.0.4103.106

I tried to add, but it doesn't help
```
Vue.use(VueAnalytics, {
	id: 'UA-000000-0',
	checkProtocolTask : null 
})
```

I also checked this issue:
https://github.com/MatteoGabriele/vue-analytics/issues/177

Thank you

**Comment by artrayd** [comment]
Seems like it's a problem inside "kocal/vue-web-extension", because when I tried to that without plugin it doesn't work either.

**Comment by axe-me** [comment]
for 5.x this works for me
```js
  Vue.use(VueAnalytics, {
    id: '',
    fields: {
      cookieDomain: "none"
    },
    set: [{ field: "checkProtocolTask", value: null }]
  });
```

also the domain you put into the `content_security_policy` is wrong, should be:  
`"content_security_policy": "script-src 'self' https://www.google-analytics.com; object-src 'self'"`
