### ISSUE TITLE
Using in vue3 will get "Cannot set property '$ga' of undefined" Error

### ISSUE THREAD

**Issue by microchi** [MatteoGabriele/vue-analytics#288]
Using in vue3 will get "Cannot set property '$ga' of undefined" Error

Online SandBox https://codesandbox.io/s/dazzling-pike-riv8o

![Screen](https://user-images.githubusercontent.com/13308256/95735436-60f2b780-0cb7-11eb-8e85-8f5fc741f40e.png)

**Comment by MatteoGabriele** [comment]
Well no surprises here: this plugin is not made for Vue 3 and probably will never be.
If you are creating a new project I would suggest you to use vue-gtag which has a Vue 3 updated version I'm working at. You can install it under vue-gtag-next, but it's still finishing the documentation

**Comment by microchi** [comment]
Got it! Thanks!

**Comment by aboutmydreams** [comment]
Hi, is there anyway to fix it or use GA in vue3 ?

**Comment by MatteoGabriele** [comment]
If you started a new project, I'd suggest you to use vue-gtag. I'm not supporting this package anymore
