### ISSUE TITLE
Tracking each page using Google Analytics 4

### ISSUE THREAD

**Issue by ridhof** [MatteoGabriele/vue-analytics#290]
Hi there, I tried to track user activities on my app using vue-analytics that referenced in [this article](https://webdeasy.de/en/vue-analytics-en/) that published on 9th October. Author mentioned that to use vue-analytics I have to configure it on main vue file like below
```js
Vue.use(VueAnalytics, {
  id: 'UA-xxxxxxxxx-x',
  router
});
```
and then I realized that the id is using UA which stands for Universal Analytics that refers to previous generation of Google Analytics, stated by Google Support in [here](https://support.google.com/analytics/answer/10089681). UA is the default property type for websites prior to 14th October 2020. Means that 14th October and upward is using new version, which is Google Analytics 4 that using `G-xxxxxxxxx` as the new id format.

I tried to copy and paste mindlessly the new format to the Vue Analytics params, it doesn't return any error, yet it doesn't trigger the analytic on Google Analytics dashboard either. I assume that new Google Analytics version is having different approach to trigger analytics compared to the old version. But I'm not sure yet, since it's purely assumption and I am going to read the whole documentation regarding the new version of Google Analytics.

Does someone else also having issue with new version of Google Analytics and vue-analytics?
Thanks!

and I added images to show the Dashboard regarding different behavior of using old version and new version of Google Analytics.
UA (old) version of Google Analytics shows that analytic works well
 ![old version](https://media.discordapp.net/attachments/750304684836651039/770119888399761418/wc9n2hBdl5VAAAAABJRU5ErkJggg.png?width=510&height=452)

Google Analytics 4 (new) version shows that analytics doesn't work at all
![new version](https://media.discordapp.net/attachments/750304684836651039/770119679162318858/unknown.png)

many thanks!!

**Comment by MatteoGabriele** [comment]
@ridhof to be able to use Google Analytics 4 you need to switch to gtag.js so I you have to change package. 
if you are using Vue 2, you can install [vue-gtag](https://github.com/MatteoGabriele/vue-gtag) or, if you are using Vue 3, install [vue-gtag-next](https://github.com/MatteoGabriele/vue-gtag-next) ( this will soon be directly integrated inside vue-gtag once Vue 3 goes out of the `next` flag )

**Comment by ridhof** [comment]
ah I see, I was using vue-gtag and it's already working pretty well. 
but I'll try vue-gtag-next too, thank you!

**Comment by jerrychong25** [comment]
@MatteoGabriele @ridhof Thanks for proving this solution.

Same issue on facing new ID G-XXXX as well.

**vue-gtag** is working perfectly!
