### ISSUE TITLE
[help] addTransaction no being received by Google Analytics

### ISSUE THREAD

**Issue by janswist** [MatteoGabriele/vue-analytics#291]
### Description

Question about implementation:
```js
            this.$ga.ecommerce.setAction('checkout', { step: 5 })
            this.$ga.ecommerce.addTransaction({
              id:       data.eventData.checkout.id,    // Transaction ID. Required.
              name:     data.eventData.product.name, // Product name. Required.
              sku:      data.eventData.product.id,
              category: 'Lifetime Deal',
              price:    data.eventData.checkout.prices.vendor.total,
              quantity: data.eventData.product.quantity,
              currency: data.eventData.checkout.prices.vendor.currency
            })
            this.$ga.event('Ecommerce', 'checkout')
```

### Expected behavior

After successful purchase see checkout value in Google Analytics and conversion to be bigger than 0%. I did a purchase myself and no luck.

### Actual behavior

Data is not on Google Analytics.

### Environment

Run this command in the project folder and fill in their results:

`npm ls vue-analytics`:
frontend@0.1.0 /Users/janswist/Developer/project/frontend
└── vue-analytics@5.22.1  

Then, specify:

1. Operating system: MacOs HighSierra
2. Browser and version: latest Chrome (just updated)

**Comment by MatteoGabriele** [comment]
not sure but, looking at the Google Analytics documentation, looks like after these operations you need to explicitly send an `ecommerce:send` action as here specified https://developers.google.com/analytics/devguides/collection/analyticsjs/ecommerce#sendingData

so after all your events you might need to add a `this.$ga.ecommerce.send()`

**Comment by janswist** [comment]
Sorry for late answer. This is what I get:

![image](https://user-images.githubusercontent.com/5583954/98448641-c3f83280-212d-11eb-8272-12b3404a8ad8.png)

Even though I can see `send` function in ecommerce object:
![image](https://user-images.githubusercontent.com/5583954/98448671-00c42980-212e-11eb-943d-331cd35ec3fe.png)

**Comment by MatteoGabriele** [comment]
can you show me your installation snippet?

**Comment by janswist** [comment]
Sure, here it is:
![image](https://user-images.githubusercontent.com/5583954/98449970-be541a00-2138-11eb-8c1d-7ef0045139d4.png)

**Comment by janswist** [comment]
@MatteoGabriele ping in case it went unnoticed :)

**Comment by janswist** [comment]
I made a little inspection and seems like it could have more to do with GA itself than `vue-analytics` plugin:
![image](https://user-images.githubusercontent.com/5583954/98848929-bce56300-2452-11eb-90ed-5b710c6e988f.png)

Seems like when `ecommerce: { enhanced: true }` it loads only Enhanced Ecommerce methods via `ec.js`, but not the basic ones. When it's turned off then it loads then the basic one `ecommerce.js` gets loaded:
![image](https://user-images.githubusercontent.com/5583954/98849359-60367800-2453-11eb-84cf-ce12e39a6f86.png)

But that actually wasn't the reason why it didn't work. It was me not paying attention to [GA docs](https://developers.google.com/analytics/devguides/collection/analyticsjs/ecommerce#addTrans). This is how it should've looked like from the beginning:
```js
     this.$ga.ecommerce.addTransaction({
        id:       eventData.checkout.id,    // Transaction ID. Required.
        revenue:  eventData.checkout.prices.vendor.total,
        tax:      eventData.checkout.prices.vendor.total_tax,
        currency: eventData.checkout.prices.vendor.currency
      })
      this.$ga.ecommerce.send()
```

So, my problem is solved as for my needs. Would love to hear about that plugin behavior though - is it how it's supposed to work?

**Comment by MatteoGabriele** [comment]
Oh thanks! Sorry had a lot to work and forgot to check in. Thanks for your debugging
