### ISSUE TITLE
No data in Google Analytics after 4 days .

### ISSUE THREAD

**Issue by didiosn** [MatteoGabriele/vue-analytics#294]
Hi, I've add vue-analytics in my project but still got no data at all. The new tracking id is not in UA-***** format. Is that the problem ?

**Comment by didiosn** [comment]
It was a mistake with the tracking ID. But now I'm facing the : "Maximum call stack size exceeded" error. Just can't find the problem.

**Comment by MatteoGabriele** [comment]
Yes, this package doesn't support v4. For that you would have to use vue-gtag

**Comment by didiosn** [comment]
All right. Let me try it.

**Comment by didiosn** [comment]
Still not working. I'm facing a **Maximum call stack size exceeded** error.

**Comment by didiosn** [comment]
I fixed it. To recap, install Vue-gtag instead of vue-analytics when using Google Analytics V4. Then add the router as the third parameter in the initialization.

Bad implementation : 

`Vue.use(VueAnalytics, {
    id: 'G-******',
    router
});`

Good one 

`Vue.use(
        VueAnalytics,
        {
            id: 'G-******'
        },
        router);`

**Comment by KappaLambda** [comment]
> I fixed it. To recap, install Vue-gtag instead of vue-analytics when using Google Analytics V4. Then add the router as the third parameter in the initialization.
> 
> Bad implementation :
> 
> `Vue.use(VueAnalytics, { id: 'G-******', router });`
> 
> Good one
> 
> `Vue.use( VueAnalytics, { id: 'G-******' }, router);`

This answer confused me a little bit. I use the GA4. So do I need vue-analytics or vue-gtag. You mention that you installed vue-gtag instead of vue-analytics but your example below still uses vue analytics and not vue-gtag.

Here is an example from Vue Gtag documentation.

```vue
......

Vue.use(VueGtag, {
  config: { id: "UA-1234567-1" }
}, router);

......
```
