### ISSUE TITLE
Google Analytics 4

### ISSUE THREAD

**Issue by mimar19** [MatteoGabriele/vue-analytics#298]
Is it currently working with GA4 and the new measurement ID, if not, will it be adapted for it?

**Comment by acuD1** [comment]
I tested with GA4, it doesn't seems to work.

**Comment by MatteoGabriele** [comment]
no, you have to switch from analytics.js to gtag.js so I would suggest something like vue-gtag or another package that uses gtag.js which is the new Google Analytics standard script

**Comment by carlitoscarrara** [comment]
Hello Matteo,
I think it would help a lot if you post the info of the last comment on the main readme.

PS: thanks for your libraries. They are very helpful!

**Comment by MatteoGabriele** [comment]
I'll put a note in the Readme file, thanks
