### ISSUE TITLE
ga.disable() and ga.enable() are not working

### ISSUE THREAD

**Issue by seanggani** [MatteoGabriele/vue-analytics#301]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description

Hello there, I initialized Vue analytics with disabled: true and in the effort to be compliant with GDPR, want to invoke ga.enable() once the user gives consent. To test this out, I tried putting a $ga.event("Hi") right after the enable, and I see that the event is not being triggered. I'm using vue-analytics@5.22.1 

### Expected behavior

Enabling Ga during runtime should work

### Actual behavior

Enabling Ga during runtime doesn't work

### Environment

Run this command in the project folder and fill in their results:

`npm ls vue-analytics`: 

Then, specify:

1. Operating system: Mac OS Big Sur
2. Browser and version: Google Chrome

### Reproducible Demo

Please take the time to create a new app that reproduces the issue or at least some code example

Demonstrable issues gets fixed faster.

**Comment by gudirut** [comment]
Hey, I faced the same issue and switched to the maintained rep of MatteoGabriele: https://github.com/MatteoGabriele/vue-gtag

Here, enable and disabale works on the fly!

**Comment by josephkobti** [comment]
vue-gtag requires Vue ^3.0.0, any solution that works with Vue 2?

**Comment by YanDevDe** [comment]
This issue is still there. It should have high priority.
