### ISSUE TITLE
GA instrumentation won't work. What am I missing?

### ISSUE THREAD

**Issue by ilmoi** [MatteoGabriele/vue-analytics#302]
I've read previous answers and re-read the guidelines multiple times, and I can't find a mistake in my code. For some reason GA doesn't instantiate.

My router/index.js:
```
import Vue from 'vue'
import VueRouter from 'vue-router'
import Feed from '../views/Feed'
import About from '../views/About'
import Tip from '../views/Tip'

Vue.use(VueRouter)

const routes = [
  {
    path: '/',
    name: 'feed',
    component: Feed
  },
  {
    path: '/about',
    name: 'about',
    component: About
  },
  {
    path: '/tip',
    name: 'tip the dev',
    component: Tip
  }
]

const router = new VueRouter({
  mode: 'history',
  routes
})

export default router
```

And main.js:
```
import Vue from 'vue'
import App from './App.vue'
import router from './router'
import './index.css'
import InfiniteLoading from "vue-infinite-loading";
import VueAnalytics from "vue-analytics";
import {store} from '@/store/store'

Vue.config.productionTip = false
Vue.use(InfiniteLoading)
Vue.use(VueAnalytics, {
  id: 'G-HPLNHBX0YK',
  router
})

new Vue({
  router,
  store,
  render: function (h) { return h(App) }
}).$mount('#app')
```

Can someone help me spot an error?

And just to be clear - the above alone should be enough to start tracking pageviews, or do I also need to add tracking code to each page separately?

**Comment by MatteoGabriele** [comment]
All looks okay from the snippet, but I notice that the ID passed does not have the typical analytics format: what is it?
usually, it starts with `UA-`, your is `G-`

**Comment by ilmoi** [comment]
So it seems the problem has to do with Google Analytics 4 - the new version of GA. With GA4 they don't give you a `UA-` code anymore and instead they give you a `G-` code. You need to go through advanced options [as explained here](https://support.google.com/analytics/answer/10269537) to setup the old GA and get a `UA-` code.

With UA code everything seems to work fine. Hope helps anyone with a similar problem in the future.

**Comment by MatteoGabriele** [comment]
If u need ga4, u probably should switch to 'vue-gtag' package

**Comment by MatteoGabriele** [comment]
I will close this ticket since the issue seems to be in analytics itself, more than in the plugin.
