### ISSUE TITLE
feature request: delay page auto tracking

### ISSUE THREAD

**Issue by marktheis** [MatteoGabriele/vue-analytics#32]
Hi. When using the page auto tracking feature, it would nice if you could delay the page tracking on each route.

Reason:
If I set `document.title` on my `created` hook, vue-analytics uses the old title instead of the new title I just set. If I could delay vue-analytics by x ms, It'll pick up the new title I think.

Or is there a better way to achieve this?

And great plugin btw :)

**Comment by MatteoGabriele** [comment]
hi @marktheis if you are using the auto-tracking is not using `document.title` but the `name` property on your route.

currently if you need custom page tracking you need to go with the manual way like 

i.e. your component
```js
export default {
 name: 'my-component'
 mounted () {
   this.$ga.page({
     path: '/whatever-page',
     title: document.title,
     location: window.location.href
   }) 
 }
}
```

**Comment by MatteoGabriele** [comment]
I can maybe look at how to customize more the auto-tracking with a proxy object, I'll have a look :) in the meantime let me know if that code helps you

**Comment by marktheis** [comment]
Ohh. I thought it was using document.title because I think it uses that **only** on initial load. I see now it uses the name property otherwise. Thanks.

Okay so this really isn't a problem for me then. You can close it for my sake. I can't see any other use for it.

**Comment by MatteoGabriele** [comment]
ah ok! I thought you had some sort of reasons to use the `document.title`, maybe for Server Side Rendering

**Comment by MatteoGabriele** [comment]
I will still going to add a feature for a better customization of the auto-tracking :)

thanks for your feedback

**Comment by seanwash** [comment]
I see that we now have the option of using `autoTracking.pageviewTemplate()` to track custom data like `document.title`, but I'm noticing the same issue as the first comment - I'm using this in conjunction with a nuxt.js plugin, and occasionally the title tracked refers to the previous page's title. I assume that's because the autotrack happens before `head()` runs and `$metaInfo` is updated.

Is the proper way/a work around still to manually trigger a view on mount with `this.$ga.page()`?

**Comment by MatteoGabriele** [comment]
Unfortunately this happens only using Nuxt, so far, so for me it's not really possible to adjust it because it is a bug within a specific framework.
If there's a place in Nuxt where all the routing happens correctly you can just use the manual page tracking there or use it on mounted of the page.

**Comment by seanwash** [comment]
No worries!

It seems like for me (and possibly other nuxt users) that the solution is to turn off auto page tracking and use `this.$ga.page()` in the mounted hook. I made a simple mixin and tossed it into each component inside `/pages`. Works like a charm!
