### ISSUE TITLE
VueAnalytics Error Handling

### ISSUE THREAD

**Issue by mikereinhold** [MatteoGabriele/vue-analytics#33]
### Description

There are a variety of scenarios in which Google Analytics may fail to execute properly for a user on a site (Google Analytics API issue, user browser blocking analytics code, organization or vpn provider blocking analytics code, etc).

Though these scenarios don't occur very often, when they do occur it will cause the currently running portion of the Vue application to fail. Example, if using the User Timing function to measure API call timing from the browser, the API Promise then function will first mo the measurement and the Analytics call then process the returned data. An uncaught exception due to Google Analytics being unavailable seriously impacts the Vue application. 

Preventing this inside the application requires a significant amount of boilerplate for every Analytics call; it would be much preferable if VueAnalytics did not allow an exception to be thrown and handled the error differently. 

Exactly how... not sure 😅 VueAnalytics already warns if Google Analytics is not properly loaded, so maybe just swallowing the error is acceptable.

### Expected behavior

Vue-Analytics should not allow any uncaught exceptions related to Google Analytics not being available

### Actual behavior

Uncaught Error for the VueAnalytics function attempting to call (whether page or event or time, etc).

### Environment
1. `npm ls vue-analytics`: vue-analytics@4.1.0
2. `node -v`: v4.2.4
3. `npm -v`: 4.1.1

Then, specify:

1. Operating system: Windows 10 x64 1703
2. Browser and version: Chrome 57.0.2987.133 (64-bit)

### Reproducible Demo

Any VueAnalytics app can be forced to demonstrate this behavior when using the [Block Yourself From Analytics Chrome Extension](https://chrome.google.com/webstore/detail/block-yourself-from-analy/fadgflmigmogfionelcpalhohefbnehm?hl=en)

**Comment by MatteoGabriele** [comment]
hey thanks for your feedback again. 
not really sure on how to achieve this error handling that your talking about. 

do you have an example on how you would handle that "manually" right now? 

i will try to install this plugin and see what i can do :)

**Comment by MatteoGabriele** [comment]
I looked at what actually the blocker is doing and it is only blocking http requests and I have no access to them: the script will never go in my try/catch. 

The only request i can handle is the script loading part, but I'm already taking care of that one.

For now i can't do anything, sorry.

If you find a way let me know 
Thanks again for you feedback :)

**Comment by mikereinhold** [comment]
@MatteoGabriele - I did some more digging on this... The problem was that I was wrapping up all my analytics needs into a single set of exports, including trying to merge Vue.$ga into my export during onReady. This worked fine when Google Analytics properly loads, but onReady never fires when the analytics script is blocked... Leaving the functions that should be exported from Vue.$ga as undefined. 

If I use Vue.$ga directly, the errors don't cause the Vue app to break. I hadn't wanted to do it that way because I wanted to keep the analytics exports together with the analytics utility functions that I was exporting also. 

Anyway, this isn't a Vue-Analytics bug in any case, so it makes sense to close it. Thanks!

**Comment by MatteoGabriele** [comment]
no problems! 

thanks again for your feedback and have a nice day!
