### ISSUE TITLE
GA tag placement

### ISSUE THREAD

**Issue by wcarron27** [MatteoGabriele/vue-analytics#34]
Don't know where elst to ask this: But, I'm getting and Error from the Google Tag manager informing me of "A Non-Standard Implementation". It says that it's detecting the Script requests, but cannot locate the script in the web page. Do I need to place the plain google analytics script in the index.html for it to work properly?

**Comment by MatteoGabriele** [comment]
Hi @wcarron27 could you please add some more information? like the entire error, some screenshots? 

thanks :)

**Comment by wcarron27** [comment]
I will tonight once I am home from work, thank you.

**Comment by MatteoGabriele** [comment]
i will close this ticket for inactivity. you can open it again if you still have the issue

**Comment by DaxChen** [comment]
I got this same warning, but I think it's okay?
The warning is from Google's [Tag Assistant Chrome extension](https://chrome.google.com/webstore/detail/tag-assistant-by-google/kejbdjndbnbjgmefkgdddjlbokphdefk)

The associated explanation is here: [Non-standard implementation](https://support.google.com/tagassistant/answer/3207128?ref_topic=2947092#nonstandard

@MatteoGabriele  This is really okay, right? 😃
