### ISSUE TITLE
tracked page load ga.js which spends more time, why not to use local js file from your vue-analytics modeule?

### ISSUE THREAD

**Issue by KeeepMoving** [MatteoGabriele/vue-analytics#35]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description

What are you reporting?

### Expected behavior

Tell us what you think should happen.

### Actual behavior

Tell us what actually happens.

### Environment

Run these commands in the project folder and fill in their results:

1. `npm ls vue-analytics`: 
2. `node -v`: 
3. `npm -v`:

Then, specify:

1. Operating system:
2. Browser and version:

### Reproducible Demo

Please take the time to create a new app that reproduces the issue or at least some code example

Demonstrable issues gets fixed faster.

**Comment by MatteoGabriele** [comment]
Besides the fact that you just skipped the entire issue template and wrote only a huge title, adding the analytics file directly in the npm package  means that you are going to bundle the entire library in your application file which will take even more time to load.

**Comment by KeeepMoving** [comment]
sorry about that :)
