### ISSUE TITLE
Add support for/expose _setReferrerOverride

### ISSUE THREAD

**Issue by officert** [MatteoGabriele/vue-analytics#36]
I need to override GA's referrer by using `window.ga.push(['_setReferrerOverride', document.referrer]);`

I looked through the code and the custom methods docs but don't see anything that exposes this.

Would it be possible to add?

**Comment by MatteoGabriele** [comment]
sure thing! thanks for the suggestion :)

**Comment by MatteoGabriele** [comment]
@officert apparently the `push` method doesn't exist anymore. It's a method from the ga.js libarry not for the new analytics.js. Are you sure you can't achieve what you need in another way?

**Comment by MatteoGabriele** [comment]
Ok I think i got it!

You need to set a field so you can just you the `set` method like so

```js
this.$ga.set('referrer', 'http://example.com')
```
this is a reference to the api https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#referrer

let me know if works! :)
