### ISSUE TITLE
pageviewTemplate is only called once on page load, not when route changes

### ISSUE THREAD

**Issue by zsalzbank** [MatteoGabriele/vue-analytics#38]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description

When auto-tracking is enabled, and a `pageviewTemplate` is supplied, the callback is only called on the initial route.

### Expected behavior

I would expect it to be called on each route change, so the parameters passed to the tracker can be dynamic based on the route.

### Actual behavior

The callback is only called on the initial route.

### Environment

Run these commands in the project folder and fill in their results:

1. `npm ls vue-analytics`: vue-analytics@4.1.1 
2. `node -v`: v6.10.2
3. `npm -v`: 3.10.10

Then, specify:

1. Operating system: Ubuntu 16.04
2. Browser and version: Electron v1.6.6

### Reproducible Demo

https://github.com/zsalzbank/vue-analytics-pageview-template

When you load the page, you will see a message in the console that says `getting pageview params on /`. When you click on any of the links, you do not see a corresponding message.

**Comment by MatteoGabriele** [comment]
Hi @zsalzbank 
Thanks a lot for your issue and the example! 

Fixed it with vue-analytics@4.1.2

Let me know if everything works

**Comment by zsalzbank** [comment]
Works! Thanks for the quick turnaround!
