### ISSUE TITLE
require does'not work

### ISSUE THREAD

**Issue by Baozi2** [MatteoGabriele/vue-analytics#39]
when I use
```
mounted(){
	this.$ga.require('ec');
}
```
but it  does not require ec.js。
I find that when i use **this.$ga.require('ec')** this time the google analyticsjs.js does' not 
loaded,so  window.ga is undefined

### Environment
vue-analytics@4.1.2
node -v6.2.1
npm -3.9.3
Mac 
chrome
Then, specify:

**Comment by MatteoGabriele** [comment]
hi @Baozi2 
this issue is because `mounted` doesn't mean that the google analytics script is loaded, they are two different things.

Do you need to add that plugin only when a specific page is mounted? otherwise you can just add it in the `onReady` method in the configuration object

```js
Vue.use(VueAnalytics, {
  id: 'UA-12345678-1',
  onReady () {
    Vue.$ga.require('ec')
  }
})
```

**Comment by Baozi2** [comment]
get  it，thx


发自网易邮箱大师
On 05/17/2017 19:37, Matteo Gabriele wrote:

hi @Baozi2
this issue is because mounted doesn't mean that the google analytics script is loaded, they are two different things.

Do you need to add that plugin only when a specific page is mounted? otherwise you can just add it in the onReady method in the configuration object

Vue.use(VueAnalytics, {
  id:'UA-12345678-1',
  onReady () {
    Vue.$ga.require('ec')
  }
})

**Comment by duxinxiao** [comment]
I think it's better to list in document
