### ISSUE TITLE
Triple pageview fire on initial pageload

### ISSUE THREAD

**Issue by jamiecarter7** [MatteoGabriele/vue-analytics#41]
### Description

I am getting a triple pageview fire on the initial load of the website.

From this point browsing the site seems to fire the correct amount of views

### Expected behaviour

It should fire once

### Actual behaviour

<img width="1035" alt="screenshot 2017-06-05 01 59 51" src="https://cloud.githubusercontent.com/assets/9541902/26804301/608e30c8-4a3f-11e7-9676-1a1d1768772f.png">

This is most likely going to be a code error on my part as Vue is my first JS framework. It may be something to do with the changing of the title and the path during the load process

### Environment

Run these commands in the project folder and fill in their results:

1. `npm ls vue-analytics`: 
pg@1.0.0 /Applications/XAMPP/xamppfiles/htdocs/pg
└── vue-analytics@2.4.0

2. `node -v`: 
v4.4.7

3. `npm -v`:
4.0.5

Then, specify:

1. Operating system:
macOS Sierra

2. Browser and version:
chrome - Version 58.0.3029.110

**Comment by MatteoGabriele** [comment]
hi @jamiecarter7 

could you please create a public repo with the issue replicated so I can debug it better?
I currently don't see this issue

Usually the application dispatches 2 events:
- runs the `ga("set", "page", "/")` command to change the page context
- runs the `ga("send", "pageview", {page: "/", title: "home", location: "http://localhost:8080/"})` for actually tracking the current page

this problem might also be related on your router setup because the auto-tracking relies on the `router.afterEach` hook: if you accidentally are doing some redirect or triggering a page twice, that one will be registered.

**Comment by MatteoGabriele** [comment]
I also suggest you to update your package to the latest version, since lot of improvements, bug fix and features are implemented in the newest version 4 :)

**Comment by MatteoGabriele** [comment]
I see that in version 2.4 that you have, there's still an extra `pageview` hit send it, but it is already fixed.
I also see two different routes in your console, so you are probably redirecting from the home page to something else.

**Comment by jamiecarter7** [comment]
Thanks for the reply!

I updated to the newest version which reduced the initial pageview to 2. I then removed the initial page view load which leaves it to just one pageview on intital load and then it tracks views from there. 

I knew it would be something on my route, I am still unsure what but its tracking the site correctly now! Thanks for the great package!

Closing issue

**Comment by MatteoGabriele** [comment]
no problem! 
glad that it works :)

**Comment by jamiecarter7** [comment]
I've implemented this onto the site and I've found that i think it was an error with our development version of the site. I turned the pageload: false and found on the live site it didnt fire with the user first landed!. 

It seems all is working well its just a localhost issue.

Thanks!

**Comment by dio5** [comment]
So, we seem to have a very similar issue with the latest version.
In dev mode, both the first load track and the afterEach next tick track are called.
Compiled however, it only tracks once... but there is one page type where it does track trigger both the initial load and the afterEach... I'm not sure yet what is the correct behavior with this module.
