### ISSUE TITLE
Can we setup a custom "url" for a page?

### ISSUE THREAD

**Issue by Cosbgn** [MatteoGabriele/vue-analytics#43]
Hi, 

Thanks for this plugin, is great. My question is:

I have a django app which will render a static html page if the user in not authenticated at the root domain (e.g. site.com), If the user is authenticated it will load a vue single page app where I use your plugin, all routes are tracked correctly except of home which looks like (site.com/#/). 

Google Analytics will correctly think that this page is the same as the static site.com page, but in reality is completely different.

Is there a way to send a custom page view, for example '/single-page-home' and deactivate page views for ('/') **only** on this url path? 
So that I can track the two pages with the same url in Google Analytics while keeping the url's the same (e.g. / and /#/). 

Thanks

**Comment by MatteoGabriele** [comment]
Hi @Cosbgn 
If I understood correctly you just want to get rid of the automatic track of a certain page and do it yourself.
If so the only thing you need is to set the filter for the route you don't want to track using the `ignoreRoute` property. check documentation [here](https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/page-tracking.md#ignore-routes-on-page-auto-tracking) 

and then you can simply manually track your pages using the instance of vue-analytics in your component. check documentation [here](https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/page-tracking.md#page-tracking)

let me know if it helps

**Comment by MatteoGabriele** [comment]
i will close this issue, but feel free to open it again if you still have problems
