### ISSUE TITLE
PageView location is incorrect

### ISSUE THREAD

**Issue by nchutchind** [MatteoGabriele/vue-analytics#44]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description

When tracking pageView automatically using the VueRouter and default settings, the location is the previous page rather than the page being navigated to.

### Expected behavior

If navigating from localhost/A to localhost/B, I would expect the pageView tracking to have a "page" of "/B" and a "location" of "http://localhost/B".

### Actual behavior

Instead, I see a "page" of "/B" and a "location" of "http://localhost/A".

### Environment

Run these commands in the project folder and fill in their results:

1. `npm ls vue-analytics`: `-- vue-analytics@4.1.2
2. `node -v`: v8.1.4
3. `npm -v`: 5.2.0

Then, specify:

1. Operating system: Windows 10
2. Browser and version: Chrome 59

### Reproducible Demo

Please take the time to create a new app that reproduces the issue or at least some code example

Demonstrable issues gets fixed faster.

**Comment by MatteoGabriele** [comment]
@nchutchind  Thanks a lot for your feedback!!
