### ISSUE TITLE
Track outbound links with vue-analytics?

### ISSUE THREAD

**Issue by patrickbolle** [MatteoGabriele/vue-analytics#47]
Hi! Love the plugin, been working perfectly on my site so far - www.travelcurated.com

I'm trying to track outbound links and am having troubles.

I've been trying to use the Custom Methods page in the docs for this : this.$ga.query(...)

My code is - 
`  <a :href="url" target="_blank" v-on:click="outboundClick()">Visit Site</a>`

`outboundClick: function() {
      this.$ga.query('send', 'event', 'outbound', 'click', this.tcURL, {
        'transport': 'beacon',
        'hitCallback': function(){console.log('out')}
      })
    },
`

Not getting any events in my Analytics. Any ideas here?

Thanks!

**Comment by MatteoGabriele** [comment]
hi @patrickbolle 
thanks for your feedback :)

I'm sorry but I tried and for me works: I click the anchor tag and the `hitCallback` callback is successfully fired before leaving the page.

```js
this.$ga.query('send', 'event', 'outbound', 'click', '/foo/bar', {
   transport: 'beacon',
   hitCallback () {
     debugger
   }
})
```
if your application goes in the debugger, then I can't do much I guess. 

Take in mind that `this.$ga.query` it's just the plain `ga` instance of Google Analytics and it works when features like this are not covered by the plugin because its huge API.

Might be useful to create a repository with your example not working.

**Comment by MatteoGabriele** [comment]
Might be because that you're actually using the default behavior of the anchor tag and the javascript part doesn't have time to fire the event.

try this 

```html
<a href="foo/bar" @click.prevent="trackOutbound">Click me</
```

```js
export default {
  methods: {
     trackOutbound () {
        const url = '/foo/bar'
        this.$ga.query('send', 'event', 'outbound', 'click', url, {
            transport: 'beacon',
            hitCallback () {
               document.location = url
            }
        })
     }
  }
} 
```

**Comment by patrickbolle** [comment]
Ahhh that could be it @MatteoGabriele 

Now my issue with that is -- I need the link to open in a new tab. And looks like that isn't possible to do properly with JS (without it looking like a pop up).

Will try this and let you know though, thanks!!

**Comment by MatteoGabriele** [comment]
Sure! :)
For now, since this is not an issue of the plug-in itself, I will close it. Feel free to open it again if you need so.

**Comment by rominf** [comment]
@MatteoGabriele, I need to track outbound links too. What do you think about moving the code from your comment to the codebase?
