### ISSUE TITLE
Feature Request for cross-domain tracking

### ISSUE THREAD

**Issue by HAKASHUN** [MatteoGabriele/vue-analytics#48]
### Description

Feature Request for cross-domain tracking

### Expected behavior

- set allowLinker option
- add codes to use linker

```javascript
ga('create', 'UA-XXXXXXX-Y', 'auto', {'allowLinker': true});
ga('require', 'linker');
ga('linker:autoLink', ['example-2.com'] );
```
https://support.google.com/analytics/answer/1034342?hl=en

### Actual behavior

There is no way to track cross-domain with this library.

### Environment

Run these commands in the project folder and fill in their results:

1. `npm ls vue-analytics`: vue-analytics@4.1.3
2. `node -v`: v6.10.1
3. `npm -v`: 3.10.10

Then, specify:

1. Operating system: Mac 10.11.5
2. Browser and version: Google Chrome  60.0.3112.78

### My Idea

```
Vue.use(VueAnalytics, {
  id: env.GOOGLE_ANALYTICS,
  autoLink: ['example-2.com'],
  router
})
```

https://github.com/HAKASHUN/vue-analytics/commit/a435f12734b5b86c5cc9d34b0f24ea9ebb9cdbf7

**Comment by HAKASHUN** [comment]
Thanks! 💯

**Comment by MatteoGabriele** [comment]
thanks for your feedback :) 

you can find the documentation here https://matteogabriele.gitbooks.io/vue-analytics/content/cross-domain-tracking.html

**Comment by dontlemmedown** [comment]
> ga('create', 'UA-XXXXXXX-Y', 'auto', `{'allowLinker': true}`);

Is it possible to set `allowLinker`?
When i set `linkers: []` ga created without autolinker flag

`Running command: ga("create", "UA-XXXX-1", "auto", {})`

**Comment by liqueflies** [comment]
Hello, why have you removed the check for adding "allowLinker"?

https://github.com/MatteoGabriele/vue-analytics/blob/cf1bde0f71806acfed9e75659858671c9ac0716c/src/create-trackers.js#L29

Thank you!
