### ISSUE TITLE
File page.js page function has a serious bug

### ISSUE THREAD

**Issue by bigbanana** [MatteoGabriele/vue-analytics#49]
File page.js page function has a serious bug, when the implementation of **npm run build**, because **UglifyJsPlugin**, **VueRouter** class constructor.name not _VueRouter_ string, so **getDataFromRouter** method will not be implemented, resulting in statistical error , Hope to quickly solve, thank you!

**Comment by MatteoGabriele** [comment]
Thanks for your feedback. 
I made a reproduction of the error myself but please next time take time to fill the template issue that I made: is there for a reason.
The issue template helps me to understand better the issue and fix it as quick as possible: if you just type your thoughts without a reference to the actual problem, makes everything more long to me to process.

Thanks :)

**Comment by MatteoGabriele** [comment]
@bigbanana bug fixed on 4.2.2

thanks again
