### ISSUE TITLE
How does one set a Google Analytics ID without `loadScript`?

### ISSUE THREAD

**Issue by jdrydn** [MatteoGabriele/vue-analytics#5]
```
import Vue from 'vue'
import VueAnalytics, { loadScript } from 'vue-analytics'

Vue.use(VueAnalytics,)

loadScript('UA-XXX-N')
```

If you don't call `loadScript`, how should I be setting the GA-ID? Or am I missing something?

**Comment by MatteoGabriele** [comment]
Usually Google Analytics provides you a little snippet which loads a script file and initialize your session using your Google Analytics domain ID.
The ID is provided by Google Analytics after you create the account for that specific domain.

The `loadScript` method just injects that script for you in the DOM, but you still have to pass your ID.

**Comment by jdrydn** [comment]
Ah, so I still need the GA script along with this module! Great thank you.

**Comment by MatteoGabriele** [comment]
No, you can use `loadScript` and pass the Google Analytics ID, or skip `loadScript` and add GA script and the ID manually in the body of your html page.

The only difference is that you don't have to touch your html page and `loadScript` returns a Promise, so you have a callback when the script is loaded.
