### ISSUE TITLE
Doesn't work within Cordova

### ISSUE THREAD

**Issue by asifkilwani** [MatteoGabriele/vue-analytics#50]
I am using vue-analytics within cordova. App runs on localhost, works well with analytics but when app install and run from play/app store, it doesn't show any results in analytics report?

**Comment by MatteoGabriele** [comment]
![1tx3ru](https://user-images.githubusercontent.com/5337152/29214248-df76e0ba-7ea6-11e7-8d7c-9bf5951bd37a.jpg)

**Comment by MatteoGabriele** [comment]
I don't ask for an entire application reproduction, but at least the vue-analytics configuration object and the version used. 

thanks :)

**Comment by asifkilwani** [comment]
Hi, 

My current vue-analytics version is 4.2.2 and below is the configuration

`Vue.use(VueAnalytics, {
  id: 'UA-100213456-1',
  linkers: ['afripods.com', 'example2.com'],
  debug: {
    enabled: true,
    trace: false,
    sendHitTask: true
  }  
})`

here is the debug there
`Running command: ga("send", "pageview", {page: "/discover_trending", title: "Explore > Trending", location: ""})
Unallowed document protocol. Aborting hit.`

**Comment by MatteoGabriele** [comment]
I personally don't work with Cordova, so I have no clue about its environment.
Does Cordova provides a `window.location.href`  ?

**Comment by asifkilwani** [comment]
yeah but it's running on file:/// protocol. 

I found a solution over the internet but don't know how to implement below with vue analytics config

`ga('create', 'UA-**********-6', {'cookieDomain': 'none'});
ga('set', 'checkProtocolTask', function(){ /* nothing */ });`

**Comment by MatteoGabriele** [comment]
As it is now, you can't add any options in the 'create' call, but I can actual fix that: it's nice to inject whatever you like in the initialization of analytics.

for the other one you can simply use `this.$ga.set('checkProtocolTask', function () {})`

**Comment by MatteoGabriele** [comment]
I've created a ticket for the options ( see #52 )

**Comment by MatteoGabriele** [comment]
@asifkilwani does the `ga.set` fix your problem or you're waiting for the other ticket to be fixed?
if so I can close this and live the other one open.

Let me know. thanks!

**Comment by asifkilwani** [comment]
Yes, below code solved the issue.

`this.$ga.set('checkProtocolTask', null); 
this.$ga.set('checkStorageTask', null); 
this.$ga.set('historyImportTask', null); `

**Comment by MatteoGabriele** [comment]
ok perfect. I'll close this one then.

I will add the option functionality asap, in the meantime I'm glad that you're not stuck!

thanks for your feedback again! :)

**Comment by Mouvedia** [comment]
@MatteoGabriele I need `'cookieDomain': 'none'`. Should I drop vue-analytics or is there a quick fix ?

**Comment by MatteoGabriele** [comment]
@Mouvedia you could use vue-analytics@5.0.0-beta.3 ( or vue-analytics@next ) where you can add endless properties to the create call. For now version 4 doesn't support that I'm sorry.

Version 5 tho it's stable enough, currently working on unit testing :)
It's up to you

**Comment by MatteoGabriele** [comment]
with the 5 beta you should write something like this

```js
import Vue from 'vue'
import VueAnalytics from 'vue-analytics'

Vue.use(VueAnalytics, {
  id: 'ua-12345-6',
  fields: {
    cookieDomain: 'none'
  }
})
```

**Comment by Mouvedia** [comment]
> In addition, if analytics.js detects that you’re running a server locally (e.g. localhost) it automatically sets the cookieDomain to ‘none’.

**Comment by MatteoGabriele** [comment]
@Mouvedia what's this?

**Comment by MatteoGabriele** [comment]
@Mouvedia you should explain what you need instead of pasting random links and text.
An issue on Github is not a rebus

**Comment by TDola** [comment]
Is there a way to set the client ID on create like shown in the example in the link above?
```

var GA_LOCAL_STORAGE_KEY = 'ga:clientId';

if (window.localStorage) {
  ga('create', 'UA-XXXXX-Y', {
    'storage': 'none',
    'clientId': localStorage.getItem(GA_LOCAL_STORAGE_KEY)
  });
  ga(function(tracker) {
    localStorage.setItem(GA_LOCAL_STORAGE_KEY, tracker.get('clientId'));
  });
}
else {
  ga('create', 'UA-XXXXX-Y', 'auto');
}
```
