### ISSUE TITLE
Time to refactor! ( v5.0.0 )

### ISSUE THREAD

**Issue by MatteoGabriele** [MatteoGabriele/vue-analytics#54]
- [x] refactor the plugin code structure
- [x] implement semantic release
- [x] implement unit testing
- [x] add support for SSR

**Comment by cjblomqvist** [comment]
I'm a little bit skeptical of the way SSR is implemented (https://github.com/MatteoGabriele/vue-analytics/commit/346f648d56db48ff7ea13633f095276be6603c1f). If you want to do a proper SSR solution, you will need to be able to cope with the router being created per request (see https://ssr.vuejs.org/en/data.html for this pattern). Preferably, everything is run based on a lifecycle hook that gets triggered client side, and you can access the vue-analytics instance in that lifecycle hook or something (maybe the whole plugin should be a component mixin or something instead?).

**Comment by MatteoGabriele** [comment]
Hi @cjblomqvist 
Well I need to access `window` and `document` objects, and they are both not available server side so I just don't track until the client is ready.

I only make the check so that your application doesn't break, as soon as it boots up it should start tracking.
You can even install the plugin on the `mounted` hook of your main application component if you needs so.

I will see if I can find some more robust way of being SSR friendly, but so far this works in my projects as well.

If you have some ideas on how could work better, please drop a PR, I would love to add it :)

**Comment by MatteoGabriele** [comment]
see #59

**Comment by cjblomqvist** [comment]
It seems like you are most correct actually - sorry for bothering you with non-issues! :-) Great plugin!
