### ISSUE TITLE
Single page without vue-router

### ISSUE THREAD

**Issue by ebisbe** [MatteoGabriele/vue-analytics#55]
If I want to trigger the page vie using this plugin without the router because I'm using a super simple web page. Where should I put the 
```
this.$ga.page('/')
```

At the moment I have put it in the App.vue created() event.

```
export default {
    name: 'app',
    components: {
      Contact, Gallery
    },
    mounted () {
      this.$ga.page('/')
    }
  }
```

 But it is not triggering at all.

**Comment by MatteoGabriele** [comment]
I'm working on a new update where I store all events triggered before analytics is ready and them fire them later on, but for now you should mount your application when the onScriptLoaded promise is resolved. Mounted or created doesn't matter.

```js
VueAnalytics.onScriptLoaded().then(() => {
  App.$mount('#app')
})
```
