### ISSUE TITLE
"Document is not defined" with SSR

### ISSUE THREAD

**Issue by HeuHax** [MatteoGabriele/vue-analytics#56]
Using server side rendering throws error: document is not defined.

Anything special i need to do to make this work?

    Vue.use(VueAnalytics, {
        id: 'UA-*******',
        router
    });

**Comment by MatteoGabriele** [comment]
which version are you using?

**Comment by HeuHax** [comment]
vue: 2.4.2
vue-router:  2.7.0
vue-analytics: 4.3.1

**Comment by MatteoGabriele** [comment]
I will make a check for `window` and `document`. If you are in a hurry, you might want to install the plugin when client side is ready

**Comment by HeuHax** [comment]
Not sure how to install it when client side is ready. Got a quick example ?

**Comment by MatteoGabriele** [comment]
The moment you know your app is mounted client side, is when `mounted` is triggered: add the installation at `mounted` of your main application

Something like this

```js
import Vue from 'vue'
import router from 'path/to/router'
import App from 'path/to/app.vue'
import VueAnalytics from 'vue-analytics'

const app = new Vue({
    router,
    mounted () {
      Vue.use(VueAnalytics, {
        id: 'xxxxxxxxxx',
        debug: {
          enabled: true
        }
      })
    },
    render: h => h(App)
})
```

**Comment by HeuHax** [comment]
Ahhh yeah of course !

Thanks a lot !

**Comment by MatteoGabriele** [comment]
Maybe not the most elegant way to install a plugin, but it works for this scenario.
I'll add the check soon :)

**Comment by MatteoGabriele** [comment]
see 346f648d56db48ff7ea13633f095276be6603c1f

now in 4.4.0 release
