### ISSUE TITLE
how to use without a router

### ISSUE THREAD

**Issue by z1haze** [MatteoGabriele/vue-analytics#58]
How can this be used just on a plain vue project? I followed the simple getting started where it just has the single use statement and passing in the ID, and its not tracking for me.. There is nothing more to do that call the Vue.use just for basic functionality?

**Comment by MatteoGabriele** [comment]
Hi @z1haze 
well the basic functionality is just that it loads the script for you and it creates the trackers based on your domain ID: but that's it! 
I don't know what you want to track and I have no access to your router instance out of the box, so I can't track your pages.

When you add the router instance to the plugin, then it starts tracking for you automatically every page you made.

If you want to do manual tracking for everything you just have to start yourself like: on the mount life cycle hook of your home page add `this.$ga.page('/home')` for example.

You can find everything you need in the guide.

**Comment by z1haze** [comment]
Thank you, I noticed as well where it mentioned manual setup. I added the this.$ga.page('/') but I wasn't able to get ga loaded. I checked this by monitoring my ga dashboard like usual but it wasn't showing any activity. I was able to get activity to show manually by just pasting the ga snippet from google at the end of the body, outside of the vue scope, so I know it wasn't my account that isn't working.

**Comment by MatteoGabriele** [comment]
the problem with version 4 is the time between action fired and script loaded.
in next release I've introduced the `untracked` feature that will store event fired before google script is properly loaded and then re-fired them as soon as window.ga is injected in your application.

I'm finishing few tests, but it is stable enough, I'm already using it in my projects.

what I suggest for now with version 4 is to mount the entire application using the callback ready or the promise.

other solution is to use the vue-analytics@next release which already takes care of this stuff without need to couple the application mount to the plugin.

**Comment by MatteoGabriele** [comment]
this is the way you could fix your app with version 4 
https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/when-google-analytics-is-loaded.md if you don't want to use the beta version

**Comment by lbogdan** [comment]
@MatteoGabriele Maybe this issue - tracking is ignored until GA script loads and it's initialized - should be mentioned in https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/installation.md , at least until the new version is released. It's basically the first issue you encounter, and it makes for a not so nice developer experience.

Btw, for me `onReady()` worked, `onScriptLoaded()` didn't.

**Comment by MatteoGabriele** [comment]
`onScriptLoaded` it's a promise and `onReady` it's a callback.
I will mention this issue in the README file

**Comment by lbogdan** [comment]
Yes, I know that, what I was saying is that `onScriptLoaded().then(...)` didn't work for me.

**Comment by MatteoGabriele** [comment]
For me works. which version are u running?

**Comment by MatteoGabriele** [comment]
I've added couple of lines in the "Get started" part, where I talk about the script + events problem.
If you can give me your version number for the onScriptLoaded problem, I will check that as well.

thanks guys for the feedback
hopefully i will release the new major version soon

**Comment by lbogdan** [comment]
It's the latest version:
```
  "version": "4.4.0"
```

**Comment by MatteoGabriele** [comment]
I'm not able to reproduce this problem. 
if u have time, would be nice to have a small repository with this problem running and a separate issue.
Thanks again
