### ISSUE TITLE
Check if the script tag is already created and do not crate new if present

### ISSUE THREAD

**Issue by darkopetreski** [MatteoGabriele/vue-analytics#60]
I have a problem using this plugin together with prerender spa plugin. Prerender plugin is used for seo, it takes a snapshot of the page and saves it. Also it contains the script tag. Then, when the page loads, GA is executed and creates a script tag again. And the script tag is duplicated.

I already reported here https://github.com/chrisvfritz/prerender-spa-plugin/issues/102 but it seems it will not be solved. So I was thinking to report this problem here.

This plugin can check if the "<script" tag for google analytics is already present. In that case do not create a new one.

Also this might help
https://github.com/chrisvfritz/prerender-spa-plugin/issues/82

**Comment by MatteoGabriele** [comment]
Hey @darkopetreski 
yeah shouldn't be a problem to add a check on that. I will have a look!

thanks for your feedback

**Comment by darkopetreski** [comment]
Thank you, you are the best :)

**Comment by MatteoGabriele** [comment]
@darkopetreski I've added few lines in the guide so you can choose the approach that works the best for you 
https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/script-loader.md

thanks :)

**Comment by darkopetreski** [comment]
Very nice, thank you!

**Comment by MatteoGabriele** [comment]
@darkopetreski be aware that I can't remove my trackers! I couldn't find a solution for that: it is too important that I create that myself or don't have control on the hits i send.

I hope that this won't be a problem for you're application.
