### ISSUE TITLE
Custom Dimension

### ISSUE THREAD

**Issue by javisoi** [MatteoGabriele/vue-analytics#62]
Question:

I want to send some custom data using a Custom Dimension/Variable? 

Would this be the way of doing so? 
https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/page-tracking.md#auto-track-with-custom-data

**Comment by MatteoGabriele** [comment]
hi @javisoi 
do you have the API reference to this feature you're talking about?
thanks

**Comment by javisoi** [comment]
https://support.google.com/analytics/answer/2709828#example

**Comment by MatteoGabriele** [comment]
you can then just use the `set` method

```js
this.$ga.set('dimension1', 'Level 1');
```

**Comment by javisoi** [comment]
would that be before or after this?

```
Vue.use(VueAnalytics, {
  id: 'UA-XXX-X',
  router,
})
```

**Comment by MatteoGabriele** [comment]
```
import Vue from 'vue'
import VueAnalytics from 'vue-analytics'

Vue.use(VueAnalytics, {
  id: 'UA-XXX-X',
  router,
  ready () {
    Vue.$ga.set('dimension1', 'Level 1')
  }
})
```

**Comment by javisoi** [comment]
ok! thank you for your explanation! I was a bit confused what to do.

**Comment by MatteoGabriele** [comment]
@javisoi you're welcome :)

**Comment by neorganic** [comment]
``` Vue.$ga.set('dimension1', 'Level 1')```
or ``` Vue.$ga.set(field: 'dimension1', value: 'Level 1')``` In current version?

**Comment by rubenheymans** [comment]
where can you find the dimension in google analytics dashboard?
