### ISSUE TITLE
Page Auto Tracking - is it possible to omit the params?

### ISSUE THREAD

**Issue by wolfscott** [MatteoGabriele/vue-analytics#65]
What a great tool -- love it!!

Question: Since this is almost a no-brainer to implement using the Page Auto Tracking, is there a way to omit the params in the routes reported?  It would seem it could "know" the params and be clever.  

I did see where I can omit entire routes, but not specifically any params.

Thanks,
\\//\\//olf

**Comment by MatteoGabriele** [comment]
Hi @wolfscott 
thanks for your feedback: very appreciated! 

Could you be more specific? which params? Do you have a small example?

thanks :)

**Comment by MatteoGabriele** [comment]
Do you mean that there's no way to remove the params of a route to become part of the query string?

**Comment by wolfscott** [comment]
Happy to provide the details -- should have thought to do that before ... :)

That is correct.  The ":projectId" becomes part of the tracked route, thus not receiving a count of "/app/project" specifically

My route as defined in the app:
 { path: '/app/project/:projectId', name: 'AppProject', component: AppProject, props: true },

and the result in analytics:
"/app/project/59218za2d23ed1e81fe53999"

The desired outcome for analytics:
"/app/project"

cheers,
\\//\//olf

**Comment by MatteoGabriele** [comment]
Yesterday I have already added this feature so in the latest version you now can just add this property to your configuration

```js
import Vue from 'vue'
import VueAnalytics from 'vue-analytics'
import router from 'path/to/router'

Vue.use(VueAnalytics, {
  id: 'UA-12345-6',
  router,
  autoTracking: {
    transformRouteParmas: false
  }
})
```

**Comment by wolfscott** [comment]
@MatteoGabriele, thank you very much.  Greatly appreciated.  I looked through the code last night and actually saw that but couldn't get it to work.  Didn't realize you had just added that feature and I had not updated the module to 5.2.0 so that makes sense.  I was just poking and experimenting to see what would happen and it looked like it could be what I was seeking. :)

So I just now updated the module and re-added the param but I'm still not successful in having it omit the params for some reason.  Is there another param I need besides transformRouteParams?  Seems I'm still getting the parameters in the URL.  I'm looking at Google Analytics, real-time view to see these results.

I'm using vue-router, if that makes a difference.

My setup:

Vue.use(VueAnalytics, {
  id: 'UA-xxxxxxx-11',
  router,
  autoTracking: {
    transformRouteParams: false
  }
})

The development URL in the browser:
http://localhost:8010/app/project/5a7647dbf4b372a805c53b65

and Google reports:
/app/project/5a7647dbf4b372a805c53b65

The desired result:
/app/project

**Comment by MatteoGabriele** [comment]
Ok now I got it. 
I did an error calling it `transformRouteParams` because it actually just removes what is passed as queryString from the `page` property.

What you ask is not that simple, to be honest.

Assuming that you have this url `app/project/:slug/item/:id/details` for example, wouldn't you like to add this entire url in your report, instead that only `app/project`?

Probably I have to introduce a custom template for every single route, so that you can customize the behaviour per route.
Something like 

```js
import VueRouter from 'vue-router'

const router = new VueRouter({
    {
       name: 'project',
       path: '/project/:slug',
       meta: {
          analytics: {
              pageviewTemplate (route) {
                 return {
                     page: route.path,
                     title: route.name,
                     location: window.location.href
                  }
              }
          }
       }
    }
})
```

does this make sense?

**Comment by wolfscott** [comment]
@MatteoGabriele, yes, that does make sense.  

Upon some consideration, I wouldn't mind adding an additional parameter to the routes which would be the 'analyticsUrl ' and although would add some redundancy to the routes, but does provide complete control over what is reported.  

Given that I may name my routes anything I choose in my projects, I'm speculating that it is not a breach to have the analytics based on a calculated (or preset) value.  Thus the added field would not constitute an issue.  Further, if I wish to omit a route, simply leave the field off; If I wish two routes to report as the same value, simply duplicate that route detail in the 2nd route.  Seems on the surface as a viable solution.

I'm guessing some would argue the added entry to be redundant; my personal opinion is it's a reasonable tradeoff provided the extra entry doesn't break any existing routing and is simply used for the analytics.  

cheers,
\\//\\//olf

**Comment by MatteoGabriele** [comment]
@wolfscott to maintain everything more abstract and with known patterns, I will add the structure that I have wrote before: so you will be able to write a proxy for what concerns the data that is going to be tracked.

**Comment by wolfscott** [comment]
@MatteoGabriele sounds great -- I appreciate your efforts -- let me know if there is anything I can do to help.

cheers,
\\//\\/olf
