### ISSUE TITLE
Is gtag.js support coming?

### ISSUE THREAD

**Issue by timothynott** [MatteoGabriele/vue-analytics#67]
I love this plugin and hope to be able to use it in an upcoming project. Will there be gtag.js support?

**Comment by MatteoGabriele** [comment]
Thanks man, I've actually never heard about it, I need to have a look and see what I can do

Thanks for the feedback :)

**Comment by timothynott** [comment]
I just setup a new GA instance and saw the new code. Looks like the old way
of doing it will be around for a while.

**Comment by MatteoGabriele** [comment]
I've found this link that talks about migration from analytics to gtag https://developers.google.com/analytics/devguides/collection/gtagjs/migration

I'm going to have a look but for now i'll put it in low priority, also because probably it's quite a big feature to add :)

thanks again

**Comment by MatteoGabriele** [comment]
So I've read about it little bit more and I think that this cannot be really a feature, but probably a totally different package ( as soon as the documentation and its purpose are more clear )
For this moment I will close this issue and see if later on should be open again.

Don't worry, if I come up with another tool I will let you know :)

thanks again: really useful news!

Matteo

**Comment by timothynott** [comment]
No problem. I was thinking at best it might be a fork.

**Comment by MatteoGabriele** [comment]
@timothynott what do you mean with that? :)

**Comment by timothynott** [comment]
I mean given that gtag is substantially different from the prior implementation of GA, it might require a form from the current vue-analytics codebase.

**Comment by voke** [comment]
@MatteoGabriele, I can see that you already reserved the package name [vue-gtag](https://www.npmjs.com/package/vue-gtag). Is there a public git repo where we can follow the progress and contribute?

**Comment by MatteoGabriele** [comment]
@voke yeah sure!
https://github.com/MatteoGabriele/vue-gtag
but it's reeeeally basic, I just reserved the package and created the repo ahahahha 
there's basically nothing yet :)
I want to read the whole documentation first

**Comment by MatteoGabriele** [comment]
@voke feel free to contribute! I will push the boilerplate for development but, has you can see, the project hasn't started yet and the documentation might still be kinda unclear: every kind of help it is super appreciated.

First problem I am encountering is: how to debug with gtag.js? 

Cheers

**Comment by voke** [comment]
@MatteoGabriele According to [this article](https://support.google.com/analytics/answer/1008083?hl=en&ref_topic=1008079) they suggest using Tag Assistant to find errors and warnings. Anyway, I will also read the docs :)

**Comment by MatteoGabriele** [comment]
@voke Thanks man!
They made already to complicated to debug for my taste! They always need to complicate stuff instead of make them easier ahahhahaha
I hope this is not the only way we can debug: I hate to relate on third party extensions/app

**Comment by MatteoGabriele** [comment]
@timothynott I've release a version of vue-gtag still need to finish tests and documentation, but would be nice if you could try it and get some feedback

cheers :)
