### ISSUE TITLE
Recommeneded way to alter route names and paths reported to GA

### ISSUE THREAD

**Issue by lesenther** [MatteoGabriele/vue-analytics#68]
My project is in a sub-directory on my server and I'm using the [base constructor option](https://router.vuejs.org/en/api/options.html) in my router config, which looks like this:

```
export default new Router({
  base: '/app/',
  routes: [{
      path: '/',
      name: 'App',
      component: App
    }]
})
```

Going to https://www.foo.com/app/ causes GA to incorrectly report the 'page' as '/' and not '/app/'.

Potentially related to [issue 43](https://github.com/MatteoGabriele/vue-analytics/issues/43).

**Comment by MatteoGabriele** [comment]
hi @lesenther 
thanks for reporting this: i'm going to check if a base url is added and merge it to the path url.
in the meantime, if you are in a rush, you can do something like this

```js
Vue.use(VueAnalytics, {
   router,
   autoTracking: {
     pageviewTemplate (route) {
        return {
           title: route.name,
           path: `/app/${route.path}`,
           location: window.location.href
        }
     }
   }
})
```

**Comment by wolfscott** [comment]
Don't know if this relevant to this discussion, but figured I would throw this into the mix. If Google receives an '//app/routename' (notice the double leading slashes) it will eat the app and record it as /routename only -- stumbled across this by accident while playing around with constructing a custom template --
