### ISSUE TITLE
Question: Recommended way to add custom GA ads campaign

### ISSUE THREAD

**Issue by duxinxiao** [MatteoGabriele/vue-analytics#69]
Thanks a lot for writing this project. I add some custom GA ads campaign ( just some query string like utm_source, utm_medium ). My web app will receive these query params when load, so should I send it by writing some code? Or if these will be done automatically should I pass the same query string when router change? For now, I'm doing nothing ( just load the web app with query string ), GA data seems to be wrong.

**Comment by MatteoGabriele** [comment]
Hi @duxinxiao 
Sorry I don't really have ads campaign knowledge but I'm pretty sure that these query string parameters are already handled by Google services.
You can maybe read this article [here](https://support.google.com/analytics/answer/1033863?hl=en)

Cheers

**Comment by graup** [comment]
@duxinxiao Have you had success with this? I'm also struggling. Tried a few different things but the utm_source i not tracked in GA.

**Comment by duxinxiao** [comment]
@graup How you add the query params? you have to add both utm_source, utm_medium and utm_campaign, because they are required. You can describe the details. And I can always tracked it in GA( my webapp is in a hybrid app, and my situation is that number of tracked users is wrong, and I decide to use some other tools to track app conversion finally)

**Comment by graup** [comment]
@duxinxiao My app is a real one-page application, I just add `http://domain.com/?utm_source=abc&utm_campaign=foo` and made sure to enable page tracking in vue-analytics. The page view is tracked but without the source...

**Comment by MatteoGabriele** [comment]
Is the data fired from GA correct, when u try it locally with debug enabled? I would check that one first

**Comment by duxinxiao** [comment]
I'm pretty sure you should add utm_medium too, these tree params are required

**Comment by Jones-S** [comment]
@graup I did add all the utm parameters, but they would still not show up in google analytics. I also use some chrome extensions to debug the tracking. The page is correctly tracked, showing up in the real-time tab of GA, but the campaign would not show up.

Parameters:
`utm_source=aerztezeitung&utm_medium=print&utm_campaign=inserat`

In GA I even see this:
<img width="562" alt="image" src="https://user-images.githubusercontent.com/7059580/40953195-e461cc10-68a8-11e8-9d95-f4e57358b8a8.png">

But when I go to the campaigns tab there is no campaign.

So I guess something with the page tracking is still wrong.
What do you exactly mean by _enable page tracking_?

I currently use this:

```
ga('create', 'UA-XXXXXXX', 'auto')
  /*
  ** Every time the route changes (fired on initialization too)
  */
  app.router.afterEach((to, from) => {
    /*
    ** We tell Google Analytic to add a page view
    */
    ga('set', {
      'page': to.fullPath,
      'anonymizeIp': true
    })
    ga('send', 'pageview')
  })
```

thanks for your help.
Cheers

**Comment by graup** [comment]
@Jones-S: Eventually it worked for me. The campaigns just didn't show up in the real time view, but they did later in the reports.
