### ISSUE TITLE
Adblock blocks google analytics

### ISSUE THREAD

**Issue by mesqueeb** [MatteoGabriele/vue-analytics#71]
Dear Matteo,

It seems that Adblock on chrome prevents Google Analytics to be loaded.
I think people who use Adblock are about half, so that's kind of sad.

Any ideas to improve this?

-Luca Ban

**Comment by MatteoGabriele** [comment]
Hi @mesqueeb 
I'm sorry but this is an issue for Google Analytics and AdBlock, not for this plugin that just functions as a wrapper of the Google API.
I can't do much about it

cheers!

**Comment by BenjjinF** [comment]
Handling being blocked by AdBlock in regards to onAnalyticsReady() could be generally useful though.

Can't catch the error on it.
