### ISSUE TITLE
TypeError: Cannot read property 'options' of null

### ISSUE THREAD

**Issue by espiegel** [MatteoGabriele/vue-analytics#72]
Was a breaking change recently introduced?

We're starting to see this error: `TypeError: Cannot read property 'options' of null`

I think it has to do with this line: https://github.com/MatteoGabriele/vue-analytics/blob/master/src/lib/page.js#L35

Currently we are passing in the router as an argument to the page() function but it looks as though the `page` function grabs the router from `src/config.js` which in our case is null and not from the arguments to `page`.

**Comment by MatteoGabriele** [comment]
Hi @espiegel 
yeah you are right, I should check if there's a vue-router instance assigned first
don't know why I gave it for granted!

thanks for your feedback

**Comment by espiegel** [comment]
We're going to use the exact version of `5.1.1` for the meantime instead of `^5.1.1`

**Comment by MatteoGabriele** [comment]
The fix is already published
Obviously feel free to reopen the issue if you still see problems

Thanks a lot for your feedback
