### ISSUE TITLE
Ignore hash jumps with vue-router

### ISSUE THREAD

**Issue by wxsms** [MatteoGabriele/vue-analytics#73]
Hi, thank you for the nice plugin 👍 

Have a simple question here: How can I ignore **hash jumps** (e.g. from `/a/b#1` to `/a/b#2`)? Since vue-router takes this as a route change, so if I pass the entire router instance to this plugin it results in hash jumps are also counted, which is not actually expected.

I have read the doc and found no solutions, can you pls help me?

**Comment by MatteoGabriele** [comment]
Hi @wxsms 
is not possible at the moment, I need to have a look and see how to implement this kind of filter

thanks :)

**Comment by MatteoGabriele** [comment]
Hi @wxsms 
Can you setup a super small reproduction of your issue?
I can't reproduce it on my own

Thanks a lot :)

**Comment by wxsms** [comment]
Maybe you can check out directly on one of my online website:

https://uiv.wxsm.space/alert

Click on any anchors on toc / heading of the page and see how the analytics data send.

Here's how I use your plugin:

https://github.com/wxsms/uiv/blob/master/docs/main.js

You might also want to checkout the router file:

https://github.com/wxsms/uiv/blob/master/docs/router/index.js

Thanks for your help! I can provide any further demos if you found this not clear enough.

**Comment by MatteoGabriele** [comment]
@wxsms so you want to be able to not track that page again at all?
example: I land on the /getting-started page and it tracks it, but if I click on an anchor tag and go to /getting-started#something it shouldn't fire anything, right?

**Comment by wxsms** [comment]
Yes. because user is **actually in the same page** between hash-only route changes.

**Comment by MatteoGabriele** [comment]
@wxsms you can find options [here](https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/page-tracking.md#customize-router-updates)

I've added a simple option, which is the `skipSamePath` property, but it only checks if paths.
If you need something more accurate I've added also the `shouldRouterUpdate` method that allow you to decide which logic apply to the router updates

hope that will solve your problems

thanks for your feedback again :)

**Comment by wxsms** [comment]
Awesome! Thank you very much.
