### ISSUE TITLE
A stylistic suggestion about event tracking

### ISSUE THREAD

**Issue by paumoreno** [MatteoGabriele/vue-analytics#76]
I like the approach of passing the event attributes to `this.$ga.event` as an object.

I think it would be even more comfortable to use if the attribute keys didn't have the `event` prefix (in my opinion it's a bit redundant) so:

 - `eventCategory` -> `category`
 - `eventAction` -> `action`
 - `eventLabel` -> `label`
 - `eventValue` -> `value`

...while maintaining the prefixed keys for backwards compatibility.

What do you think?

Thanks!

**Comment by MatteoGabriele** [comment]
Thanks for your suggestion but I didn't decide the api structure: these names are what Google Analytics needs when you pass an object instead of a series of arguments.

I will leave them like this because they follow a pattern that is persistent in the Google Analytics library

thanks again :)
