### ISSUE TITLE
set('userId', 'some_user_id') does not cause GA to recognize users on the page

### ISSUE THREAD

**Issue by christophmayrhofer** [MatteoGabriele/vue-analytics#79]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description

Setting the userId does not cause data to show up in the GA user id view

### Expected behavior

GA Dashboard shows > 0 active users

### Actual behavior

active users = 0

### Environment

`-- vue-analytics@5.6.0

1. Operating system: WIN 10
2. Browser and version: Chrome 63

### Code
Vue.use(VueAnalytics, {
        id: process.env.googleAnalyticsId,
        router
});

later in another file:

import Vue from 'vue'

Vue.$ga.set('userId', 'some_user_id')

**Comment by MatteoGabriele** [comment]
Hi @christophmayrhofer 
if you enable the debugging mode, is that `userId` hit registered by Google Analytics in the console?

thanks for your feedback

**Comment by christophmayrhofer** [comment]
@MatteoGabriele 

Running command: ga("set", "userId", "DC9867E0-E0CF-11E7-BB84-6B403B8B2EC4")

**Comment by MatteoGabriele** [comment]
try this setup

```js
// Install

import Vue from 'vue'
import VueAnalytics from 'vue-analytics'

Vue.use(VueAnalytics, {
  id: '00000000',
  debug: {
    enabled: true
  }
})

// Component

export default {
  name: 'MyComponent',

  created () {
    this.$ga.set('userId', 123456)
  }
}
```

using the Vue instance or the component scope doesn't matter, this is just to check if in you application you see Googla Analytics script firing the hits in the console.

**Comment by christophmayrhofer** [comment]
@MatteoGabriele 

Setting the user Id from within the component works as well:

Executing Google Analytics commands.
analytics_debug.js:10 Running command: ga("set", "userId", 123456)

Unfortunately the user count still remains 0 in the dashboard.

**Comment by MatteoGabriele** [comment]
Then I'm sorry but probably there are some issues with your account. The API works :)
I don't log these events myself, but I use the Google analytics debug API: they are real data sent to your account.

**Comment by goors** [comment]
same here. on the analytics (user view) dashboard it says 0 users.
