### ISSUE TITLE
Docs for v-ga: this.$ga.track -> this.$ga.event

### ISSUE THREAD

**Issue by FlorianWerndl** [MatteoGabriele/vue-analytics#80]
On the docs page for v-ga: https://matteogabriele.gitbooks.io/vue-analytics/content/docs/v-ga.html

Shouldn't it be 
`this.$ga.event('randomClicks', 'click', 'name', name)` 

instead of
`this.$ga.track('randomClicks', 'click', 'name', name)`

Best

**Comment by MatteoGabriele** [comment]
@FlorianWerndl thanks :)
