### ISSUE TITLE
[Feature request] Consider googleanalytics/autotrack

### ISSUE THREAD

**Issue by DaxChen** [MatteoGabriele/vue-analytics#81]
Consider adding support for [Autotrack](https://github.com/googleanalytics/autotrack)?

Looks promising and very convenient for most use cases!

Thank you for your great package!
Dax

**Comment by MatteoGabriele** [comment]
It sounds very interesting!

Thanks for your feedback :)

**Comment by MatteoGabriele** [comment]
Due to naming conventions, I need to move this feature in the 6.x major version.
Sorry for being late but I had a lot of work :)

thanks!

**Comment by MatteoGabriele** [comment]
Hey @DaxChen I'm literally working on this and I have almost finished, but I'm adding also webpack 4 and other things so...almost there!

**Comment by MatteoGabriele** [comment]
I have a question @DaxChen 
what would be the best way to load this? it's not a package and apparently there's nothing such url that could respect semversioning so I could use a url of the current stable version but if a patch or something comes out you need to wait until I publish a new update and it kinda sucks.

I was thinking about just let you use a property where you paste the url of the version you want but I don't know if I like it.

let me know what are your thoughts on this

thanks :)

**Comment by DaxChen** [comment]
Hi @MatteoGabriele sorry for the late reply. I just came back from vacation 😄

I'm not sure if I fully understand the problem correctly, but `autotrack` is published to npm, why not use the npm version? Or maybe use *peerDependency* instead so users can install any version of autotrack on their own without updating `vue-analytics`.

Thank you so much!!

**Comment by MatteoGabriele** [comment]
@DaxChen 
peerDependencies are a good idea but isn't NPM going to warn every time I install the `vue-analytics` and I don't need `autotrack.js`?

**Comment by MatteoGabriele** [comment]
@DaxChen I know I know, It's getting late with this feature aahhahahah
I was thinking tho that I might move it directly to the vue-gtag repo that I'm working at. Do you know if tracking.js is compatible with gtag.js?

cheers
