### ISSUE TITLE
Newbie quickstart

### ISSUE THREAD

**Issue by mateomorrison** [MatteoGabriele/vue-analytics#82]
Hello, I'm a newbie in VueJS and I am on a constant learning. I need to integrate this to my App, but find it hard to get it working. I created a file called `vue-analytics.js` and try to call it on the router, but it's not tracking.

One thing that helps me get started with new packages are the demos, on an actual App.vue or router/index.js on how to insert it. Please help me, after creating the file with all settings (trackingId, etc) and calling it into vue-router as: `import VueAnalytics from '../services/vue-analytics.js'`.

Thanks!

**Comment by MatteoGabriele** [comment]
well I don't really know your application structure but I can assume that you have a file where you bootstrap you application: something where there is

```js
import router from 'path/router'
import App from 'path/App.vue'

new Vue({
   router,
   render: h => h(App)
}).$mount('#app')
```
So usually what I do is register all plugin before this code is fired and I will have in the case of Analytics something like this

```js
import Vue from 'vue'
import VueAnalytics from 'vue-analytics'
import router from 'path_to_your_source/router'
import App from 'path_to_your_source/App.vue'

Vue.use(VueAnalytics, {
  id: 'blablabla',
  router,
  // debug helps you to see events in the console
  // so you know that something is happening
  debug: {
    enabled: true
  }
})

new Vue({
  router,
  render: h => h(App)
}).$mount('#app')
```

let me know if this helps

**Comment by mateomorrison** [comment]
@MatteoGabriele Hello, this totally worked. I checked analytics and the hits are getting to the right place. The problem is when I run `npm run build` it's showing this:

`ERROR in ./src/main.js
Module not found: Error: Can't resolve 'vue-analytics' in '/home/ubuntu/fangoo/src'
 @ ./src/main.js 12:0-41`

**Comment by MatteoGabriele** [comment]
@mateomorrison I'm glad that it works :)
for the build, I'm sorry but I don't know how you are handing it. Looks like you didn't install the module.

**Comment by henroid** [comment]
@mateomorrison : I've followed your instructions yet, it seems to work locally but not when I deploy

**Comment by MatteoGabriele** [comment]
@henroid if you can create a repository with this issue I can take a look at it

**Comment by henroid** [comment]
We resorted to using analytics directly, however, if it would be valuable to post an example repo, I can post it.

**Comment by MarGul** [comment]
I'm not really sure what I'm doing wrong. I have installed the plugin and in my bootstrap (just like you have showed here above) I set Vue to use VueAnalytics. I can see in my head that the analytics.js is getting inserted (and when I add debug: true I can see analytics_debug.js) so it feels like it's hooked up correctly.

However I can't see any tracking info on my google analytics account. Isn't there something else that I have to do? For example authenticate with google that I own this domain and so on? Or am I installing the plugin wrong?

**Comment by MatteoGabriele** [comment]
hi @MarGul 
I'm not sure why you have this issue, but if data is fired and you see it via logs in the console, I can't do too much after that.
You can read this [article](https://medium.com/@matteo_gabriele/tips-tricks-for-vue-analytics-87a9d2838915) I wrote lately on how to setup few things, but other then that you should check your domain. Maybe you have a new account and still doesn't function correctly.

let me know

**Comment by MarGul** [comment]
Thanks for the rapid answer Matteo. I can't see anything in the logs when I'm trying to fire of a test event using this.$ga.event() and I have debug installed.

I did just create my google analytics account so maybe I just have to wait a bit to see that it's working. Just feels like the real-time should work instantly if everything is setup correctly. 

I did read through that article and everything else that I found on the Internet before writing this comment :)

**Comment by MatteoGabriele** [comment]
@MarGul can you show me exactly how you installed it, including the way you import the library?

**Comment by MarGul** [comment]
import router from './router';

import VueAnalytics from 'vue-analytics';

Vue.use(VueAnalytics, {
    id: 'UA-115412XXX-1',
    router,
    debug: {
        enabled: true
    }
});

/**
 * Create the Vue instance.
 */
const app = new Vue({
    el: '#app',
    store,
    router,
    render: h => h(App)
});`

**Comment by MatteoGabriele** [comment]
@MarGul looks fine. Sometimes developers use es5 imports and the plugin has a default export so it doesn't work and it doesn't throw any errors

**Comment by MarGul** [comment]
@MatteoGabriele 

I do have a little strange setup maybe. If you look at https://github.com/MarGul/Bidder/tree/master/resources/assets/js and then my bootstrap.js and my app.js you could see the setup.

**Comment by MatteoGabriele** [comment]
@MarGul yeah well if I can be honest: it is a little bit strange setup :) 

One thing that you could try tho, is to create just a fresh new app using vue-cli, add your domain and everything and check console logs with debug true and maybe even a look at your stats.

if it works, then you probably have a problem in your application.

**Comment by MarGul** [comment]
Hehe yeah it's the first Vue App I'm building so might have to fix this. I will try tomorrow to create a vue-cli app and see if I can get it to work. Otherwise it feels like there is something wrong with my google analytics account. Thanks for the help, I will keep you posted :)

**Comment by MatteoGabriele** [comment]
@MarGul no worries man!
I always say "more refactoring more skills, more skills more refactoring"
