### ISSUE TITLE
Wouldn't it be nice if $ga is given as the first argument in command?

### ISSUE THREAD

**Issue by ycmjason** [MatteoGabriele/vue-analytics#83]
https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/v-ga.md

According to the above documentation, we have to use bind so that we could access to `this.$ga` in the tracking command. Wouldn't it be nice if the `$ga` is injected by default as the first argument?

**Comment by MatteoGabriele** [comment]
yes would be nice, didn't find a solution so far: I need some time to see what's the best approach on that.
If you have any ideas, drop a PR :)

thanks

**Comment by ycmjason** [comment]
Is it necessary to bind this to the tracking command? I don't think it's a good idea to access to component value in the tracking command anyways. Will inspect and submit a PR.

**Comment by MatteoGabriele** [comment]
yeah that's for sure, I already suggest to avoid that in the documentation.
was the first approach that popped up in my head that day 😄 
Not the best but works and I needed that feature: totally in for a refactor!

**Comment by ycmjason** [comment]
According to what I see you currently don't do anything to the commands right? Just put them to the config?

**Comment by MatteoGabriele** [comment]
nope, it's just an object and I pass the component context in the directive when I read the property

https://github.com/MatteoGabriele/vue-analytics/blob/master/src/directives/ga.js#L14

**Comment by ycmjason** [comment]
Ok. I personally hate the directive. I rather using `@click="doSomething(); $ga.commands.f()`

**Comment by MatteoGabriele** [comment]
I find that kind of approach little bit dirty, but tastes and needs are always different.

**Comment by ycmjason** [comment]
The obvious easy approach would be when `vue-ga` is first initiated, wrap each commands in a function.

```
function(){
  return originalFunction($ga, ...arguments)
}
```

**Comment by ycmjason** [comment]
https://github.com/MatteoGabriele/vue-analytics/blob/9f1d3a2aa2253abc847ae172c622d80c886fd478/src/bootstrap.js#L28
Doesn't look needed..

**Comment by ycmjason** [comment]
After inspecting the code, I have a strong feeling that this whole thing should be redone... hahaha did you make this in a rush?

**Comment by MatteoGabriele** [comment]
First thing first: always keep a polite approach because we don't know each other.
Second: if you have a better solution just do a PR or suggest the actual code, laughing at developers that do open source is the most irritating thing ever, because you can otherwise just do it yourself.

Thanks

**Comment by ycmjason** [comment]
I didn't mean it. Please accept my apologies.

**Comment by MatteoGabriele** [comment]
@ycmjason Thanks 

If you have suggestions for other topics, please add or re-open another ticket, to avoid confusion.
This will be focusing only on the commands and maybe the directive.

I will have a look as soon as possible at the scope of the commands methods asap

thanks again for your feedback
