### ISSUE TITLE
update documentation to reflect new $ga function names

### ISSUE THREAD

**Issue by macheeto** [MatteoGabriele/vue-analytics#84]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description

Documentation lists incorrect function names.

### Expected behavior

Documentation should use new function names.

### Actual behavior

Tracking functions names don't match.

### Environment

Run this command in the project folder and fill in their results:

`npm ls vue-analytics`: 

Then, specify:

1. Operating system:
2. Browser and version:

### Reproducible Demo
Code: this.$ga.event('click', 'click', 'label', 123)
Error message: "this.$ga.event is not a function"

Code: this.$ga.trackEvent('click', 'click', 'label', 123)
Error message: none

**Comment by MatteoGabriele** [comment]
hi @macheeto 
I don't really understand what you wrote, can u be more specific?

**Comment by macheeto** [comment]
Open this link in a browser:
https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/event-tracking.md

Look at examples:
this.$ga.event('category', 'action', 'label', 123)

Function names are out of date, this does not work anymore. Actual function names start with "track" word:
this.$ga.trackEvent('category', 'action', 'label', 123)

You can run this code to see the actual names:
Object.keys(this.$ga).forEach(function(element){
    console.log(element);
});

Maybe this is related to changes in GA code?

**Comment by MatteoGabriele** [comment]
I don't really follow you, where do you read that 'event' it's a deprecated name?
the `$ga` object is created by me and it's an interface of the Googla Analytics API

**Comment by MatteoGabriele** [comment]
well of course if you are using an old version, the documentation is different. Usually also because breaking changes since version 2.

if you want to see old documentation you just need to go and check the tag matching your current package version.

Example: this is your [documentation](https://github.com/MatteoGabriele/vue-analytics/tree/v2.4.0)

**Comment by macheeto** [comment]
I see what happened. Your project's main page shows this:
Requirements: Vue ^2.0.0
At a glimpse that looks like the current vue-analytics version, it's the most prominent number on the page. I added that to package.json thinking that that was the latest vue-analytics version. Can you tell me where is the correct vue-analytics version displayed, is it the npm package field?

**Comment by MatteoGabriele** [comment]
Yes, it's right there on top where you see "npm package" or just check the tags list, or go to npm
