### ISSUE TITLE
e.replace is not a function when using a function for id

### ISSUE THREAD

**Issue by christophmayrhofer** [MatteoGabriele/vue-analytics#85]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description

The docs claim that it is possible to use a function instead of a string to setup the ga ID:

    Vue.use(VueAnalytics, {
        id: () => 'UA-0000000000-0'
    });

### Expected behavior

    Vue.use(VueAnalytics, {
        id: () => 'UA-0000000000-0'
    });

should be equivalent to

    Vue.use(VueAnalytics, {
        id: 'UA-0000000000-0'
    });

### Actual behavior

vue-analytics causes an error: e.replace is not a function
The source code wants to replace the dashes with a string replace and expects e (=id) to be a string at this moment.

### Environment

Run this command in the project folder and fill in their results:

`npm ls vue-analytics`: 
`-- vue-analytics@5.6.0

Then, specify:

1. Operating system: WIN 10
2. Browser and version: Chrome 56

**Comment by MatteoGabriele** [comment]
hi @christophmayrhofer 
this feature has been added after the 5.7.0 release. I suggest you to just to the latest version which is currently 5.8.0

thanks

**Comment by christophmayrhofer** [comment]
Thanks that fixed the problem

**Comment by wannymiarelli** [comment]
This problem is present also in 5.12.x
<img width="1115" alt="schermata 2018-05-30 alle 14 13 01" src="https://user-images.githubusercontent.com/2851947/40719539-3258ef64-6414-11e8-8df9-db8f29530c2d.png">

the array list up to the error is the resolved result of my promise (an array of string as requested)

**Comment by homerjam** [comment]
This still seems to be an issue 🤔

**Comment by MatteoGabriele** [comment]
@homerjam what version you have?

**Comment by homerjam** [comment]
`5.16.4` - I'm using via the official Nuxt.js Google analytics module

**Comment by MatteoGabriele** [comment]
I do need a reproduction to check tho. Something easy done with a simple Vue app. No Nuxt.
Then if works without Nuxt we will isolate the problem
