### ISSUE TITLE
Set userId from vuex store onAnalyticsReady.

### ISSUE THREAD

**Issue by XXLeeS** [MatteoGabriele/vue-analytics#89]
I want to set `userId` from the state in the vuex store after vue instance created.
Therefore, I can't just adding the `set` property to the configuration object.

Here is my code: 
```js
// main.js
const app = new Vue({ ... })
onAnalyticsReady().then(() => {
  if(app.$store.state.userInfo.username)
    app.$ga.set('userId', app.$store.state.userInfo.username)
})
```
However, if I do so, the `userId` won't be set correctly due to it runs before `ga('create', ...)`.
Currently I resolve this problem by `setTimeout`, but I think there should be a better solution.(maybe a new hook?)

**Comment by MatteoGabriele** [comment]
Hi @XXLeeS 
Can I ask what's the use case for this?

Why do you need to set it from the Store? Perhaps is not the best place to handle it, in my opinion.
I would try to keep those things separated.

Thanks for the feedback

**Comment by XXLeeS** [comment]
I store the user login info ( like id, username, ... ) in the vuex store.
Therefore I can use it globally in different components.
Maybe I should not store it in vuex? ( I'm not a pro developer :( )
But no matter where I store these variable, I have to assing it to `userId` after the vue instance created. ( to make sure after user refresh the browser, I still have correct `userId`)

Thanks for help!

**Comment by MatteoGabriele** [comment]
it is a very specific use case and not super easy to tackle.
because your tracking system depends on your user id that comes from an API, I suppose, you should probably try to initialize the entire plugin only when you have that data.

you could try to listen to the store mutation by subscribing to the store and listening to a specific mutation type that matches the one that brings you that data.

in the meantime I'll try to think about a solution

**Comment by MatteoGabriele** [comment]
something like this 

```js
import store from 'your_path/store'

store.subscribe((mutation) => {
  if (mutation.type === 'user_id_mutation_name') {
    Vue.use(VueAnalaytics, {})
  }
})
```

it is not the most pretty thing to type, but it is a little bit better that messing with vue instances in the store and timeouts :)

**Comment by MatteoGabriele** [comment]
Hi @XXLeeS 
I've created a vuex plugin that you can use to fire events from the vuex store.

here an example for your use case, imagine that we retrieve some user data from the `/user` endpoint

```js
const store = new Vuex.Store({
  state: {
    user: {
      id: null
    }
  },
  actions: {
    async getUserData ({ commit }) {
      const response = await axios.get('/user')
      commit('getUserData', {
        user: response.data,
        meta: {
          analytics: [
            ['set', 'userId', response.data.id]
          ]
        }
      })
    }
  },
  mutations: {
    getUserData (state, user) {
      state.user.id = user.id
    }
  }
})
```
let me know if this works for you

**Comment by MatteoGabriele** [comment]
Well actually you should be able to set a user just by calling the store action and nothing else.
Check the new documentation for Vuex in the readme file.

**Comment by goors** [comment]
@xxlee0927 can you please paste the code for your solution for this user tracking. I am going crazy because of the same problem.

**Comment by MatteoGabriele** [comment]
@goors if you create a small application with vue-cli and explain your issue in the repo, I can have a look, otherwise check the documentation for userID or Vuex integration
