### ISSUE TITLE
[Feature] User ID

### ISSUE THREAD

**Issue by thekonz** [MatteoGabriele/vue-analytics#9]
As shown [in the ga docs](https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id), we can set the user id on load or after like this:

```JavaScript
// on load
ga('create', 'UA-XXXXX-Y', 'auto', {
  userId: USER_ID
});

// after load
ga('set', 'userId', USER_ID);
```

I propose, that we implement it like this:

```JavaScript
const userId = '6c4e3e1b-4b4b-4bd7-a6e0-befea10f2fe7';

// on load
Vue.use(VueAnalytics, { id, router, userId })

// after load
Vue.$ga.set('userId', userId);
```

The `$ga.set(...)` should call `ga('set', ...)`.

What do you think?

**Comment by MatteoGabriele** [comment]
Hi @thekonz 
it's a nice one, didn't know about the User Explorer report.

thanks :)

**Comment by MatteoGabriele** [comment]
Feature added with v2.2.0

see 9a200515b84ddf20c8278b5b19356485ad2ae0e7

**Comment by thekonz** [comment]
![oh boy](http://i.imgur.com/89HANHg.gif)

you're quick. thanks!

**Comment by MatteoGabriele** [comment]
Just updated the readme file. 
Obviously I forgot to update it before publishing it! A classic.
