### ISSUE TITLE
Exceeded rate limit for sending hits. Aborting hit.

### ISSUE THREAD

**Issue by msassa** [MatteoGabriele/vue-analytics#91]
When you exceed the quota to send events to analytics, I get that message.
Maybe you consider to add some kind of queue work, to send a event batch and then another, and so on. That will be nice to solve this problem

**Comment by msassa** [comment]
What I want to say, is that I have many articles on the home page, and I want to send an 'impression' event for each one. They are around 50 articles.

Then, in a foreach I sent an event for each article, and fulfilled the GA rate (10 first events and then 1 per second) I start to get that result: Exceeded rate limit for sending hits. Aborting hit.

What I had done in a previous app, was to generate a queue of events to send, and go sending them slowly, so that does not happen.

It would be great if this component would handle that automatically.

**Comment by MatteoGabriele** [comment]
ah ok I get the point now. 
I need to see how to handle it, but looks like a nice idea.

**Comment by MatteoGabriele** [comment]
@msassa Sorry it took me a while to be able to code a bit.
I hope it will work as you expected, otherwise I'm open to suggestions :)

thanks again

**Comment by msassa** [comment]
Thank you @MatteoGabriele 
I will try to use it ..
