### ISSUE TITLE
Vue-analytics for components

### ISSUE THREAD

**Issue by purvishah165** [MatteoGabriele/vue-analytics#92]
How to track components using this? In my application, the route is not changing but the components are dynamically changing as per user selection. In such cases, how do I analyse which components were used?

**Comment by MatteoGabriele** [comment]
if you are not using a routing system or you also need to track component that you are manually switching, you basically have to do it yourself simply using the available api

example
```js
export default {
   name: 'MyComponent',
   created () {
      this.$ga.page('/my-component')
   }
}
```
